### ISSUE TITLE
ui-router $urlRouterProvier.otherwise ignored

### ISSUE THREAD

**Issue by fullstackwebdev** [DaftMonk/generator-angular-fullstack#1004]
Create a vanilla project with ui router, go to app.js, change $urlRouterProvider.otherwise('/') to '/login', no matter what it will be ignored. Any solution?

**Comment by Awk34** [comment]
Works fine for me

**Comment by fullstackwebdev** [comment]
I still was unable to get it to work so I tried doing this on a fresh install of a server, with the latest node, npm and fresh install of yeoman generator-angular-fullstack, I made only one change:

```
[www@foobar statetest]$ git diff
diff --git a/client/app/app.js b/client/app/app.js
index 06f98ed..be5cb98 100644
--- a/client/app/app.js
+++ b/client/app/app.js
@@ -10,7 +10,7 @@ angular.module('testApp', [
 ])
   .config(function ($stateProvider, $urlRouterProvider, $locationProvider, $httpProvider) {
     $urlRouterProvider
-      .otherwise('/');
+      .otherwise('/login');
```

And I still was not redirected to /login on startup.  I guess what I am trying to figure out is how this was able to work for you but not me?  I included the complete log of my terminal : 
http://pastebin.com/1ycXv9Hn

**Comment by Awk34** [comment]
what happens when you enter `localhost:9000/asdf` into your address bar?
