### ISSUE TITLE
Add a Readme.md template

### ISSUE THREAD

**Issue by Awk34** [DaftMonk/generator-angular-fullstack#1005]
It would be nice to also generate a readme file, with details on building, serving, etc

Things to include:
- Node.js/NPM
- Bower
- Install Ruby/Sass
- Install Mongo/SQL locally
- Gulp/Grunt
- Optional server
- running from `dist`

**Comment by equero** [comment]
Excelent Idea. ¿Anyone is working on this feature yet? I could try this weekend.

**Comment by Awk34** [comment]
I haven't started yet, been working on Gulp and eventually getting canary into master. 

It probably wouldn't be too hard. The readme should include all the steps necessary to run the app locally, so if the user didn't scaffold a backend, it wouldn't show any of that, if he/she chose MongoDB it would talk about running the MongoDB daemon locally, etc. etc.

**Comment by jeshuamaxey** [comment]
I've found that when I start a project with this generator and then hand it off or involve another dev, showing them the readme of this repo helps them get up to speed. I think the same info (particularly sub generator commands) should be included, if not directly in the readme then in a contributing.md also generated. I'm being wary not to fill the readme with bloat before it even exists :)

**Comment by Awk34** [comment]
The generated readme wouldn't include any information about the generator commands. It's possible, however, to include a `contributing.md` file as well, explaining how certain things in the generated project work, but depending on how much info it would contain, it could just go in the readme.

**Comment by josephmilla** [comment]
Any update? I could take a stab on this.

**Comment by Awk34** [comment]
@josephmilla I've got a basic example of it
