### ISSUE TITLE
Increase security by splitting user and admin pages.

### ISSUE THREAD

**Issue by bwasnie1** [DaftMonk/generator-angular-fullstack#1020]
I was wondering if it would increase the security if I would split the webapp into one for users and one for admins. Sure, it depends on the needs, but if you want to build some fancy stuff where you have full control of the system as admin, like payouts or bills, you really want to keep of any curious user who knows a bit of webdevelopment and security.
 
As you can see in the navbar for example, it's easy to see with ```ng-show='isAdmin()'``` that there is an hidden link which points to ```/admin```. I know you need the right ```role``` permission for that, but any additional info you give the user, makes it easier for him to do bad things.

Just a thought. What do you think? Creating two different webapps which use the same database.

**Comment by Awk34** [comment]
That's not practical at all. It's a web app, you should assume that anyone can poke around and find your other views. This is especially true for people like me, whom host their web app's source code publicly on GitHub. You would then also have to spend a whole lot of time splitting your app up, and maintaining both versions simultaneously. Then, even if your front-end views are completely secure, if your back-end is vulnerable all your work is wasted. Of course, if you can practically prevent code-sniffing you should, but as long as your back-end is rock solid, it shouldn't be something to worry about a whole lot.
