### ISSUE TITLE
[UnauthorizedError: invalid signature] using passportjs.

### ISSUE THREAD

**Issue by toriumi0118** [DaftMonk/generator-angular-fullstack#1022]
Hi, I'm new for this project.
I'm developing web app with twitter, google, facebook passportjs which is created by the template.

When I login, 
```
UnauthorizedError: invalid signature
```
occurs.

So, I tried to find out a cause.
Then I think 

https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/server/auth(auth)/auth.service.js#L69

might have problem.

The JSON#stringify put double quote to token. After apply that, whenever I get token value from the cookie, the token surrounded by double quote.
So my validateJwt in isAuthenticated method throw the error.

Could you please tell me, why the JSON#stringify is needed.

**Comment by Forestdev** [comment]
I am getting the same error. I reverted all the changes I made, and still get this error. What gives?

**Comment by toriumi0118** [comment]
@Forestdev 
I changed the line to

```js
 res.cookie('token', token);
```

then you can get non-quoted token value to the browser and you can keep valid token to the cookie.
So work properly.
