### ISSUE TITLE
Deperecated Dependency

### ISSUE THREAD

**Issue by dzeroone** [DaftMonk/generator-angular-fullstack#1023]
deprecated jsonwebtoken@1.1.2: Critical vulnerability fix in v5.0.0. See https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/

**Comment by Awk34** [comment]
See https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/_package.json#L19
