### ISSUE TITLE
The generated application still depends on a vulnerable version of jsonwebtoken

### ISSUE THREAD

**Issue by gvelo** [DaftMonk/generator-angular-fullstack#1030]
The scaffold still has a dependency on jsonwebtoken@4.2.2 , please update to the latest socketio-jwt version.

    ├─┬ socketio-jwt@3.0.0
    │ │ authenticate socket.io connections using JWTs
    │ │ git+https://github.com/auth0/socketio-jwt.git
    │ │ https://github.com/auth0/socketio-jwt
    │ ├─┬ jsonwebtoken@4.2.2
    │ │ │ JSON Web Token implementation (symmetric and asymmetric)
    │ │ │ git+https://github.com/auth0/node-jsonwebtoken.git
    │ │ │ https://github.com/auth0/node-jsonwebtoken

**Comment by yoshiokatsuneo** [comment]
I just made a pull-request to update packages. https://github.com/DaftMonk/generator-angular-fullstack/pull/1021
