### ISSUE TITLE
oauth strategies not compatible

### ISSUE THREAD

**Issue by pbrain19** [DaftMonk/generator-angular-fullstack#1035]
Trying to create user by login in to facebook then doing the same with google fails due to not catching scenario in passport.js of both fb, and google folders to ensure that if user with same email already exist we need to update the info.

**Comment by Awk34** [comment]
While this would be ideal, email can't always be used as a unique identifier. Plenty of OAuth strategies don't give out an email address (GitHub for example). Also, if a user registered me1@example.com for Facebook and me2@example.com for Google, we would also be SOL. Really we can't always rely on email.

**Comment by pbrain19** [comment]
So letting the app fail is acceptable ?

**Comment by pbrain19** [comment]
And I'm well aware that some don't give out an email... However by default the risk for failure is present and this is something I don't agree with.

**Comment by remicastaing** [comment]
We should make a difference between the email address as login and the email address as email address. As login, you can't have to times the same email address. As email address, it's ok.
We could prepare some ways (hooks) to merge account with a same verified email address (as email address) if provided.
