### ISSUE TITLE
cdnify takes forever

### ISSUE THREAD

**Issue by luckylooke** [DaftMonk/generator-angular-fullstack#1036]
Running "cdnify:dist" (cdnify) task
Going through dist/public/index.html to update script refs
GET /api/things 200 119987ms
^C

Execution Time (2015-07-06 16:43:46 UTC)
cdnify:dist      35m 2.2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 99%
Total 35m 22.9s

After 35min I have to Ctrl+C

**Comment by Awk34** [comment]
Seems like it's a problem with `grunt-cdnify`. Do you have any details?

**Comment by luckylooke** [comment]
Fresh install and I just try to build.. it stops on cdnify, so I have to cancel it after half hour of waiting. I have Ubuntu 14.04 64bit. What else?

**Comment by Awk34** [comment]
I don't encounter any issues on Ubuntu with a fresh install. There must be something different with your setup. Post any details that would be potentially helpful (especially version numbers).

**Comment by luckylooke** [comment]
I was checking versions and I have found that grunt-cdnify is not installed at all.
```
$ node -v
v0.12.6
$ npm -v
2.12.1
$ grunt --version
grunt-cli v0.1.13

$ npm list grunt-cdnify
zoom@0.0.0 /home/ctibor/projects/zoom
└── (empty)

npm ERR! code 1
```

I was scaffolding project via yeoman with choosing:
```
# Client

? What would you like to write scripts with? JavaScript
? What would you like to write markup with? HTML
? What would you like to write stylesheets with? CSS
? What Angular router would you like to use? uiRouter
? Would you like to include Bootstrap? Yes
? Would you like to include UI Bootstrap? Yes

# Server

? Would you like to use mongoDB with Mongoose for data modeling? Yes
? Would you scaffold out an authentication boilerplate? Yes
? Would you like to include additional oAuth strategies? Google, Facebook, Twitter
? Would you like to use socket.io? Yes
```

**Comment by Awk34** [comment]
Well it should actually be under `grunt-google-cdn`

**Comment by luckylooke** [comment]
aha..
```
$ npm list grunt-google-cdn
zoom@0.0.0 /home/projects/myProject
└── grunt-google-cdn@0.4.3 
```

**Comment by luckylooke** [comment]
Updated version of generator works correctly.

**Comment by Awk34** [comment]
:D awesome

**Comment by milrak** [comment]
I have same problem: cdnify takes forever.

npm list grunt-google-cdn
project@ /dir/project
└── grunt-google-cdn@0.4.3 

When I run `grunt cdnify` ,my terminal locked forever
