### ISSUE TITLE
Run Php

### ISSUE THREAD

**Issue by GiankOtarola** [DaftMonk/generator-angular-fullstack#1037]
It is possible to run a php file?
Because I use $http to get data from an api, but wherever I put the php file, I get that the file is not found and if I try to acces to the php via URL, the file is download.

**Comment by eddiemonge** [comment]
What is the php file doing? Can you rewrite it in JS and then serve it?

**Comment by GiankOtarola** [comment]
It´s appear to download the file. I mean that when I run grunt serve and I want to post in the php file with $http, it said the error that it can be found and I think that I cant run any php file. I have to config grunt file to run or use php files?

**Comment by Awk34** [comment]
Node.js is a JavaScript engine. If you want to run PHP code via a Node.js server, you might want to look into something like [node-php](https://github.com/davidcoallier/node-php). Or you could just go with one of the standard PHP servers.
