### ISSUE TITLE
Problem with new yeoman version

### ISSUE THREAD

**Issue by epworthhh** [DaftMonk/generator-angular-fullstack#1038]
Hello!

I have a problem with the new yeoman version. Problems in generator and when i do "grunt serve".

if u know something about this please help me.

Thank you

**Comment by eddiemonge** [comment]
@epworthhh You need to provide more details than that please.

**Comment by epworthhh** [comment]
First, my apologies for the delay.

Finally i could create a project without problems, but when i do "grunt server":

"Running "concurrent:server" (concurrent) task
    Warning: Running "sass:server" (sass) task
    Warning: 
    You need to have Ruby and Sass installed and in your PATH for this task to work.
    More info: https://github.com/gruntjs/grunt-contrib-sass
     Use --force to continue.
    
    Aborted due to warnings."

**Comment by epworthhh** [comment]
Ok I got it. I just had to install Sass using <addr>gem install sass</addr> and now everything is fine...couldn't be easier.

**Comment by Awk34** [comment]
Yup, but you do point out that we don't have instructions to do that anywhere AFAIK. I will include this in the new README that I'm making for #1005. Thanks.
