### ISSUE TITLE
favicon / apple touch icon

### ISSUE THREAD

**Issue by samcreate** [DaftMonk/generator-angular-fullstack#1041]
I tried putting these icons in /client and ../client and I don't see them getting link after running the build command. Am I missing something?

**Comment by kingcody** [comment]
You'll need to add a link to your `index.html` like:
```html
<link rel="apple-touch-icon" href="apple-touch-icon.png">
```

See https://github.com/h5bp/html5-boilerplate/commit/345925f04384b59929d8d39ba428cef548921408 for more detail.

(since the generator does not create apple touch icons, adding the link by default would cause 404's)

**Comment by kingcody** [comment]
@samcreate I'm going to go ahead and close this. If you have any more issues feel free to reopen.
