### ISSUE TITLE
grunt build not replacing build:js blocks with reference to minified file

### ISSUE THREAD

**Issue by coreyog** [DaftMonk/generator-angular-fullstack#1047]
I was in a very similar situation as this issue: https://github.com/DaftMonk/generator-angular-fullstack/issues/164

My issue is that no matter what I change, `grunt build` or maybe more specifically the `usemin` task won't update my index.html to convert the references to the generated vendor.js or vendor.css

I have these blocks:

    
    
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css" />
    
    

and

    
    
    <script src="bower_components/jquery/jquery.js"></script>
    <script src="bower_components/angular/angular.js"></script>
    <script src="bower_components/bootstrap/dist/js/bootstrap.js"></script>
    <script src="bower_components/angular-route/angular-route.js"></script>
    <script src="bower_components/angular-bootstrap/ui-bootstrap-tpls.js"></script>
    <script src="bower_components/ng-lodash/build/ng-lodash.js"></script>
    <script src="bower_components/ng-idle/angular-idle.js"></script>
    
    

My Gruntfile.js: http://pastebin.com/bLyVnHST
My `grunt build` Output: http://pastebin.com/xLVddMfP

dist/scripts contains both my scripts.js and vendor.js WITH CONTENT. Same thing for dist/styles having main.css and vendor.css.

However, despite all files being generated correctly, dist/index.html is not updated to reference them.

It still has the above blocks. No errors are generated anywhere that I can see. I've tried updating `build:css` and `build:js` to all the values mentioned in the other issue (linked above) i.e. `build:js(./)`, `build:js(.)`, `build:js(./app)`, or `build:js(app/..)`. Some of them created empty vendor.js files but no matter what it never updated index.html to point to vendor.js.

What really kills me is that just last week I was on a mac and this worked. I have since received my permanent work laptop that's running windows and now it's not working. I also find it extremely weird that my other root level html files (403.html, login-error.html, etc) ARE getting modified to link to vendor.js but those files don't look any different than index.html.

I have already run `npm update -g yo bower grunt`

**Comment by coreyog** [comment]
Nevermind, found my issue. My grunt-bower-install plugin is injecting js scripts and ending the lines with unix line endings (\n) where this plugin is looking for windows endings (\r\n).

**Comment by hishwest** [comment]
@coreyog  : how did you solve the problem please , have ou change all html ending line to unix line ending or have you re-install bower , i din't understand . txs in advance

**Comment by Awk34** [comment]
@hishwest Make sure that all of your files only use one line ending style. I use the `dos2unix` program to change CRLF to LF.
