### ISSUE TITLE
Error: GET /api/things

### ISSUE THREAD

**Issue by jshaker** [DaftMonk/generator-angular-fullstack#1050]
After running grunt command, this happens.
http://i.imgur.com/fkhCbMz.png

Needless to say grunt serve doesn't successfully host the app.

I followed all the steps, ran npm install and bower install post installation just to be sure. My selections were:
-JavaScript
-Jade
-CSS
-No Bootstrap
-No Scaffold

Any clues?

**Comment by Awk34** [comment]
Go to https://www.mongodb.org/, download and install MongoDB, and then run the `mongod` command from your shell. Let me know how it works out.
