### ISSUE TITLE
Why is serveClient set to false in prodcution 

### ISSUE THREAD

**Issue by programming-kid** [DaftMonk/generator-angular-fullstack#1053]
i am playing around with socket io when i found following line of code in app.js

```javascript
var socketio = require('socket.io')(server, {
    serveClient: (config.env === 'production') ? false : true,
    path: '/socket.io-client'
});
```
and i am wondering why is serveClient set to false in production , i goggled a lot but couldn't find much info on this , i guess this option is used to serve static socket io client file , if it is set to false in production how is client served in production 

can anyone pls explain this 

thanks

**Comment by kingcody** [comment]
@programming-kid, hi there; how have you been?

Explanation: The socket.io client file is concatenated and minified into `vendor.js` when the project is built.

**Comment by programming-kid** [comment]
m good @kingcody  thanks for the explanation  :+1:
