### ISSUE TITLE
Having trouble to register socket to nested collection

### ISSUE THREAD

**Issue by jolacaleb** [DaftMonk/generator-angular-fullstack#1058]
I'm trying to implement simple notification system. For that, I made a nested collection named 'notification' inside 'User' collection.

I am trying hard to make socket broadcast when 'notification' collection added.

But as the collection is not a model (or schema) in mongoose, I have no idea how to register.

This is a template which generator has made for me.

**/server/api/user/user.socket.js**
```javascript
var User = require('./user.model');

exports.register = function(socket) {
  User.schema.post('save', function (doc) {
    onSave(socket, doc);
  });
  User.schema.post('remove', function (doc) {
    onRemove(socket, doc);
  });
};
```
I think I can write a code similar with it, so I tried <code>User.schema.notification.post</code> something like this... How silly I am.

I made router able to get message.

So what I'm stuck on is I can get existing data from mongodb, but I want to <code>syncupdates</code> it through socket.io.

Can anybody help me? or can anybody just let me know where to start? Thank you.

**Comment by Awk34** [comment]
While I can tell you that this is a question best asked somewhere like StackOverflow, I'll also say it looks like what you're doing is a bad idea. MongoDB doesn't like growing documents. Also, dig into the Socket.io and MongoDB code to see how it all works together.
