### ISSUE TITLE
How to use the latest version ?

### ISSUE THREAD

**Issue by ritz078** [DaftMonk/generator-angular-fullstack#1060]
How can I use the latest code since the last version available on npm is 10 months older and it has no support for babel.

**Comment by DanMMX** [comment]
Checkout canary branch, it has the latest working code

**Comment by Awk34** [comment]
Clone the code, run `npm install` and then `npm link`, run `yo angular-fullstack` as normal.

**Comment by Awk34** [comment]
I plan on pushing to NPM soon

**Comment by ritz078** [comment]
Thanks :smile:
