### ISSUE TITLE
Flow.js causes build error (Warning: Unable to read "dist/public/bower_components/flow.js" file (Error code: EISDIR))

### ISSUE THREAD

**Issue by jshultz** [DaftMonk/generator-angular-fullstack#1064]
Is there a process for resolving or getting around this issue: `Warning: Unable to read "dist/public/bower_components/flow.js" file (Error code: EISDIR)`

The only one I've found that works is is a [workaround](https://github.com/flowjs/flow.js/issues/73). But I still have to use --force in order to get it to build and deploy correctly.

EDIT: the other problem is, even with this fix, you have to run `grunt build --force` in order for it to work. :/

**Comment by kingcody** [comment]
@jshultz which task is failing? Small log post please?

**Comment by jshultz** [comment]
Sure, here you go:

`
Running "usemin:js" (usemin) task

Processing as JS - dist/public/app/8d8978e0.vendor.js
Update the JS to reference our revved images

Processing as JS - dist/public/app/e60d0032.app.js
Update the JS to reference our revved images

Processing as JS - dist/public/bower_components/flow.js
Warning: EISDIR, illegal operation on a directory Used --force, continuing.
`

**Comment by kingcody** [comment]
@jshultz can you try something for me?
Can you change your original `rev` block in `Gruntfile.js` from:
```javascript
    rev: {
      dist: {
        files: {
          src: [
            '<%= yeoman.dist %>/client/{,*/}*.js',
            '<%= yeoman.dist %>/client/{,*/}*.css',
            '<%= yeoman.dist %>/client/assets/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}',
            '<%= yeoman.dist %>/client/assets/fonts/*'
          ]
        }
      }
    },
```
to this:
```javascript
    rev: {
      dist: {
        files: {
          src: [
            '<%= yeoman.dist %>/client/!(bower_components)/{,*/}*.js',
            '<%= yeoman.dist %>/client/!(bower_components)/{,*/}*.css',
            '<%= yeoman.dist %>/client/assets/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}',
            '<%= yeoman.dist %>/client/assets/fonts/*'
          ]
        }
      }
    },
```

**Comment by jshultz** [comment]
Mine doesn't look like that? Mine looks like:

```
// Renames files for browser caching purposes
    rev: {
      dist: {
        files: {
          src: [
            '<%= yeoman.dist %>/public/{,*/}*.js',
            '<%= yeoman.dist %>/public/{,*/}*.css',
            '<%= yeoman.dist %>/public/assets/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}',
            '<%= yeoman.dist %>/public/assets/fonts/*'
          ]
        }
      }
    },

```

**Comment by kingcody** [comment]
Sorry, that was my mistake (copying from the wrong branch).

How about changing it to this:
```javascript
    rev: {
      dist: {
        files: {
          src: [
            '<%= yeoman.dist %>/public/!(bower_components)/{,*/}*.js',
            '<%= yeoman.dist %>/public/!(bower_components)/{,*/}*.css',
            '<%= yeoman.dist %>/public/assets/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}',
            '<%= yeoman.dist %>/public/assets/fonts/*'
          ]
        }
      }
    },
```

**Comment by jshultz** [comment]
No worries, I've been there before.

So, I tried that and:

```

// Renames files for browser caching purposes
    rev: {
      dist: {
        files: {
          src: [
            '<%= yeoman.dist %>/public/!(bower_components)/{,*/}*.js',
            '<%= yeoman.dist %>/public/!(bower_components)/{,*/}*.css',
            '<%= yeoman.dist %>/public/assets/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}',
            '<%= yeoman.dist %>/public/assets/fonts/*'
          ]
        }
      }
    },

Processing as JS - dist/public/bower_components/flow.js
Warning: EISDIR, illegal operation on a directory Use --force to continue.
```

**Comment by kingcody** [comment]
Well, that seemed to fix the issue on code generated by the `canary` branch. Let me see if I can reproduce on the `master` branch.

**Comment by jshultz** [comment]
can I update an existing application that's already built to the latest version? I'm not sure how that works. I'll let you figure out the first issue first, though. :)

**Comment by kingcody** [comment]
As far as that goes, there isn't a clear upgrade path for migrating an existing app.

**Comment by jshultz** [comment]
ok, no biggie I can make that work pretty easy. :)

**Comment by kingcody** [comment]
Ok, well https://github.com/DaftMonk/generator-angular-fullstack/issues/1064#issuecomment-121796285 got us a little bit closer. That excluded `bower_components` from the `rev` block.

Now we just need to do the same for the `usemin` block:
```javascript
    usemin: {
      html: ['<%= yeoman.dist %>/public/!(bower_components)/{,*/}*.html'],
      css: ['<%= yeoman.dist %>/public/!(bower_components)/{,*/}*.css'],
      js: ['<%= yeoman.dist %>/public/!(bower_components)/{,*/}*.js'],
      ...
    },
```

I think its safe to say that we don't need usemin rewriting asset references in our bower dependencies (:

**Comment by jshultz** [comment]
Guess what? That fixed all the things! :) Awesome! :)

**Comment by kingcody** [comment]
@jshultz I'd like to share an interesting tidbit with you.

There is a newer version of `grunt-usemin` in `canary` and they have fixed the problem in their module (which is why I didn't have the usemin issue when testing canary branch). However like I said, I feel that we should probably exclude the `bower_components` folder anyways.

The other thing is that there is a newer (more maintained) module called `grunt-filerev` which does the same task as `grunt-rev` and they have also fixed this issue in their module as well.

**Comment by jshultz** [comment]
ok, cool. thanks for the heads up. :)

**Comment by adam-back** [comment]
Also useful: this is an issue with an folder which has .js in the file name. Examples include, Chart.js, flow.js, etc.

Solution from https://github.com/cbas/grunt-rev/issues/29#issue-50205873:

>It seems the grunt rev section in its current form can't distinguish between a directory ending in ".js" and a .js file. Grunt-rev (and subsequently usemin) will fail with
```
Warning: Unable to read "dist/public/bower_components/spin.js" file (Error code:
 EISDIR). Use --force to continue.

>Aborted due to warnings.
```
>In the below Gruntfile.js section, I fixed the problem by singling out each .js/ directory (spin.js is a project name and a .js file, for example) and excluding it. If you can tell me a more general way to do it by regex I would appreciate it.
```
   > // Renames files for browser caching purposes
    rev: {
      dist: {
        files: {
            src: [
                '<%= yeoman.dist %>/public/**/*.js',
                '<%= yeoman.dist %>/public/**/*.css',
                '<%= yeoman.dist %>/public/assets/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}',
                '<%= yeoman.dist %>/public/assets/fonts/{,*/}*.ttf',
                '!<%= yeoman.dist %>/public/bower_components/openlayers/tests/node.js',
                '!<%= yeoman.dist %>/public/bower_components/spin.js'
          ]
        }
      }
    },
```
