### ISSUE TITLE
grunt build on windows 8 includes every js file under client folder

### ISSUE THREAD

**Issue by tommysanterre** [DaftMonk/generator-angular-fullstack#1075]
When runing grunt build on windows 8 the output index.html include the built app.js but also all the individual .js files under the client folder. 

However those files are not copied during the build and many error 404 are shown in the console.

I believe this section should not be in the built index.html
```
<!-- injector:js -->
<script src="app/main/main.controller.js"></script>
<script src="app/main/main.js"></script>
<script src="components/navbar/navbar.controller.js"></script>
<!-- endinjector -->
```

**Comment by Awk34** [comment]
Usemin requires you to have LF line endings. Make sure to convert `index.html`'s line endings to LF before you try to build.

**Comment by tommysanterre** [comment]
@Awk34 fixed my issue thanks.

**Comment by tommysanterre** [comment]
The generator already include a .gitattributes file. To prevent this error the .gitattributes file could enforce lf file ending.

**Comment by Awk34** [comment]
I believe it does: https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/.gitattributes#L1

**Comment by tommysanterre** [comment]
Looks like it you're right. However when i generate a project with the latest release the .gitignore file does not enforce lf file ending.
```
* text=auto
```
Maybe the latest release does not include this change.
