### ISSUE TITLE
Using grunt serve:dist with Babel doesn't work

### ISSUE THREAD

**Issue by DanMMX** [DaftMonk/generator-angular-fullstack#1086]
Anything is available when running `grunt serve:dist`

```

GET /app/app.css 404 401ms
GET /app/app.js 404 6ms
GET /app/account/account.js 404 8ms
GET /app/account/login/login.controller.js 404 7ms
GET /app/account/settings/settings.controller.js 404 10ms
GET /app/account/signup/signup.controller.js 404 13ms
GET /app/admin/admin.controller.js 404 8ms
GET /app/admin/admin.js 404 6ms
GET /app/main/main.controller.js 404 8ms
GET /app/main/main.js 404 7ms
GET /components/auth/auth.service.js 404 6ms
GET /components/footer/footer.directive.js 404 8ms
GET /components/modal/modal.service.js 404 7ms
GET /components/navbar/navbar.controller.js 404 7ms
GET /components/navbar/navbar.directive.js 404 4ms
GET /components/sequelize-error/sequelize-error.directive.js 404 3ms
GET /components/socket/socket.service.js 404 2ms

```

The only weird thing I saw on the compile process was

```
Running "ngtemplates:main" (ngtemplates) task
>> No templates found
File .tmp/templates.js created.
Added .tmp/templates.js to <!-- build:js app/app.js -->
```

But don't think that is the problem

<img width="1079" alt="captura de pantalla 2015-08-06 a las 10 34 14" src="https://cloud.githubusercontent.com/assets/1919322/9115881/f0c73000-3c26-11e5-892e-fb221beee512.png">

**Comment by kingcody** [comment]
@DanMMX can you explain the issue here?

**Comment by DanMMX** [comment]
@kingcody just updated the details, sorry for the delay I missed the notification

**Comment by Awk34** [comment]
Is this on a fresh install?

**Comment by DanMMX** [comment]
yes, it was, I might lot of other stuff

**Comment by orapouso** [comment]
It happened something like that but it does not depends on Babel. Any fresh install grunt serve:dist will have the same outcome, with or without Babel.

I happened to see that the minified version of the app.js is generated but the reference to the original files is not deleted from index.html.

```html
Generated app.js part of index.html
<!-- build:js({.tmp,client}) app/app.js -->
    <script src="app/804e8d51.app.js"></script>
    <!-- injector:js -->
    <script src="app/main/main.controller.js"></script>
    <script src="app/main/main.js"></script>
    <script src="components/navbar/navbar.controller.js"></script>
    <!-- endinjector -->
<!-- endbuild -->

The <!-- injector--> part is not removed
```

Somehow, if you just delete the injector comments `<!-- injector --> <!-- endinjector -->`, save, generate, then undo that and generate again the problem does not appear again and the injector works as expected.

Tried to debug all I could but couldn't find the problem. Hope that helps.

**Comment by Awk34** [comment]
It looks like it might be more line endings issues. Usemin doesn't like `crlf` line endings. Try making sure you are using only `lf` line endings.

**Comment by DanMMX** [comment]
How can I check that @Awk34 ?

**Comment by kingcody** [comment]
There is a tool called `dos2unix` that can do the conversations for you.

**Comment by orapouso** [comment]
What I find odd is that I just do the yo angular-fullstack -> grunt
serve:dist on linux. How come that could be line ending problems?

**Comment by DanMMX** [comment]
I run it on Mac, not sure if that changes things @orapouso , will check that @kingcody :+1:

**Comment by IcebergRage** [comment]
I got the same problem.

A part of my app use the good index.html (the minify one) but another part use the non-minify index.html
I tried the @orapouso solution, it doesn't work for me.

**Comment by james075** [comment]
up?

**Comment by DanMMX** [comment]
@kingcody @Awk34 nope, used already the dos2unix tool and "converted" the files to UNIX files … didn't worked, any other idea?

**Comment by kingcody** [comment]
@DanMMX it might be easiest if you could post you project in a repo and see if I or someone else can reproduce.

**Comment by kingcody** [comment]
@IcebergRage that because the second example is not using HTML5 mode and instead setting the url directly.

**Comment by DanMMX** [comment]
@kingcody this is it https://bitbucket.org/DanMMX/casacuestacentro

**Comment by kingcody** [comment]
@DanMMX this should fix it:
**`Gruntfile.js`**
```diff
		usemin: {
-			html: ['<%= yeoman.dist %>/client/!(bower_components)/{,*/}*.html'],
+			html: ['<%= yeoman.dist %>/client/{,!(bower_components)/**/}*.html'],
			css: ['<%= yeoman.dist %>/client/!(bower_components)/{,*/}*.css'],

**Comment by DanMMX** [comment]
Worked perfectly @kingcody , can you explain me what does that change mean? `{,!(bower_components)/**/}*` gonna close this as it's not an issue anymore.

**Comment by kingcody** [comment]
`<%= yeoman.dist %>/client/{,!(bower_components)/**/}*.html` expands to `<%= yeoman.dist %>/client/*.html` and `<%= yeoman.dist %>/client/!(bower_components)/**/*.html`

**Comment by DanMMX** [comment]
ah, was about to make a PR for it but it's already merged, thanks @kingcody :+1:

**Comment by kingcody** [comment]
@DanMMX no problem, and thank you for all the help you have provided so far with testing the `3.0.0` release.
