### ISSUE TITLE
get logged out on refresh

### ISSUE THREAD

**Issue by chovy** [DaftMonk/generator-angular-fullstack#1087]
I thought a user object was stored client side in a session, but I'm not seeing it.

`$rootScope.currentUser = $cookieStore.get('user') || null;`

I'm using a slightly older version 1.x

**Comment by kingcody** [comment]
I'm not sure, but I believe in `1.x` there was a `Session` resource that handled that.

**Comment by chovy** [comment]
It looks like it was handled by `$cookieStore` which is deprecated in 1.3

**Comment by kingcody** [comment]
`generator-angular-fullstack@3.0.0-rc5` has been released with `angular@~1.4.0` and `angular-cookies@~1.4.0`.

**Comment by chovy** [comment]
I can't really update....this generated code isn't really updatable.

Can you point me to the line that handles this in the new version so I can copy it into my Auth controller?

**Comment by kingcody** [comment]
Here: https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/client/components/auth%28auth%29/auth.service%28js%29.js#L17-L19

And here: https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/client/app/app%28js%29.js#L26-L28
