### ISSUE TITLE
feat(grunt): remove grunt-autoprefixer, add grunt-postcss

### ISSUE THREAD

**Issue by macneib** [DaftMonk/generator-angular-fullstack#1089]
relatively simple change over
````
npm install grunt-postcss pixrem autoprefixer-core cssnano --save-dev
````
in app/gruntFile.js

remove: 
````javascript
autoprefixer: {
  options: {
    map: true,
    browsers: ['last 1 version']
  },
  dist: {
    expand: true,
    cwd: '.tmp/',
    src: '{,*/}*.css',
    dest: '.tmp/'
  }
}
````
and add:

````javascript
postcss: {
  options: {
    map: true,
    processors: [
      require('autoprefixer-core')({browsers: ['last 1 version']})
    ]
  },
  dist: {
    expand: true,
    cwd: '.tmp/',
    src: '{,*/}*.css',
    dest: '.tmp/'
  }
},
````

then in gruntFile switch autoprefixer over to postcss

Any objections?

**Comment by kingcody** [comment]
No objections here; we should definitely move away from deprecated modules.

**Comment by macneib** [comment]
@kingcody Pull requests go to canary right?

**Comment by gabovanlugo** [comment]
I think this thing is deprecated again.

[https://github.com/ai/autoprefixer-core](url)

**Comment by Koslun** [comment]
We're moving away from grunt itself with the upcoming 4.0 release. But please do open up another issue if you want to suggest alternative implementations.
