### ISSUE TITLE
Register route not working

### ISSUE THREAD

**Issue by PhilippeCorreges** [DaftMonk/generator-angular-fullstack#1091]
Hello,
I followed http://docs.stormpath.com/angularjs/guide/register.html entirely, Stormpath is well configured but no user is created and I am not redirected to the index.html page.
Any idea ??

Thanks

Philippe

**Comment by kingcody** [comment]
I'm not sure what Stormpath is, but if you'd like to share what it is your trying to setup and what errors you might be having it would be a lot easier for someone to help you. Also you might want to check with the Stormpath forum/community, you would probably have better luck finding someone with knowledge about the integration there.

**Comment by kingcody** [comment]
@PhilippeCorreges I'm going to close this due to inactivity.
