### ISSUE TITLE
Api token Auth

### ISSUE THREAD

**Issue by IgorDePaula** [DaftMonk/generator-angular-fullstack#1099]
Please, implement improvement of token auth on api, for access of mobile apps.

**Comment by kingcody** [comment]
@IgorDePaula could you be a little more specific, what kind of improvements?

**Comment by IgorDePaula** [comment]
I true, it's a new feature, free access to data from mobile app for a auth token api (or other method). I created an admin panel by this generator and I want sharing data from this database on mobile app.

**Comment by kingcody** [comment]
There is already that ability. Simply append `?access_token=XXXXXXXXX` to an api request. If the token is valid then the request will be authenticated.

**Comment by IgorDePaula** [comment]
I do not understand, where I authenticate this token on code (server)?

2015-07-25 10:23 GMT-03:00 Cody Mize <notifications@github.com>:

**Comment by kingcody** [comment]
`POST` to `/auth/local` sending `email` and `password` and you should receive:
```javascript
{
  "token": "XXXXXXXXXXXXXXXXXX"
}

**Comment by IgorDePaula** [comment]
All time that open the add I post email and password to panel app and I
receive the token and next requests I send the token to panel app?

2015-07-26 1:51 GMT-03:00 Cody Mize <notifications@github.com>:

**Comment by kingcody** [comment]
I'm not sure exactly what you mean, but if you make the `POST` call to `/auth/local` and receive an access token (which is good for 5 hours) you can then include it as a header (`authorization: Bearer XXXXXXXXX`) or a query parameter (`?access_token=XXXXXXXXX`) on subsequent api calls and they will be authorized as the user for which the token was authorized for. I hope that clears things up for you.

**Comment by IgorDePaula** [comment]
It was what I imagined. Thank you for your help

2015-07-26 3:43 GMT-03:00 Cody Mize <notifications@github.com>:

**Comment by IgorDePaula** [comment]
I'll test.

2015-07-26 8:48 GMT-03:00 principe.borodin@gmail.com <
principe.borodin@gmail.com>:

**Comment by kingcody** [comment]
@IgorDePaula does that solve your issue?

**Comment by IgorDePaula** [comment]
Yes, yo can close this issue, please.

2015-07-26 22:17 GMT-03:00 Cody Mize <notifications@github.com>:

**Comment by IgorDePaula** [comment]
A last detail, for this work, it's necessary enable cors, the default is cors disabled.

**Comment by kingcody** [comment]
If you are disabling CORS, you should look into implementing a CSRF mitigation strategy.

**Comment by IgorDePaula** [comment]
No, you dont understand, for send post data to receive the token, like you
talk to me, I need enable the CORS, by default the CORS is disabled on app.

2015-07-27 18:22 GMT-03:00 Cody Mize <notifications@github.com>:

**Comment by IgorDePaula** [comment]
It works by a long time, but now not work more. I received 401 error with the right token.

**Comment by IgorDePaula** [comment]
Oh men, I'm sorry, my carelessness.
