### ISSUE TITLE
grunt serve and grunt serve:dist only listen on 127.0.0.1

### ISSUE THREAD

**Issue by chrkorn** [DaftMonk/generator-angular-fullstack#1100]
I have installed an angular fullstack app on a headless server, following the tutorial.

When executing grunt serve grunt serve:dist, it is not possible to access the app from outside the headless server, as expressjs will only be listening on 127.0.0.1 (as output from netstat -tulpen clearly shows).

I suggest adding a line explaining how to change that to the documentation. It would have saved us quite some time.

**Comment by kingcody** [comment]
Check [`server/config/environment/index.js`](https://github.com/DaftMonk/generator-angular-fullstack/commit/2cd1c24d2224e46fa68f8da834e86ac3ed80de8e) on the master branch.

**Comment by kingcody** [comment]
closed by #1080
