### ISSUE TITLE
Question: Where does cookie get received from the front end in facebook authentication

### ISSUE THREAD

**Issue by christiansakai** [DaftMonk/generator-angular-fullstack#1108]
Hello,

When using facebook authentication
```
function setTokenCookie(req, res) {
  if (!req.user) return res.json(404, {
    message: 'Something went wrong, please try again.'
  });
  var token = signToken(req.user._id, config.secrets.session, config.tokenExpiration.session);
  res.cookie('token', JSON.stringify(token));
  res.redirect('/');
}
```

I would like to know, this line `res.cookie('token')`, where does that get retrieved on the front end?

**Comment by kingcody** [comment]
Here: https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/client/components/auth%28auth%29/auth.service%28js%29.js#L6-L8
