### ISSUE TITLE
No error is thrown when bower is not installed

### ISSUE THREAD

**Issue by JohanLorenzo** [DaftMonk/generator-angular-fullstack#1110]
Thank you for this awesome generator!

I forgot bower was not installed on the machine I was, I ran the generator and everything looked fine. 
Then I ran `grunt serve`, and I got:
```
Running "concurrent:server" (concurrent) task
    Warning: Error: File to import not found or unreadable: bootstrap-sass-official/vendor/assets/stylesheets/bootstrap.
```
This message does not explain why there is no bootstrap installed.

Then, I think we should check if bower is correctly installed and if not, abort the installation process. What do you all think?

**Comment by Awk34** [comment]
In the canary branch we have a [README.md](https://github.com/DaftMonk/generator-angular-fullstack/blob/canary/app/templates/README.md) file that gets generated along with the project, including instructions to use Bower.
