### ISSUE TITLE
`warning: CRLF will be replaced by LF` in many files

### ISSUE THREAD

**Issue by JohanLorenzo** [DaftMonk/generator-angular-fullstack#1111]
# Steps to reproduce
1. Run the generator
1. `git init`
1. `git add .`

# Results
Your console gets full of lines like:
```
warning: CRLF will be replaced by LF in .bowerrc.
The file will have its original line endings in your working directory.
```

# Environment
Linux. Yeoman 1.4.7. Angular Fullstack v2.1.0 (installed 10 minutes ago)

**Comment by verrol** [comment]
Add the line:
safecrlf=false
to .git/config under '[core]'.

**Comment by JohanLorenzo** [comment]
I don't remember using this workaround 6 months ago. Why is it necessary today, @verrol ?

**Comment by verrol** [comment]
@JohanLorenzo I don't know the answer to that. May be a contributor for the client library checked in some code with windows line ending.

**Comment by Awk34** [comment]
Yeah, this is due to a config change from line endings set to auto, to forcing LF. We just need to make sure all the files have LF endings to be consistent
