### ISSUE TITLE
Why maintain angular-scenario in bower.json?

### ISSUE THREAD

**Issue by ligeek** [DaftMonk/generator-angular-fullstack#1118]
After I took a look in `bower.json`, I researched angular-scenario because what it is using for.
In course of the researching, I had figured out this have been deprecated and turned into **maintenance mode** . 

here is links:
https://docs.angularjs.org/guide/e2e-testing
https://github.com/angular/bower-angular-scenario#packaged-angular-scenario

They note if you plan to create new project, use [Protractor](https://github.com/angular/protractor).

But, master and canary branch in this generator keep maintaining angular-scenario in `bower.json`.
Is there what I couldn't catch?

**Comment by kingcody** [comment]
I believe you are correct and that it should be removed. PR?

**Comment by ligeek** [comment]
Yes, I will :)

**Comment by kingcody** [comment]
Thank you @ligeek
