### ISSUE TITLE
Dokku digitalocean deploying mongo don't connect

### ISSUE THREAD

**Issue by MatthieuHarbich** [DaftMonk/generator-angular-fullstack#1120]
Hey!
I'm desesperatly trying to deploy an angular-fullstack to digital ocean with dokku...

Express server listening on 5000, in production mode
       events.js:85
             throw er; // Unhandled 'error' event
                   ^
       Error: failed to connect to [127.0.0.1:27017]

I get this when I try to push, I can't connect to the database. Does anyone know this issue? I really don't what to do, and it's important to me to get it online before tomorrow... 

If someone can help me, please!

Mongo is running on server side.

**Comment by Awk34** [comment]
Do you have mongo running on the same instance as your generator-angular-fullstack server?

**Comment by kingcody** [comment]
@MatthieuHarbich were you able to resolve this issue?

**Comment by MatthieuHarbich** [comment]
Hey, no but to be honest I stopped my researches for a moment, I will retry in two weeks. 
@kingcody so no I still don't. I think the problem is in the conf variables in dokku, on heroku you need to pass variables, I didn't try yet.
@Awk34 Mongo were running on server side on my digitalocean server, on the right port.

If you resolve the issue, please share it! Tank you for your answers

**Comment by Awk34** [comment]
Closed due to inactivity.
