### ISSUE TITLE
grunt serve:dist multiple get errors 

### ISSUE THREAD

**Issue by oaaraya** [DaftMonk/generator-angular-fullstack#1132]
When I test using grunt serve:dist I get multiple 404 errors, it seems to be everything between the inject.js and .css 

GET /app/main/main.css 404 15ms
GET /app/project/project.css 404 7ms
GET /app/project/projectdetail.css 404 2ms
GET /components/modal/modal.css 404 2ms
GET /app/login/login.js 404 32ms
GET /app/main/main.js 404 33ms
GET /app/project/project.controller.js 404 33ms
GET /app/project/project.js 404 5ms
GET /app/project/projectdetail.controller.js 404 10ms
GET /app/project/projectdetailedit.controller.js 404 9ms
GET /app/project/projectnew.controller.js 404 5ms
GET /components/modal/modal.service.js 404 5ms
GET /components/navbar/navbar.controller.js 404 7ms
GET /api/users/current 401 2ms - 42b
GET /api/users/current 401 1ms - 42b
GET /app/main/main.css 404 5ms
GET /app/project/project.css 404 6ms
GET /app/project/projectdetail.css 404 6ms
GET /components/modal/modal.css 404 5ms
GET /app/main/main.css 404 3ms
GET /app/project/project.css 404 3ms
GET /app/project/projectdetail.css 404 2ms
GET /components/modal/modal.css 404 1ms
GET /app/login/login.js 404 8ms
GET /app/main/main.js 404 13ms
GET /app/project/project.controller.js 404 7ms
GET /app/project/project.js 404 7ms
GET /app/project/projectdetail.controller.js 404 6ms
GET /app/project/projectdetailedit.controller.js 404 6ms
GET /app/project/projectnew.controller.js 404 3ms
GET /components/modal/modal.service.js 404 5ms
GET /components/navbar/navbar.controller.js 404 2ms
GET /api/users/current 401 1ms - 42b
GET /api/users/current 401 1ms - 42b

Same thing when I deploy to Heroku, I've already ran grunt build.

**Comment by Awk34** [comment]
You most likely aren't using proper line endings. Try using `dos2unix` or something similar to convert all line endings to `lf`.

**Comment by oaaraya** [comment]
Thank you @Awk34 that got rid of it all the errors. I still have some formatting differences that make me believe there is some css not being added, I'm using ngTable and the sorting disappears when I grunt serve:dist and also the inline labels have no spaces. When I just grunt serve, everything works fine. Again, thank you for your quick answer

**Comment by Awk34** [comment]
How are you including the CSS files? They're probably not getting included in the `usemin` task for the build step.

**Comment by oaaraya** [comment]
@Awk34 all the css are in the build on the index.html. What I find strange is that only certain things don't work, line the sorting on ngtables, everything else works, like paging, filtering, etc.

      
      <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css" />
      <link rel="stylesheet" href="bower_components/font-awesome/css/font-awesome.css" />
      <link rel="stylesheet" href="bower_components/ng-table/dist/ng-table.min.css" />
      <link rel="stylesheet" href="bower_components/angular-loading-bar/build/loading-bar.css" />
      
    
    
    <link rel="stylesheet" href="app/app.css">
      
      <link rel="stylesheet" href="app/app.css">
      <link rel="stylesheet" href="app/main/main.css">
      <link rel="stylesheet" href="app/project/project.css">
      <link rel="stylesheet" href="app/project/projectdetail.css">
      <link rel="stylesheet" href="app/project/projectdetailedit.css">
      <link rel="stylesheet" href="app/project/projectnew.css">
      <link rel="stylesheet" href="components/modal/modal.css">

**Comment by oaaraya** [comment]
@Awk34 I found out what is was, there is a weird overlay of data-title tag between bootstrap and ngtables that usemin apparently overwrites. If you create the headers manually the issue is resolved.

**Comment by srikanthenjamoori** [comment]
@Awk34 , worked like charm, thanks for solution.
