### ISSUE TITLE
Cannot see any cdn script in the dist/public/index.html file.

### ISSUE THREAD

**Issue by chenweiyj** [DaftMonk/generator-angular-fullstack#1138]
I run `grunt` and it tells me the following output.

```
Running "cdnify:dist" (cdnify) task
Going through dist/public/index.html to update script refs
✔ bower_components/angular/angular.js changed to //ajax.googleapis.com/ajax/libs/angularjs/1.4.0-beta.2/angular.min.js
✔ bower_components/angular-cookies/angular-cookies.js changed to //ajax.googleapis.com/ajax/libs/angularjs/1.4.0-beta.2/angular-cookies.min.js
✔ bower_components/angular-resource/angular-resource.js changed to //ajax.googleapis.com/ajax/libs/angularjs/1.4.0-beta.2/angular-resource.min.js
✔ bower_components/angular-sanitize/angular-sanitize.js changed to //ajax.googleapis.com/ajax/libs/angularjs/1.4.0-beta.2/angular-sanitize.min.js
```

However I cannot find any cdn script shown in the `dist/public/index.html`.

**Comment by kingcody** [comment]
See:
yeoman/generator-angular#266
btford/grunt-google-cdn#47

**Comment by Awk34** [comment]
Closed due to inactivity.

**Comment by david-mohr** [comment]
I came across this when working on a `cdnify` task for gulp.  Do the maintainers have a stance on how this should work?

My personal opinion is that as a user, if you're calling `cdnify`, then you don't want any of the CDN links to be bundled into the `vendor.js` file.  The solution is to move/hoist and CDN links above the `<!-- build` section.

For Grunt, the option is https://github.com/mjetek/grunt-cdn-nobuild.

And I've ported this to gulp: https://github.com/david-mohr/gulp-cdn-hoist

Also, during my testing I noticed something that might prevent this from working as expected: `jquery` doesn't appear in `bower.json`. Consequently it won't be caught by `cdnify` but `angular` will, meaning that `angular` will appear before `jquery` in `index.html` and therefore angular may not behave as expected.

**Comment by jkiimm** [comment]
I'm running into this problem too. So, I've found that grunt-usemin owner commented to use block replacement for ignoring CDN resources [in their issue](https://github.com/yeoman/grunt-usemin/issues/330).

Would that be alternative option to use filter with regex that figures out whether is CDN resource or not in [blockReplacement](https://github.com/yeoman/grunt-usemin#blockreplacements)?
