### ISSUE TITLE
Socket usage template suggestion

### ISSUE THREAD

**Issue by smirciat** [DaftMonk/generator-angular-fullstack#1140]
In the interest of helping novices such as myself use and understand this helpful and powerful generator, it might be helpful to explicitly show the use of a callback in the template example of the use of socket.syncUpdates within client/app/main/main.controller.js.  This way it would be obvious when learning to use socket that a callback option is included and very useful when syncing the updates.
```
    $http.get('/api/things').success(function(awesomeThings) {
      $scope.awesomeThings = awesomeThings;<% if(filters.socketio) { %>
      socket.syncUpdates('thing', $scope.awesomeThings, function(event, item, array){
        //socket update callback function
      });<% } %>
    });
```

**Comment by kingcody** [comment]
That would be nice, there are several areas of the generator/project that could use some in-depth docs. Is that something you would like contribute?

**Comment by smirciat** [comment]
I would be interested in contributing what I can from the perspective of someone learning the MEAN stack through this generator template.  I have forked the repo, and can gererate pull requests if appropriate.  Is there any specific protocol to follow with this?  Any level or format of documentation that would be preferred?  I am interested in making a contribution but not wasting anyone's valuable time.

**Comment by kingcody** [comment]
Are you familiar/comfortable with JSDoc commenting?

**Comment by smirciat** [comment]
I'd have to read up on that...

**Comment by kingcody** [comment]
Well its a great way to document since it stays with the code and there are a plethora of tools that can turn that into stand alone (md|html|text) docs. If you get some time to look it over that would be great, if not, no worries (:

**Comment by smirciat** [comment]
It looks straightforward at first glance.  Any basic guidance how I should proceed to be helpful to the project?

**Comment by kingcody** [comment]
@smirciat perhaps you could checkout [**`auth.service.js`**](https://github.com/DaftMonk/generator-angular-fullstack/blob/canary/app/templates/client/components/auth(auth)/auth.service(js).js) for examples of jsdoc commenting used in this project.

**Comment by Awk34** [comment]
Closed due to inactivity.
