### ISSUE TITLE
Angular bower.json semver issue

### ISSUE THREAD

**Issue by ruyadorno** [DaftMonk/generator-angular-fullstack#1141]
I see the `bower.json` template file uses `>=1.2.*` as the semver version resolution for the generated project.

I'm pretty sure this is going to break once a 2.x tag is available on their [distribution repo](https://github.com/angular/bower-angular) due to the incompatible nature of Angular 2.0.

A simple solution is to use `^1.*.*` instead.

**Comment by Awk34** [comment]
See https://github.com/DaftMonk/generator-angular-fullstack/blob/canary/app/templates/_bower.json

**Comment by ruyadorno** [comment]
:+1: I see, it will eventually make it to master in time :blush: 

thanks!
