### ISSUE TITLE
Some SCSS color functions not working

### ISSUE THREAD

**Issue by BlindPrimate** [DaftMonk/generator-angular-fullstack#1145]
I'm new to fullstack development and your fantastic constructor, so this may be a known issue, but it seems like certain SCSS color functions are not working, specifically the tint & shade functions.  It seems like many of the other color functions work just fine.  I've looked at the known issues and done a number of google searches and haven't found any similar issues.

**Comment by Awk34** [comment]
I haven't been able to reproduce

**Comment by BlindPrimate** [comment]
After an hour of tinkering, I discovered that the issue was with my local environment.  Compass was not installed properly, and grunt wasn't loading compass as expected.  After getting it up and running, all the color functions are now working.  Thanks for your time.
