### ISSUE TITLE
Is it possible to use it standalone in a Laravel project?

### ISSUE THREAD

**Issue by aligajani** [DaftMonk/generator-angular-fullstack#1148]
I tried doing `yo angular-generator:service ServiceName` and it asked me for my path.

I supplied it `public/js/app/services/` and it didn't do anything. My ServiceName wasn't generated.

**Comment by aligajani** [comment]
Yes we can. Just have this in the root of your project and save it as `.yo-rc.json`.

{
  "generator-angular-fullstack": {
    "insertRoutes": true,
    "registerRoutesFile": "server/routes.js",
    "routesNeedle": "// Insert routes below",
    "routesBase": "/api/",
    "pluralizeRoutes": true,
    "insertSockets": true,
    "registerSocketsFile": "server/config/socketio.js",
    "socketsNeedle": "// Insert sockets below",
    "filters": {
      "babel": true,
      "js": true,
      "html": true,
      "sass": true,
      "uirouter": true,
      "bootstrap": true,
      "uibootstrap": true,
      "socketio": true,
      "mongoose": true,
      "auth": true
    }
  },
  "generator-ng-component": {
    "routeDirectory": "client/app/",
    "directiveDirectory": "client/app/",
    "filterDirectory": "client/app/",
    "serviceDirectory": "client/app/",
    "basePath": "client",
    "moduleName": "",
    "filters": [
      "uirouter"
    ],
    "extensions": [
      "babel",
      "js",
      "html",
      "scss"
    ],
    "directiveSimpleTemplates": "",
    "directiveComplexTemplates": "",
    "filterTemplates": "",
    "serviceTemplates": "",
    "factoryTemplates": "",
    "controllerTemplates": "",
    "decoratorTemplates": "",
    "providerTemplates": "",
    "routeTemplates": ""
  }
}

**Comment by kingcody** [comment]
@aligajani even easier, you can use [`generator-ng-componet`](https://github.com/daftmonk/generator-ng-component) by its self.
