### ISSUE TITLE
Forces to use mongoose, if we need to use socket.io

### ISSUE THREAD

**Issue by sojharo** [DaftMonk/generator-angular-fullstack#1149]
I wanted to use socket.io in my project on server side with no database connection. The generator did not give option to generate only socket.io application. I had to select the mongoose before I could select socket.io during generation.

**Comment by Awk34** [comment]
Did you have a question?

**Comment by sojharo** [comment]
I want only socket.io in my generated application. But the generator
doesn't show me socket.io option if I don't select mongoose first. I should
be able to do select socket.io during first time generating of app
regardless of I select mongoose or not.

**Comment by Awk34** [comment]
The Socket.io code we have depends on Mongoose, as its sole purpose is to sync updates to the MongoDB database. If you'd like to integrate Socket.io for other reasons, you'll have to do it manually. You can look at the server file [here](https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/server/config/socketio(socketio).js) and the Socket.io documentation at http://socket.io/docs/.
