### ISSUE TITLE
Canary endpoint subgen incompatible with master.

### ISSUE THREAD

**Issue by kingcody** [DaftMonk/generator-angular-fullstack#1160]
Currently when generating an endpoint with the `canary` branch, a project that was generated with the `master` branch will not receive the mongoose models template that should be included. This is due to the `mongooseModels` filter not being set for projects generated with `<=2.1.1`.

**Comment by kingcody** [comment]
Another point to make is that the `master` branch code lacks `mongoose-bird` support.

**Comment by Awk34** [comment]
You bring up a very good point. Trying to run subgenerators in a project that was generated with a version too far behind won't work. I'm not really sure what the best solution to this is.

**Comment by Awk34** [comment]
The only thing I can think of is to release as 3.0.0 and note the breaking changes.

**Comment by Awk34** [comment]
@kingcody and I have decided on a major version release
