### ISSUE TITLE
Canary: replace <%= does() %>

### ISSUE THREAD

**Issue by kingcody** [DaftMonk/generator-angular-fullstack#1163]
After a long night of thought and experimentation, I'd like to propose replacing the templating syntax:
```javascript
<%= does("ASSERTION_SUBJECT") %>.be.at.least(1);
```
With:
```javascript
<%= expect() %>ASSERTION_SUBJECT<%= to() %>.be.at.least(1);
```

Pros:
* Fixes problems with escaping templates and line breaks
* Will be simpler to implement and maintain
* Templates read better than broken english `does`
* No need to quote the assertion subject

Cons:
* Adds slightly more syntax to the templates than `does`

**Comment by Awk34** [comment]
Hmmm, I'm not sure how I feel about this. While it does make the Yeoman templates make more grammatical sense, I like the old syntax better. We could change the language of it to make more sense (especially the `foo` variable to something like `subject`), but I like the single function to insert the proper syntax better. I think it's harder to look at the second example you gave.

**Comment by kingcody** [comment]
@Awk34 have thought about any solutions for this issue? Particularly the issue of the `ASSERTION_SUBJECT` containing ejs strings and/or new lines.

**Comment by Awk34** [comment]
I've thought about it some more, and it seems like your new solution makes more sense for our specifics.
