### ISSUE TITLE
Chromedriver is not executable in Linux

### ISSUE THREAD

**Issue by Forestdev** [DaftMonk/generator-angular-fullstack#1175]
There seems to be an issues with the `chromedriver` on Linux. As it is a windows executable, Linux won't run it.

**Comment by kingcody** [comment]
That's odd, when I run `npm run update-webdriver` it downloads the Linux version.

**Comment by Forestdev** [comment]
I found out that it has downloaded the Linux version, as intended. However, the problem was the way the harddrives were being mounted. As the harddrive was mounted after the OS fired up, thus executable files did not have permission to fire.

So the solution was to set in the settings so that the additional harddrives would mount on launch, automatically. This has solved the issue.

Thank you.
