### ISSUE TITLE
Bug (and fix): undefined email and displayName when using the PassportJS Facebook Strategy

### ISSUE THREAD

**Issue by nicolaslair** [DaftMonk/generator-angular-fullstack#1186]
When generating a default app, there is a small bug with the PassportJS Facebook Strategy: the displayName and email fields are not accessible by default as their values is undefined even though the scope seems to be correct in server/auth/facebook/index.js: scope: ['email', 'user_about_me']

The way to fix it is to also include the profileFields in server/auth/facebook/passport.js:

passport.use(new FacebookStrategy({
      clientID: config.facebook.clientID,
      clientSecret: config.facebook.clientSecret,
      callbackURL: config.facebook.callbackURL,
      profileFields: ['id', 'displayName', 'email']
    },

I guess this bug has been introduced with the release of the Facebook API v2.4.

Hope it helps!

**Comment by Awk34** [comment]
https://github.com/DaftMonk/generator-angular-fullstack/blob/canary/app/templates/server/auth(auth)/facebook(facebookAuth)/passport.js#L9

Yep, it's because Facebook changed their API. Fix is in canary branch.
