### ISSUE TITLE
Question: how to update generator-angular-fullstack?

### ISSUE THREAD

**Issue by bobby77** [DaftMonk/generator-angular-fullstack#1188]
Hello,
I use generator-angular-fullstack and I would have a few questions. Sorry if it is not the right place for this. I can remove this post if needed.

I use a version downloaded in Feb2015 for my app. I see v3.0 coming, and I would like to know how I can update to a new version of the generator. In terms of practices, are there any files that I should not modify in case I would like to be able to make an update? 

Also, I did not check coffeescript when I loaded it. Should I start my project from scratch to include it, or can I modify the set-up of generator-angular-fullstack?

Thanks a lot

**Comment by kingcody** [comment]
@bobby77 great questions. The main reason `generator-angular-fullstack` is having a major release is there are numerous breaking changes from `2.x` to `3.x`. So basically you can continue using the `2.x` branch with your current project, or generate a new project with the upcoming `3.0.0` release.

**Comment by bobby77** [comment]
OK thanks a lot for your answer. I will then wait for v3 before switching my code to coffeescript.
Do you have an approximate idea when it will be available? I see it is quite advanced.
Thanks.

**Comment by Awk34** [comment]
I'm hoping to get it out within the next month. We'll be releasing a few more Release Candidates before then. With Yeoman generators, there's no real way to upgrade your old code to code from the newer generator, other than generating a new project with the new generator, and manually copying your code over. That's just the way it works. :/ There's no way to account for what kinds of things you changed in your code to upgrade to the new code.
