### ISSUE TITLE
Connect to mongolab DB in Openshift

### ISSUE THREAD

**Issue by JahlomP** [DaftMonk/generator-angular-fullstack#1199]
How do I connect to a database in Mongolab from an angular-fullstack app on openshift?

I set an environment variable for MONGOLAB_URI but did not work.

**Comment by JahlomP** [comment]
@DaftMonk can you help me out here?

**Comment by Awk34** [comment]
If you want to use MongoLab in development, edit this: [development.js](https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/server/config/environment/development.js#L8). If you are in the production environment, setting `MONGOLAB_URI` will work.
