### ISSUE TITLE
$http legacy promise has been deprecated

### ISSUE THREAD

**Issue by ligeek** [DaftMonk/generator-angular-fullstack#1200]
[$http Deprecation Notice](https://docs.angularjs.org/api/ng/service/$http#deprecation-notice) tell us `.success` and `.error` method which we have been using have become legacies. [This commit](https://github.com/angular/angular.js/commit/a8f7e9cfde82ed7eaba3a868d8acafdf57f2d76f) is related with this issue. Therefore, I think we have to follow that.

If you take a look [$http General Usage](https://docs.angularjs.org/api/ng/service/$http#general-usage), then get to know response object has changed a little. While `.success` and `.error` callback was returning just response body by default, `.then` is returning object with some useful properties. A callback response that we have got from `.success` and `.error` is **`data` property** that a callback response have in `.then`.

```javascript
// in success
$http.get('/api/things').success(function(awesomeThings) {
  $scope.awesomeThings = awesomeThings;
});

// in then
$http.get('/api/things').then(function(res) {
  $scope.awesomeThings = res.data;
});
```

**Comment by kingcody** [comment]
Sounds great, PR?

**Comment by ligeek** [comment]
@kingcody yep, I will.
