### ISSUE TITLE
Some files has too long paths

### ISSUE THREAD

**Issue by MyPCIsBetter** [DaftMonk/generator-angular-fullstack#1203]
I'm using a server based on Windows software (Microsoft Azure). It seems like some files are too long and that causes problems with building my application. I described my problem precisely [here](http://stackoverflow.com/questions/32170367/building-web-app-on-azure-npm-err-windows-nt-6-2-9200/32170904).

For example there is a problem with this path:
> D:\home\site\wwwroot\node_modules\socketio-jwt\node_modules\jsonwebtoken\node_modules\jws\node_modules\base64url\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_modules\is-finite\node_modules\number-is-nan\package.json.5f81d88f6c51ba4596881f5ad60cfe9c

What can I do to fix that? Do any of you have similar problems?

**Comment by Awk34** [comment]
I develop on a Windows machine, but all of my servers are unix systems. The only problems I've had with the long paths is deleting them, but I seem to not have that issue on Windows 10.

**Comment by Awk34** [comment]
Were you able to fix your issue? I'm going to close this, as this is an issue with NPM and Windows, not our project.
