### ISSUE TITLE
Question: Promises

### ISSUE THREAD

**Issue by donniev** [DaftMonk/generator-angular-fullstack#1213]
Is there any work being done on creating a promise based version of the server code using bluebird?
I have successfully converted the sample app but have not touched the code that actually generates the sample.

**Comment by DanMMX** [comment]
Sequelize uses Bluebird, what are you intending to do or wanted to be done with Bluebird? Don't think there's a specific need right now to use it.

**Comment by donniev** [comment]
I just prefer to use promised based code to interact with the database layer or file system, or external processes.
Since this is abstracted away  by the generator it probably isn’t terribly important in this case so question was more
out of curiosity than an actual need.

**Comment by Awk34** [comment]
We are using promises with the database interactions, but if there's another location that you feel could benefit from using promises, feel free to open a PR.
