### ISSUE TITLE
"heroku addons:add mongohq", add is deprecated

### ISSUE THREAD

**Issue by fcagalj** [DaftMonk/generator-angular-fullstack#1222]
It should be used "heroku addons:create mongohq" instead.

I also suggest using MongoLab as default DB because it offer free plan. MongoHQ doesnt offer free plan any more...

**Comment by Awk34** [comment]
I can't find where we reference the deprecated command. [In the README](https://github.com/DaftMonk/generator-angular-fullstack#heroku), the command that we reference is `heroku addons:create mongolab`.

**Comment by fcagalj** [comment]
It is inside heroku/index.js generator. It is not task but instructions to use add:mongohq instead of create:mongolab. I created PR.

https://github.com/DaftMonk/generator-angular-fullstack/pull/1226

**Comment by Awk34** [comment]
Aha! I was just looking in the doc files, not it the JS. Thanks for the PR!

**Comment by kingcody** [comment]
Closed by #1226
