### ISSUE TITLE
UnauthorizedError: jwt expired

### ISSUE THREAD

**Issue by reggirepret** [DaftMonk/generator-angular-fullstack#1223]
The method in api/user/me is having problems, as soon as I correctly log in, the session is ended and I am forced to log in again.

The log error is then: UnauthorizedError: jwt expired followed by 401.

I am wondering what this is down to, I have tried the following:

update the jsonwebtokens5 to that.

I am lost, as I do not have much experience with authentication and cookies and the like. (the tests are failing on Herko server as well as locally)

**Comment by Awk34** [comment]
What version of the generator are you using. Is it a fresh install? The `401` you're seeing is shown whenever you try to access a route that requires authorization, while you are not logged in.

**Comment by reggirepret** [comment]
I think I am using quite an old version of the generator, the problem has only recently shown up. I think I am going to scaffold the app from scratch again and see if the problem persists.

**Comment by Awk34** [comment]
Cool, I look forward to seeing if the problem is gone

**Comment by Awk34** [comment]
Closed due to inactivity
