### ISSUE TITLE
How to use environment variables on the client side

### ISSUE THREAD

**Issue by louisscruz** [DaftMonk/generator-angular-fullstack#1227]
I have some API keys that are currently stored in controllers and factories. For instance:

    angular.module('exampleApp')
      .factory('flickr', ['$http',
        function($http) {
          var apiKey = 'xxxxxxxxxxxxxxxxxxxxxxxxx';
          ....
        }
    ]);

Is there a way I can store an API key like this in my local.env.js? Can someone please give me a specific way of doing so?

For deployment, I'd like to set these variables on my server with:

    export FLICKR_API_KEY='xxxxxxxxxxxxxxxxxxxxxxxxx'

Please forgive my ignorance on this. I come from a rails background, so setting server side variables isn't an issue for me. The problem is client side variables. I've read every issue related to environment variables, local.env, etc., but I'm struggling to get a good understanding of this. If someone informs me how this works, I'll be happy to add some info to the docs.

**Comment by kingcody** [comment]
So you are wanting to expose a server side environment variable to your client code? How dynamic is the variable? Will it stay the same after the project has been compiled or will it differ depending on the deployment?

**Comment by louisscruz** [comment]
@kingcody Yes, I want to expose a server side environment variable to my client code. The variable is not dynamic, and it will remain the same after compilation (no difference for different compilations). I know that this variable will inevitably be known to the client, but I'd prefer not to check it into version control. Would something like [grunt-replace](https://github.com/outaTiME/grunt-replace) be my best bet?

**Comment by Awk34** [comment]
If you want to store it client-side without being in Git, you could commit a js file that exposes nothing, and is loaded in index.html. Then, once that file is in Git, add it to your `.gitignore`, and add whatever keys you'd like to it. Or just use `grunt-replace`

**Comment by remicastaing** [comment]
@louisscruz , you could also inject your API key at build time. Take a look at this old PR: https://github.com/DaftMonk/generator-angular-fullstack/pull/757.

**Comment by louisscruz** [comment]
Thank you all for your guidance!
