### ISSUE TITLE
yo angular-fullstack:openshift takes forever.

### ISSUE THREAD

**Issue by srrvnn** [DaftMonk/generator-angular-fullstack#1231]
after running rhc setup, i am running the openshift command. the command stalls at the 'Creating appilcation ...' step, and it has been more than 30 mins, with no feedback at all. 

what could be wrong?

**Comment by srrvnn** [comment]
if it helps, this is the first time i am running this command, and the 
'Checking for an existing OpenShift hosting environment...' 

command failed with the warning : 
`warning: Insecure world writable dir /usr in PATH, mode 040777`

**Comment by Awk34** [comment]
Is that an issue with your setup for OpenShift?

**Comment by srrvnn** [comment]
seems to be an OpenShift issue. running `rhc create app` takes forever as well.
