### ISSUE TITLE
Error import fs from 'fs';

### ISSUE THREAD

**Issue by harissarwar** [DaftMonk/generator-angular-fullstack#1244]
I have just installed this generator but i am unable to create any app.
I am getting following error

D:\dev\git\New folder>yo angular-fullstack
C:\Users\Haris\AppData\Roaming\npm\node_modules\generator-angular-fullstack\app\generator.js:3
import fs from 'fs';
^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Haris\AppData\Roaming\npm\node_modules\generator-angular-fullstack\node_modules\babel-c
ore\lib\api\register\node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Haris\AppData\Roaming\npm\node_modules\generator-angular-fullstack\app\index.js:7:28)
    at Module._compile (module.js:460:26)

D:\dev\git\New folder>

**Comment by kingcody** [comment]
What version of node are you using?

**Comment by DylanRothko** [comment]
I'm also having this issue ( new to node ).  I'm running v0.12.4
thanks in advance for any clues man.

**Comment by kingcody** [comment]
TBH I'm not sure why this would be happening, we are loading the `babel-core/register` hook which should transpile the required modules on the fly.

@harissarwar, I noticed that you are running this on windows; @DylanRothko are you also using windows?

**Comment by DylanRothko** [comment]
@kingcody I am not, Im pasting some terminal output below.

/usr/local/lib/node_modules/generator-angular-fullstack/app/generator.js:3
import fs from 'fs';
^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/generator-angular-fullstack/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-angular-fullstack/app/index.js:7:28)
    at Module._compile (module.js:460:26)

**Comment by kingcody** [comment]
@DylanRothko could you try something for me? In `/usr/local/lib/node_modules/generator-angular-fullstack/app/index.js` on line 7, could you change that to be:
```javascript
exports = module.exports = require('./generator.js');
```

I'm just curious if that has any affect...

**Comment by DylanRothko** [comment]
@kingcody no luck, ill paste my terminal output below but the only noticeable change was that module.js was mentioned as module..js

Should I have run any commands after updating the file in /usr/local?

/usr/local/lib/node_modules/generator-angular-fullstack/app/generator.js:3
import fs from 'fs';
^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/generator-angular-fullstack/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-angular-fullstack/app/index.js:7:28)
    at Module._compile (module.js:460:26)

**Comment by kingcody** [comment]
@DylanRothko I honestly didn't think that it would matter, just a shot in the dark. I'm still unsure what would be causing this issue.

**Comment by harissarwar** [comment]
I am using windows with latest version of nodejs.

**Comment by harissarwar** [comment]
I am using Nodejs 12.7 64bit version on window 8.1

**Comment by kingcody** [comment]
@DylanRothko in `/usr/local/lib/node_modules/generator-angular-fullstack`, @harissarwar in `C:\Users\Haris\AppData\Roaming\npm\node_modules\generator-angular-fullstack`; run `npm ls babel-core`. I just want to make sure that you both have the module installed and up to date.

**Comment by harissarwar** [comment]
Here is the output

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Haris>cd
AppData\Roaming\npm\node_modules\generator-angular-fullstack

C:\Users\Haris\AppData\Roaming\npm\node_modules\generator-angular-fullstack>npm
ls babel-core
generator-angular-fullstack@3.0.0-rc6
C:\Users\Haris\AppData\Roaming\npm\node_mo
dules\generator-angular-fullstack
└── babel-core@5.8.23


C:\Users\Haris\AppData\Roaming\npm\node_modules\generator-angular-fullstack>

On Fri, Sep 4, 2015 at 12:29 AM, Cody Mize <notifications@github.com> wrote:

> @DylanRothko <https://github.com/DylanRothko> in
> /usr/local/lib/node_modules/generator-angular-fullstack, @harissarwar
> <https://github.com/harissarwar> in
> C:\Users\Haris\AppData\Roaming\npm\node_modules\generator-angular-fullstack;
> run npm ls babel-core. I just want to make sure that you both have the
> module installed and up to date.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DaftMonk/generator-angular-fullstack/issues/1244#issuecomment-137549398>
> .
>



-- 
Haris Sarwar
Product Manager,
Zigron <http://www.zigron.com/>

**Comment by harissarwar** [comment]
I am using NodeJS Version 12.4 not 12.7. I just verified it now.


On Fri, Sep 4, 2015 at 12:35 AM, Haris Sarwar <haris.sarwar@gmail.com>
wrote:

> Here is the output
>
> Microsoft Windows [Version 6.3.9600]
> (c) 2013 Microsoft Corporation. All rights reserved.
>
> C:\Users\Haris>cd
> AppData\Roaming\npm\node_modules\generator-angular-fullstack
>
>
> C:\Users\Haris\AppData\Roaming\npm\node_modules\generator-angular-fullstack>npm
> ls babel-core
> generator-angular-fullstack@3.0.0-rc6
> C:\Users\Haris\AppData\Roaming\npm\node_mo
> dules\generator-angular-fullstack
> └── babel-core@5.8.23
>
>
>
> C:\Users\Haris\AppData\Roaming\npm\node_modules\generator-angular-fullstack>
>
> On Fri, Sep 4, 2015 at 12:29 AM, Cody Mize <notifications@github.com>
> wrote:
>
>> @DylanRothko <https://github.com/DylanRothko> in
>> /usr/local/lib/node_modules/generator-angular-fullstack, @harissarwar
>> <https://github.com/harissarwar> in
>> C:\Users\Haris\AppData\Roaming\npm\node_modules\generator-angular-fullstack;
>> run npm ls babel-core. I just want to make sure that you both have the
>> module installed and up to date.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/DaftMonk/generator-angular-fullstack/issues/1244#issuecomment-137549398>
>> .
>>
>
>
>
> --
> Haris Sarwar
> Product Manager,
> Zigron <http://www.zigron.com/>
>



-- 
Haris Sarwar
Product Manager,
Zigron <http://www.zigron.com/>

**Comment by DylanRothko** [comment]
@kingcody 

$ npm ls babel-core
generator-angular-fullstack@3.0.0-rc6 /usr/local/lib/node_modules/generator-angular-fullstack
└── babel-core@5.8.23

**Comment by DylanRothko** [comment]
maybe this line has something to do with it: at Module._extensions..js (module.js:478:10)
i found another article issue here that says it had something to do with node-sass

hope this helps, wish I could be of more use

**Comment by kingcody** [comment]
@harissarwar @DylanRothko, I believe I have a solution... Would you both be so kind as to try this:

**generator-angular-fullstack/app/index.js** and **generator-angular-fullstack/endpoint/index.js**:
```javascript
'use strict';

// Register the Babel require hook
require('babel-core/register')({
  only: /generator-angular-fullstack\/(?!node_modules)/
});

// Export the generator
exports = module.exports = require('./generator');
```

**Comment by sherylpeebee** [comment]
was there ever any resolution to this issue? i'm experiencing the same error.

**Comment by kingcody** [comment]
See the above comment for a temporary solution, or use `3.0.0-rc5`. We'll try to have an official fix posted tomorrow.

**Comment by sherylpeebee** [comment]
thank you

**Comment by harissarwar** [comment]
I have tried these fixes, generator is working now.

I made following changes

'use strict';

// Register the Babel require hook
//require('babel-core/register');
require('babel-core/register')({
  only: /generator-angular-fullstack\/(?!node_modules)/
});

// Export the generator
exports = module.exports = require('./generator');



On Fri, Sep 4, 2015 at 11:51 AM, sher <notifications@github.com> wrote:

> thank you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DaftMonk/generator-angular-fullstack/issues/1244#issuecomment-137660690>
> .
>



-- 
Haris Sarwar
Product Manager,
Zigron <http://www.zigron.com/>

**Comment by pihomeserver** [comment]
Same issue on Mac OS, solved with the fix.
Thanks !

**Comment by DylanRothko** [comment]
@kingcody thanks, worked 100% for me.
