### ISSUE TITLE
[questions] Using grunt, where to keep global variables and how to get username of currently logged in user.

### ISSUE THREAD

**Issue by MyPCIsBetter** [DaftMonk/generator-angular-fullstack#1249]
I hope it's right place to ask questions.
I haven't had any contact with grunt before, so after creating a project with Yeoman generator I become a bit confused. In Readme.md there is some infomation about it but, being honest, I'm not exactly sure I understand everything.
So:
**1.** **When exactly should I use commands like "grunt" and "grunt serve"?** How my programming habits should look like? I mean: when to build my project? As I suspect, "grunt" simply does everything: testing, code compression and preparing project to be published in internet. I thought that "grunt serve" is for running my app for local testing: it does *something* and opens web browser. But after openning it in browser, there is task called "watch" and powershell writes "Waiting...". Moreover, the app loads endlessly and I can see blank page. So... **does it simply work incrorrectly or is this made for something else?**
**2.** The other question is: **where should I keep the basic information about who is currently logged in to my app?**  I'm making a simple chat app and I need to know who made a message sent to api. Is there some "place" in this project **where I should keep all, let's say, "global variables"**? Or maybe there currently is something like that in gerenated code? 
**3.** Is there some **better documentation** of what exactly happens in generated code? Explanation of what technologies are used and why?

Thanks in advance for your answers ;)

**Comment by kingcody** [comment]
1. That is what `grunt serve` is for, but it sounds like you are having some issues with you generated code, bugs maybe? What version of the generator did you use? What version of node?

2. Did you select `mongoose` or `sequelize` when you generated your project?

3. There isn't really a docs page other than the `README.md`, comment in the source code, and github issues.

**Comment by MyPCIsBetter** [comment]
@kingcody:
1. Does my understanding of those grunt commands are OK? `grunt` for publishing to internet, `grunt serve` for testing locally?
2. I don't remember if there was a question of whether I want `mongoose` or `sequelize`, but I think I'm using `mongoose` right now.

**Comment by kingcody** [comment]
Running `grunt` will run the default task list which is `['newer:jshint', 'test', 'build']`. `grunt serve` is for starting your app in development mode.

> I think I'm using mongoose right now

In `.yo-rc.json` in the `generator-angular-fullstack.filters` array do you see `mongooseModels` and/or `sequelizeModels` or `noModels`?

**Comment by MyPCIsBetter** [comment]
@kingcody none of them:
```javascript
"generator-angular-fullstack": {
    "insertRoutes": true,
    "registerRoutesFile": "server/routes.js",
    "routesNeedle": "// Insert routes below",
    "routesBase": "/api/",
    "pluralizeRoutes": true,
    "insertSockets": true,
    "registerSocketsFile": "server/config/socketio.js",
    "socketsNeedle": "// Insert sockets below",
    "filters": {
      "babel": true,
      "js": true,
      "html": true,
      "sass": true,
      "uirouter": true,
      "bootstrap": true,
      "uibootstrap": true,
      "socketio": true,
      "mongoose": true,
      "auth": true,
      "oauth": true,
      "googleAuth": true,
      "facebookAuth": true,
      "twitterAuth": true
    }
  },
```

**Comment by MyPCIsBetter** [comment]
@kingcody so, finally, what is the answer to my 2nd question? Let me explain it in other words: I generated new endpoint in my server/api called chat_message where I manage messages send by users to chat. I want to know what is the name and id of user that currently sent some message. How can I do that? Is this information storied somewhere?

**Comment by kingcody** [comment]
If you use `auth.isAuthenticated()` to restrict the route to logged in users, then `req.user` will be the associated model for that user.

**Comment by MyPCIsBetter** [comment]
@kingcody Is it safe? I mean: your solution gets userId from request that comes from client. What if client change id sent through request? The message would look like created by another user.

The other thing is: I used your solution to created my chat_message, but it doesn't work. It says: "validation failed".
```javascript
exports.create = function(req, res) {
  var userId = req.user._id;
  var chat_msg_data = req.body;
  chat_msg_data.postedBy = userId.id;
  //var newChatMessage = new ChatMessage(chat_msg_data);
  
  ChatMessage.create(chat_msg_data, function(err, chat_message) {
    if(err) { console.err("cannot create chat message"); return handleError(res, err); }
    return res.status(201).json(chat_message);
  });
};
```
Could it mean that userId I provided is wrong?

**Comment by Awk34** [comment]
They can't. In the stack, we use [JSON Web Tokens](jwt.io) for authentication. JWT tokens come with headers, a payload (including user ID), and a signature from the server. The server code verifies the JWT through the signature.

**Comment by MyPCIsBetter** [comment]
@Awk34 Thanks a lot ;) But problem I've described above isn't still solved.
Does user ID (got from req) is the same value as id of object "User" stored in database?

This is model of chat_message table:
```javascript
var ChatMessageSchema = new Schema({
  content: String,
  postedBy: {type: mongoose.Schema.Types.ObjectId, ref: 'User'},
  date: { type: Date, default: Date.now }
});
```
The code of operation of creating new chat_message was pasted in my previous post.

Am I doing it right? "postedBy" [is a reference](http://mongoosejs.com/docs/populate.html) to "User" table. I'm getting userId the same way you told me to do. I assign this id to chat_msg_data.postedBy. It doesn't work. "Validation failed".

Is it because that ID I've got isn't the same as ID in database? If yes, how would you assign message to current user?

I'm sorry that I'm keeping thread open, but this is the only place that I could get an answer, because you know this code :/

**Comment by Awk34** [comment]
You're setting `userId` to `req.user._id` which is a GUID string, and then try to set `chat_msg_data.postedBy` to be a property `id` of string `userId`. That doesn't look right to me.

**Comment by MyPCIsBetter** [comment]
@Awk34 So... how can I do it correctly? At least, please give me some advice where should I look for it.

**Comment by kingcody** [comment]
`chat_msg_data.postedBy = userId;`
