### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by jacovc86** [DaftMonk/generator-angular-fullstack#1255]
During the installation process, this thing accured, I don't know why.
Here is a snapshot:
![image](https://cloud.githubusercontent.com/assets/12764608/9702544/e632c59e-546a-11e5-8c3d-735e4645604e.png)

The end:
![image](https://cloud.githubusercontent.com/assets/12764608/9702610/68c8130c-546f-11e5-86c2-9c701a0cd6ab.png)

Any help?

**Comment by Awk34** [comment]
Follow the installation instructions for [node-gyp](https://github.com/nodejs/node-gyp)

**Comment by jacovc86** [comment]
Thank you. The thing is I don't remember installing gyp for the first place, do you recommend to remove it as it is no longer necessary?

**Comment by Awk34** [comment]
It is likely installed as a dependency of one of the app's dependencies. I'm sure you'll need it.

**Comment by jacovc86** [comment]
Thank you very much. It's all working properly now
