### ISSUE TITLE
Implement socketio rooms to server

### ISSUE THREAD

**Issue by ju4nkA** [DaftMonk/generator-angular-fullstack#1262]
How can I implement rooms to the server side?

**Comment by Awk34** [comment]
That's more of a Socket.io question than a question for this repo, no?

**Comment by kingcody** [comment]
[Here](https://github.com/DaftMonk/generator-angular-fullstack/issues/490#issue-41163440) is a very simple example of using socket.io rooms with a project generated by `generator-angular-fullstack`.
