### ISSUE TITLE
Add "Manual Annotating for Dependency Injection" From John Papa Style Guide

### ISSUE THREAD

**Issue by MohhamedRafi** [DaftMonk/generator-angular-fullstack#1268]
I am sorry if this is the wrong place to put this (I am new to github) but I was wondering if we can add Manual Annotating for Dependency Injection support for the generator. I was looking over john papa angular style guide and the style Y090 and Y091 caught my eye because they had a mini-faction safe syntax. I was wondering since this is a practice I seen all over the inter webs mainly in angular's official website I thought we can add it.

**Comment by Awk34** [comment]
This is unnecessary, as we use [ng-annotate](https://github.com/olov/ng-annotate) to do this automatically at build-time
