### ISSUE TITLE
Support Node 4.2

### ISSUE THREAD

**Issue by khwerhahn** [DaftMonk/generator-angular-fullstack#1278]
Upgrade to node 4? https://new.nodejs.org/en/

**Comment by kingcody** [comment]
We are investigating this, currently there are some broken deps that need to update. We'll see how things pan out over the next couple of weeks.

**Comment by Awk34** [comment]
This might as well serve as the tracking issue for it though.

**Comment by Awk34** [comment]
The one that I'm watching is gulp-sass, since it depends on node-sass, which is using `pangyp` instead of `node-gyp` and is causing issues. This has to do with the `gulp` branch that I'm working on for 3.0.0.

**Comment by Awk34** [comment]
Seems like this is resolved in node-sass.

**Comment by Awk34** [comment]
#1280 Adds Node 4.0.0 to the TravisCI targets

**Comment by corporationsruleyourmom** [comment]
[Good info here](https://nodejs.org/en/blog/release/v4.0.0/) pretty excited about seeing the advantages of Node.js and io.js working together

**Comment by macneib** [comment]
FYI: node 4.2.0 will be the LTS release

**Comment by Awk34** [comment]
@macneib source?

**Comment by macneib** [comment]
@Awk34 https://github.com/nodejs/node/issues/3000#issuecomment-144894835

**Comment by macneib** [comment]
4.2.0 LTS now released
https://twitter.com/nodejs/status/653644449025814528

**Comment by vartana** [comment]
Did this get resolved? If not what is the eta?

**Comment by Awk34** [comment]
The issue will be closed when resolved. No ETA. #1400 has to pass.
