### ISSUE TITLE
Connecting a node client to Server: socket.io-client

### ISSUE THREAD

**Issue by reggirepret** [DaftMonk/generator-angular-fullstack#1283]
Hi, 

I am struggling to understand where my problem is coming up. I have a node client that is going to run on an internet of things device (beaglebone black at the moment) it will send information to the server that will then add "readings" to the database that is then synced with the browser client.

However, during the initial handshake process where the IoT device connects to the server and the information that is required to setup the device is edited in the browser client I am experiencing a dead connection.

The testclient.js file runs and the initial communication works perfectly, the socket.on("newConnection", data) event fires up and all is well. However, when the server emits an event a bit later (after the browser client has edited the setup information) there is no response from the clienttest.js app.

I am completely lost as to what is causing this.

I am emitting events from server/config/socketio.js and clienttest.js is listening on the connection,

Please advise how I can get the node client to become responsive to emit events from the server.

clienttest.js
```
var socket = require('socket.io-client')('http://localhost:9000/',
{
	path: '/socket.io-client'
});
var jsonfile = require('jsonfile');

var file = '/Users/admin/Documents/4de Jaar/Skripsie/testing.json';
var util = require('util');
var currentRogueID;


socket.on("connect",function(){
	console.log("socket connected");
	//testConnection is a short script that looks for a json setup file that I have stored locally.
	testConnection();
});

//This is the event that needs to fire after the intial connection sequence
socket.on("updateRogue", function(data){
	console.log("updateRogue fired up" + data._id);
});

socket.on("newRogueCreated", function(data){
	jsonfile.readFile(file, function(err, obj) {
	//read file and check
		if(obj){
			//already registered, do nothing
			console.log("second connection");
		}
		else{
			//first time connecting, create json file to store rogue info.
			jsonfile.writeFile(file, data, function (err) {
	    	//console.error(err);
	    	//console.log("error occured");
	    	currentRogueID = data._id;
			//store id in space to use for readings.
			console.log("currrent ID:" + currentRogueID);
			});
		}
	});
});

socket.on("disconnect",function(){
	console.log("socket disconnected");  
});

function testConnection(){
	jsonfile.readFile(file, function(err, obj) {
	//read file and check
	if(obj){
		//already registered, do nothing
		console.log("old connection");
		//emit returning rogue event.
	}
	else{
		socket.emit("newRogueIncoming", "info");
		console.log("new rogue incoming emmited");
	}
});
}
```

server/config/socketio.js

the event "updateRogueServer" is fired (I have check the logs), the updateRogueServer event is emitted from the browser client
```
/**
 * Socket.io configuration
 */

'use strict';

var config = require('./environment');

// When the user disconnects.. perform this
function onDisconnect(socket) {
}

// When the user connects.. perform this
function onConnect(socket) {
  // When the client emits 'info', this listens and executes
  socket.on('info', function(data) {
    console.info('[%s] %s', socket.address, JSON.stringify(data, null, 2));
  });

  // Insert sockets below
  require('../api/rogue/rogue.socket').register(socket);
  require('../api/reading/reading.socket').register(socket);
  require('../api/rouge/rouge.socket').register(socket);
  require('../api/thing/thing.socket').register(socket);

}

module.exports = function(socketio) {
  // socket.io (v1.x.x) is powered by debug.
  // In order to see all the debug output, set DEBUG (in server/config/local.env.js) to including the desired scope.
  //
  // ex: DEBUG: "http*,socket.io:socket"

  // We can authenticate socket.io users and access their token through socket.decoded_token
  //
  // 1. You will need to send the token in `client/components/socket/socket.service.js`
  //
  // 2. Require authentication here:
  // socketio.use(require('socketio-jwt').authorize({
  //   secret: config.secrets.session,
  //   handshake: true
  // }));

  socketio.on('connection', function(socket) {
    socket.address = socket.request.connection.remoteAddress +
      ':' + socket.request.connection.remotePort;

    socket.connectedAt = new Date();

    // Call onDisconnect.
    socket.on('disconnect', function() {
      onDisconnect(socket);
      console.info('[%s] DISCONNECTED', socket.address);
    });
    socket.on('readingemit', function(data){
      var Reading = require('../api/reading/reading.model');
      Reading.create(data);
    });
    socket.on('newRogueIncoming', function() {
      console.log("newRogueIncoming event occured");
      var Rogue = require('../api/rogue/rogue.model');
      var d = {location: 'unknown'};
      Rogue.create(d, function(err,rogue){
        socket.emit('newRogueCreated', rogue);
      });
    });
    socket.on('updateRogueServer', function(data){
      console.log("event fired on server");
        socket.emit('updateRogue', data);
      console.log("updateRogue finished, testevent emitted");
    });
    // Call onConnect.
    onConnect(socket);
    console.info('[%s] CONNECTED', socket.address);
  });
};
```

Please help! This is work on my Thesis

**Comment by kingcody** [comment]
Could you be more specific as to which events, that you've set up, aren't working?

**Comment by reggirepret** [comment]
Hi,

Currently the emit event from server/config/socketio.js called socket.emit("updateRogue", data) is not working.

It is not firing on the node client side. And I also do not know how to test if the emit is working from the server side.

I am using for the rest of the project a standard yeoman angular fullstack generated app with express, css, javascript and socket.io

**Comment by kingcody** [comment]
Well in your example: `//socket.emit('updateRogue', rogue);`, is commented out.

**Comment by reggirepret** [comment]
I have updated the question, sorry that commented out version of the emit event was put there for testing purposes. I have removed it now, to avoid confusion. 

My problem I think is that the clienttest.js becomes "unresponsive" to any emit events from the server.

**Comment by reggirepret** [comment]
Hi @kingcody ,

Thank you so much for your help so far! I have been struggling over the past week, and it is great that someone is helping out!

**Comment by reggirepret** [comment]
Turns out I was broadcasting to only the client that emitted the "updateRogueServer" event. Therefore, changing the event socket.emit("updateRogue",data) to socketio.emit("updateRogue",data); solved the problem.

It was a namespace issue.
