### ISSUE TITLE
oAuth buttons gone from login/signup views after update to latest version

### ISSUE THREAD

**Issue by sebastianvilla** [DaftMonk/generator-angular-fullstack#1286]
It seems the oAuth buttons are gone since the last update. When generating a new project the buttons seem to be missing, even when an Authentication Boilerplate is selected in the options and all 3 networks are chosen.

Is anyone else experiencing this?

Version 3.0.0-rc7-patch.0.

**Comment by kingcody** [comment]
@sebastianvilla I'll take a look this evening. Thanks for the report.

**Comment by kingcody** [comment]
I'm not able to reproduce ATM. Could you post your `.yo-rc.json` contents for me?
