### ISSUE TITLE
How to deploy from gulp branch

### ISSUE THREAD

**Issue by minchomilev** [DaftMonk/generator-angular-fullstack#1295]
Hi, my project is build with angular fullstack - gulp branch, and how can I build production version

**Comment by Awk34** [comment]
`gulp build`

**Comment by minchomilev** [comment]
I've started gulp build several times but in my client folder i have only assets

**Comment by Awk34** [comment]
When was your project scaffolded with it? It *is* a WIP. Try running the
generator again.

**Comment by minchomilev** [comment]
I've removed the project and install it again, and now I got this error:

events.js:85
      throw er; // Unhandled 'error' event
            ^
ReferenceError: /Users/mmilev/.npm-packages/lib/node_modules/generator-angular-fullstack/app/templates/gulpfile.babel(gulp).js:1
 >> 1| // Generated on <%= (new Date).toISOString().split('T')[0] %> using <%= pkg.name %> <%= pkg.version %>
    2| 'use strict';
    3| 
    4| import _ from 'lodash';

pkg is not defined

**Comment by kingcody** [comment]
@minchomilev I've pushed a [commit](https://github.com/DaftMonk/generator-angular-fullstack/commit/ca176cc678f49cd5c8dab2dc0e2fd5bd178e754e) to the `gulp` branch that should address your current issue.
