### ISSUE TITLE
auth.isAuthenthicated() does not populate req.user

### ISSUE THREAD

**Issue by verrol** [DaftMonk/generator-angular-fullstack#1296]
Hi,

I can really use some here here. 

I am using angular-fullstack @3.0.0-rc5. I added a new end point 'post'. In server/api/post/post.controller.js, i added this: 

var auth = require('../../auth/auth.service');

which was copied from server/api/user/index.js. I want 'auth' in post.controller.js because I want to add the User._id to the Post before saving it. I want to do this in the exports.create method in post.controller.js.

however, I call auth.isAuthenticated(); as the first line as shown below, but req.user is still not populated:

// Creates a new Post in the DB
exports.create = function(req, res) {
  auth.isAuthenticated();
  req.body.submitterId = '';
  console.log('DEBUG - req.user: ', req.user);
// populate req.body.submitterId before saving
  Post.createAsync(req.body)
    .then(responseWithResult(res, 201))
    .catch(handleError(res));
};

If there is a better pattern the group have been using, please let me know.

Thanks,

.v

**Comment by Awk34** [comment]
That's not how `auth.isAuthenticated` works. It's an [Express Middleware](http://expressjs.com/guide/using-middleware.html). See an example of it being used here: https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/server/api/user(auth)/index.js#L11
