### ISSUE TITLE
oauth-buttons.html file has the incorrect file name - Oath buttons giving 404 not found

### ISSUE THREAD

**Issue by mcpDESIGNS** [DaftMonk/generator-angular-fullstack#1298]
The newest generator creates a 404 when trying to load the OathButtons directive.

The directive is looking for an `oauth-buttons.html` but it is generated as `oath-buttons.html`.

Easy fix, just wanted to let you know! :+1:

**Comment by Awk34** [comment]
This has already been fixed

**Comment by Awk34** [comment]
https://github.com/DaftMonk/generator-angular-fullstack/commit/23379553e114e446f6146db8e480461a178cfbfc

**Comment by mcpDESIGNS** [comment]
Thanks, I missed that one!
