### ISSUE TITLE
Grunt serve not launching

### ISSUE THREAD

**Issue by andershagebakken** [DaftMonk/generator-angular-fullstack#1307]
Hi. I have been working on a large project. Suddenly, when I run "grunt serve", the behavior is different. It does not launch in any browser window and the terminal window provides me with these lines:

Running "serve" task

Running "clean:server" (clean) task

Running "env:all" (env) task

Running "concurrent:server" (concurrent) task

Running "injector:scripts" (injector) task
Missing option `template`, using `dest` as template instead
Injecting js files (37 files)

Running "injector:css" (injector) task
Missing option `template`, using `dest` as template instead
Injecting css files (18 files)

Running "wiredep:target" (wiredep) task

Running "autoprefixer:dist" (autoprefixer) task

Running "express:dev" (express) task
Starting background Express server
Debugger listening on port 5858

And it stops here. Why is this suddenly happening and how can I fix it? I am using OS X.
Thanks in advance!

**Comment by mcpDESIGNS** [comment]
Have you made any changes to your grunt file recently?

Also, do you have mongo running and everything?

**Comment by andershagebakken** [comment]
I did not change the grunt file at all. Mongo is running fine on Mongolab. I tried to delete the node_modules and it seems to be working fine now. Sorry for the trouble.
