### ISSUE TITLE
Internet explorer 9 issue on production

### ISSUE THREAD

**Issue by ichbinedgar** [DaftMonk/generator-angular-fullstack#1311]
Hi,
I'm not sure if this is a bug or not. When I run the application from the dist folder, IE9 uses the compatibility mode IE7.If I run it using grunt serve:dist or grunt serve works smoothly (it's not using the compatibility mode). I'm using a linux (suse) server for production. Can you help me?

Forgot to add that I used grunt serve:dist or grunt serve locally on windows machine.

**Comment by Awk34** [comment]
I can't seem to reproduce. Do you have any more information on this?

**Comment by ichbinedgar** [comment]
So did you try it and work for you? I'm not sure how to give you that information. You can try it with a fresh installation and then just open the main page with IE9, you will see a blank page. My app can be access only via intranet, so maybe that's the issue. Well, thanks!

**Comment by ichbinedgar** [comment]
Hi,
I've just figured it out.

I needed to remove the IE conditionals from the top of the index.html:
```
<!DOCTYPE html>
<html>
....
```

That's it.
