### ISSUE TITLE
like generator-angular-fullstack but for mssql

### ISSUE THREAD

**Issue by jjgonver** [DaftMonk/generator-angular-fullstack#1315]
I'm looking for a generator like generator-angular-fullstack but I need to connect to a database MSSQL(i.e. angular-fullstack + sequelize + tedious). All projects that I found aren't actives.
Do you know something like that?
Thanks

**Comment by Awk34** [comment]
There's a project that supports Sequelize called [generator-angular-fullstack](https://github.com/DaftMonk/generator-angular-fullstack).

**Comment by Awk34** [comment]
To install the latest version that supports Sequelize, run `npm install --global generator-angular-fullstack@3.0.0-rc8` (Note that this *is* a prerelease)

**Comment by jjgonver** [comment]
ok, perfect. I go to test. Thanks

**Comment by jjgonver** [comment]
After run:
```npm install --global generator-angular-fullstack@3.0.0-rc8```
How to call to yeoman?

**Comment by Awk34** [comment]
`yo angular-fullstack`
