### ISSUE TITLE
Sequelize configuration info for other sql databases

### ISSUE THREAD

**Issue by jjgonver** [DaftMonk/generator-angular-fullstack#1319]
I'm testing the generator-angular-fullstack version 3.0.0-rc8 and by default install the sqlite3 configuration.
What I need to change to use another sql databases?
Which is the info for each sql databases (uri and options)?
If I want to use mssql. Do I need to install tedious?

A lot of thanks.

**Comment by jjgonver** [comment]
Meanwhile I managed to work with Postgres:

1. npm install --save pg
2. npm install --save pg-hstore
3. Create the database in postgres
4. Change the development.js file in server\config\environment:
````
sequelize: {
    uri: process.env.POSTGRES_URL || 'postgres://postgres:1234@localhost:5432/dev',
    options: {
      //logging: false,
      dialect: 'postgres',
      host: 'localhost',
      port: 5432,
      /*username: 'postgres',
      password: '1234',*/

      define: {
        timestamps: false
      }
    }     
  },

  seedDB: true
};
````

**Comment by kingcody** [comment]
@jjgonver here is a link to the sequelize docs: http://sequelize.readthedocs.org/en/latest/api/sequelize/

All the available options for connecting to the various supported databases are listed there.

However IMHO, you should probably stick with PostgreSQL for your production database. It is very robust and offers many features that others do not.
