### ISSUE TITLE
Error While Installing angular-fullstack

### ISSUE THREAD

**Issue by pravin-d** [DaftMonk/generator-angular-fullstack#1320]
I'm getting the following error while running 
yo angular-fullstack

node-pre-gyp install --fallback-to-build

  CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc:194:25: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
          result_type = "";
                        ^
1 warning generated.
  SOLINK_MODULE(target) Release/debug.node
  COPY /User/yo-angular/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v14-darwin-x64/debug.node
  TOUCH Release/obj.target/action_after_build.stamp
npm ERR! Darwin 14.3.0
npm ERR! argv "node" ".nvm/versions/node/v0.12.7/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.1
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.18 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.18 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     yo-angular/npm-debug.log

Any Idea how to solve it ?

**Comment by Awk34** [comment]
This is either a problem with PhantomJS or node-gyp. Try installing PhantomJS on its own. Make sure you have followed both packages' installation instructions.
