### ISSUE TITLE
npm run update-webdriver fails

### ISSUE THREAD

**Issue by ndjordjevic** [DaftMonk/generator-angular-fullstack#1325]
Just generated an app and by running this I got:

> dentalrec-mean@0.0.0 update-webdriver /Users/ndjordjevic/WebstormProjects/dentalrec-mean
> node node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager update

module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/ndjordjevic/WebstormProjects/dentalrec-mean/node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/Users/ndjordjevic/.nvm/versions/node/v0.12.7/bin/npm" "run" "update-webdriver"
npm ERR! node v0.12.7
npm ERR! npm  v3.3.4
npm ERR! code ELIFECYCLE
npm ERR! dentalrec-mean@0.0.0 update-webdriver: `node node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager update`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dentalrec-mean@0.0.0 update-webdriver script 'node node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager update'.
npm ERR! This is most likely a problem with the dentalrec-mean package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager update
npm ERR! You can get their info via:
npm ERR!     npm owner ls dentalrec-mean
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ndjordjevic/WebstormProjects/dentalrec-mean/npm-debug.log```

**Comment by kingcody** [comment]
It's possible one of your dependencies didn't download. You could try removing your `node_modules` folder and reinstalling with `npm install`.

**Comment by ndjordjevic** [comment]
Didn't help, but when I increased the grunt-protector-runner to the latest (2.1.0) everything was fine. The old version didn't get protactor at all, so the generator should be updated to get newest grunt-protactor-runner.

**Comment by xeroxoid** [comment]
@ndjordjevic Any version of grunt-protractor-runner that you now install will install protractor to `node_modules/protractor` instead of `node_modules/grunt-protractor-runner/node_modules/protractor` that it did before. This is why the script does not find the webdriver-manager... A quick fix is to just change the line in your `package.json` file.

```javascript
  "scripts": {
    "start": "node server/app.js",
    "test": "grunt test",
    "update-webdriver": "node node_modules/protractor/bin/webdriver-manager update" //this line
  },
```

**Comment by Awk34** [comment]
I haven't been able to reproduce. I just installed the latest version of `grunt-protractor-runner`, and installed the `webdriver-manager` program in the expected path.

**Comment by xeroxoid** [comment]
I think it has to do with some combos of node & npm versions.. I got the same.

**Comment by Awk34** [comment]
What are your versions @xeroxoid ?

**Comment by xeroxoid** [comment]
node: 0.10.40
npm: 3.3.6

**Comment by Awk34** [comment]
oh wow that's weird, your node version is way out-of-date, but your npm version is above what most people are using (most haven't moved to 3.x.x yet)

**Comment by xeroxoid** [comment]
Yeah well we run it on production and it's the latest 0.10 version so we procrastinate upgrading to anything newer. For npm I suppose I ran 'npm -g install npm' at some point ;)

**Comment by Shingaz** [comment]
Same issue here with `node 4.2.4` and `npm 3.5.3`. There is no bin folder in `grunt-protractor-runner` module:

```
Error: Cannot find module 'c:\dev\projects\angular-fullstack\node_modules\grunt-protractor-runner\node_modules\protractor\bin\webdriver-manager'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

Solved with using the binary in the `protractor` module instead, as mentioned by @xeroxoid.
