### ISSUE TITLE
ERR during npm install

### ISSUE THREAD

**Issue by liujason** [DaftMonk/generator-angular-fullstack#1329]
I'm not sure if this is because I'm using Node 4.1, but I'm getting the following error during brand new `npm install` after `yo angular-fullstack`

```
npm ERR! Failed at the v8-debug@0.4.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
```
I also noticed some WARN during install (not sure why it is looking for jsonwebtoken@4.2.2, even though the package file has ^5.0.0).
```
npm WARN engine karma@0.12.37: wanted: {"node":">=0.8 <=0.12 || >=1 <=2"} (current: {"node":"4.1.0","npm":"2.14.3"})
npm WARN deprecated jsonwebtoken@4.2.2: Critical vulnerability fix in v5.0.0. See https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/
npm WARN deprecated jws@2.0.0: Security update: Versions below 3.0.0 are deprecated.
npm WARN deprecated find-file@0.1.4: Use the globby package instead
npm WARN deprecated CSSselect@0.7.0: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
```

**Comment by liujason** [comment]
Same problem on npm:2.11.3, node:0.12.7.

**Comment by liujason** [comment]
Removing 'grunt-node-inspector' from package.json fixed the problem.

**Comment by Awk34** [comment]
Closing this as it's more a problem with the `grunt-node-inspector` package, rather than ours. Also, we don't officially support Node 4.x.x, because of cases like this!

**Comment by bostondevin** [comment]
I removed grunt-node-inspector and i'm still getting this error, but alas, i'm using Node 4.0 - what sort of effort would it take to make this work with the latest version of node? What version of node should we be using with this?

**Comment by Awk34** [comment]
Which version of the generator are you using, and which package fails?

**Comment by lwensveen** [comment]
I had this problem on Linux (Fedora), I got it fixed by installing the g++ package

For Fedora 22 it's: 

dnf install gcc-c++

For other distro's it might be:

yum install g++

apt-get install g++

**Comment by Awk34** [comment]
yes, that's documented in the node-gyp prereqs

**Comment by rahul-islam** [comment]
which version of Node you officially support??

**Comment by Awk34** [comment]
generator 2.x.x supports node 0.12.x.
generator 3.0.0 pre-release experimentally supports node >=4.1.1

**Comment by jcperez-ch** [comment]
Is there an ETA on when potentially the 3.x will be released? grunt-node-inspector seems like the most obvious dependency broken, have you found another one linked to node 4.x support?

**Comment by niksjaiswal** [comment]
@liujason can you post the full log.
