### ISSUE TITLE
Multiple auth

### ISSUE THREAD

**Issue by fcristel** [DaftMonk/generator-angular-fullstack#1337]
Is it possible to associate multiple oAuth to a single user? If someone connects with Facebook, and then wants to associate a Twitter account too

**Comment by chinnichaitanya** [comment]
Adding to that, I'm having trouble implementing two **Auth(local)** modules for two different sets of users in the same app one for public and one for internal use. 

Can someone please help me with that ?

**Comment by Awk34** [comment]
@fcristel I've got an example of that here: https://github.com/Awk34/aksite/tree/master/server/auth

**Comment by fcristel** [comment]
Thank you very much @Awk34 . 

I took a look at your project and I didn't see you implemented this functionality. Please correct me if I'm wrong.

I think I didn't make myself clear before. I already have an authentication using local, Facebook, G+ or Twitter and works fine. Users can register and login with one of the mentioned accounts. 

What I want to achieve is that an already registered user can associate another account and then choose to authenticate with any of the two. For example, if one user registered with a Facebook account, once authenticated, to be able to associate a Twitter account to the same user. This way, the next time he logs in, he can choose to do it with the Facebook or Twitter account, and return the same user.

The result is something like this: https://github.com/sahat/satellizer#api-reference
It has the <code>$auth.link</code> and <code>$auth.unlink</code> that seems to do exactly what I want. But with the problem that it doesn't use passport.js. 
I tried using the same approach, using <code>passport.authenticate</code> to signin and <code>passport.authorize</code> to link an account to the existing one, but with no success because, on one hand Facebook has only one configured callback URL, and on the other, although using passReqToCallback parameter in FacebookStrategy on setup, I don't have the expected request parameter passed back (I was expecting one with the authentication, indicating that the request was made from an already authenticated user).

**Comment by remicastaing** [comment]
@fcristel, take a look at https://github.com/remicastaing/ludiic. I tried in this project to automatically associate the same user created with the local and the FB strategy. Note that with Twitter, you have to gather and confirm the email address on your own, like for the local strategy.

**Comment by fcristel** [comment]
Interesting approach @remicastaing .
I see it more like a work-around, because I would limit the users to have the same email registered in the app and on Facebook or G+, etc. I, for example, have different emails on different social networks, so I think it doesn't quite solve the problem. 
But I will definitely consider this approach if I see that I can't find another solution. Thank you!

**Comment by Awk34** [comment]
@fcristel I do have the functionality. Look specifically at [this code](https://github.com/Awk34/aksite/blob/master/server/auth/facebook/passport.js#L17-L30). I check if there is a user already logged in, and if so, add the new OAuth data to that user's profile. That way [here](https://github.com/Awk34/aksite/blob/master/server/auth/facebook/passport.js#L31) I can check whether a person has associated Facebook with his/her account, and can log him/her in, even if the account was created using a different strategy.

**Comment by fcristel** [comment]
Oh, sorry @Awk34 . I can't believe i missed that part. It works perfectly. I was missing the <code>addAuthHeaderFromCookie</code> and <code>appendUser</code> from the callback and that's why my request came back with no user in it obviously. 
Thank you very much!

**Comment by Awk34** [comment]
Glad to help
