### ISSUE TITLE
ECMAScript 6 in server

### ISSUE THREAD

**Issue by urosjarc** [DaftMonk/generator-angular-fullstack#1341]
First of all, I want to say that this is THE BEST project generator: GOOD JOB GUYS!

My question, request: Is transpiler babel option avalible for the server part until node.js implement ES6 to the fullest, if not how can I help to make it happend.

I saw in the grunt console that babel task is running but if I use ES6 syntax it write me an error:
```Running "babel:server" (babel) task```
But after server runs:
```
	let test = 'test';
	    ^^^^
SyntaxError: Unexpected identifier
```

**Comment by Awk34** [comment]
Yes, in the latest pre-release we use Babel server-side. The error is pointing to `test`, not `let`, so I'd think you have a syntax error elsewhere.

**Comment by urosjarc** [comment]
Hm I try many things to check if in server side is possible to use ES6 but no luck so far.
I'm using generator-angular-fullstack@2.1.1 version. How would you suggest for me to check babel if it runs correctly.

**Comment by Awk34** [comment]
Server-side babel is only in the latest pre-release versions, the newest of which is `3.0.0-rc8`

**Comment by lvarayut** [comment]
Is the `3.0.0-rc8` version ready for production?

**Comment by Awk34** [comment]
No. RC stands for Release Candidate.

**Comment by lvarayut** [comment]
I saw the milestone for `3.0.0-rc8` which's currently 92%. Do you have any due date to release it?

**Comment by Awk34** [comment]
@lvarayut no
