### ISSUE TITLE
Inject bootstrap css in index.html

### ISSUE THREAD

**Issue by jainpuneet86** [DaftMonk/generator-angular-fullstack#1347]
Hello,

Thanks for awesome plugin, i need some help to make it work for my project. I want to use bootstrap css with my project. Although boot strap css exists in bower components, but its not included in index.html 

Please help me by suggesting how I can achieve the same.

**Comment by Awk34** [comment]
If you selected CSS as your styling language, Bootstrap CSS will be injected into `index.html` when `grunt wiredep` is run. Otherwise, Bootstrap CSS/SCSS/LESS will be imported into your `app.styl`/`app.scss`/`app.less`.

**Comment by jainpuneet86** [comment]
A

**Comment by jainpuneet86** [comment]
I was facing this issue due to a bug in bower config.

I was able to fix this following instructions mentioned in https://github.com/twbs/bootstrap/issues/16663
