### ISSUE TITLE
Yeoman generator-angular-fullstack app example

### ISSUE THREAD

**Issue by jjgonver** [DaftMonk/generator-angular-fullstack#1348]
I'm starting to use generator-angular-fullstack to make a project and want to know if there is an example of a project done with it to try to better understand its operation.

Thank you.

**Comment by chinnichaitanya** [comment]
You can find a well explained tutorial for beginners [here](http://tylerhenkel.com/building-an-angular-node-comment-app-using-yeoman/).

**Comment by jjgonver** [comment]
Hi chinnichaitanya. Thanks. I already know this tutorial. In my question I referred to a final App done with the result of the generator-angular-fullstack generator.
Thanks in advance.

**Comment by Awk34** [comment]
My personal website started with 2.1.1 - https://github.com/Awk34/aksite

**Comment by Awk34** [comment]
It seems like I answered your question.
