### ISSUE TITLE
Cannot find module 'babel-core/register'

### ISSUE THREAD

**Issue by charliegroll** [DaftMonk/generator-angular-fullstack#1349]
I followed the instructions for install

    sudo npm install -g yo grunt-cli bower generator-angular-fullstack

but I get the following error:

    Error: Cannot find module 'babel-core/register'
        at Function.Module._resolveFilename (module.js:336:15)
        at Function.Module._load (module.js:286:25)
        at Module.require (module.js:365:17)

I could just install it manually, but I'm wondering why I would need to do that. Everything went well with the [install](https://gist.github.com/charliegroll/df22a089f6792886b8fe).

**Comment by kingcody** [comment]
Is `babel-core` listed as a `devDependency` in `package.json`? If so, perhaps it just failed to install with the original generator run.

**Comment by charliegroll** [comment]
There were permissions issues

**Comment by mcpDESIGNS** [comment]
What do you mean by permission issues? I'm actually running into the same situation @charliegroll .

I did `sudo yo angular-fullstack` as well, but no luck.

**Comment by Awk34** [comment]
@mcpDESIGNS run as root

**Comment by pihomeserver** [comment]
I use the generator for few weeks now and today i need to add a new endpoint and got this error. I tried to update yo, npm, modules, remove babel-core, install it again, no way to make it run again
I use node 0.12.4, npm 3.4.1, bower 1.6.7 and generator-angular-fullstack 3.0.0@rc8

**Comment by mcpDESIGNS** [comment]
@pihomeserver I believe you need to be using Node `4.x` for the latest 3.0 generator.

**Comment by pihomeserver** [comment]
Ok strange that it worked since yesterday but i will upgrade and check. Thank you @mcpDESIGNS
