### ISSUE TITLE
Error after gulp build

### ISSUE THREAD

**Issue by minchomilev** [DaftMonk/generator-angular-fullstack#1352]
Hi, I am getting two errors in browser, when I try to start the production version of angulr full stack build with gulp. Everything is working just fine exept state changing.

Error: e.$current.locals is null
u@http://localhost:9001/app/vendor-64a9aea9c7.js:45:13617
S/u.compile/</<@http://localhost:9001/app/vendor-64a9aea9c7.js:45:14022

Error: [$injector:unpr] Unknown provider: nProvider <- n
http://errors.angularjs.org/1.4.5/$injector/unpr?p0=nProvider%20%3C-%20n
r/<@http://localhost:9001/app/vendor-64a9aea9c7.js:3:29774

**Comment by Awk34** [comment]
See 08f8648
