### ISSUE TITLE
style guide

### ISSUE THREAD

**Issue by jorgebo10** [DaftMonk/generator-angular-fullstack#1370]
I wanted to know if you are considering implementing  any styleguides such as https://github.com/johnpapa/angular-styleguide

Thanks

**Comment by mcpDESIGNS** [comment]
I'd be willing to help in implementing some of these minor changes.
I always prefer `var vm = this` controllerAs syntax, etc.

**Comment by Awk34** [comment]
Yes, we have been working on moving towards the newer best-practices of AngularJS. It's an ongoing process.
