### ISSUE TITLE
Facebook Auth in Production Not Working

### ISSUE THREAD

**Issue by liebeskind** [DaftMonk/generator-angular-fullstack#1371]
Everything is working in localhost.  In production (using Heroku), I have set Facebook ID and Secret and am not getting any redirect errors.  However, when I try to authenticate, the url changes to https://xxxx.herokuapp.com/xxxx.herokuapp.com/auth/facebook/callback?code=yyyyyy and then redirects back to the login page without logging the user in.

Any ideas what might be causing this issue?

**Comment by Awk34** [comment]
Which version of the generator are you using? And which version of `passport-facebook` are you using? FB had some breaking API changes not too long ago. My first guess is that that's it.

**Comment by liebeskind** [comment]
Awk, thanks for the reply.  Using passport-facebook@2.0.0 and generator-angular-fullstack@2.1.1

**Comment by Awk34** [comment]
[this](https://github.com/DaftMonk/generator-angular-fullstack/commit/f6e7a12ac9c08960ba89426a3ab64edbf9b22f6c) is the commit that updated the generator code for FB's changes. Make sure yours looks similar.

**Comment by liebeskind** [comment]
Thanks Awk - I have those changes implemented, but it's still not working unfortunately.  

Here is the heroku logs.  I don't think it's even getting to passport.:
    
    2015-10-17T05:59:26.753248+00:00 app[web.1]: GET /auth/facebook 302 3ms - 0b
    2015-10-17T05:59:26.915059+00:00 heroku[router]: at=info method=GET path="/xxxxx.herokuapp.com/auth/facebook/callback?code=yyyyyy" host=xxxxx.herokuapp.com request_id=zzzzzzz fwd="xx.xxx.xx.xxx" dyno=web.1 connect=1ms service=7ms status=200 bytes=1566
    2015-10-17T05:59:26.913253+00:00 app[web.1]: GET /xxxxx.herokuapp.com/auth/facebook/callback?code=yyyyyyyy 200 3ms

**Comment by Awk34** [comment]
:/ dunno what to tell you. You have any more information?

**Comment by liebeskind** [comment]
Awk, thanks for your help with this.  Solved by eliminating the ENV_DOMAIN from heroku config.
