### ISSUE TITLE
heroku client side injection errors

### ISSUE THREAD

**Issue by tharrington** [DaftMonk/generator-angular-fullstack#1381]
Getting not found errors on the heroku build... The injector creates references to a components directory within dist:

        
        <script src="app/app.js"></script>
          
          <script src="app/account/login/login.controller.js"></script>
          <script src="app/account/settings/settings.controller.js"></script>
          <script src="app/account/signup/signup.controller.js"></script>
          <script src="app/main/main.controller.js"></script>
          <script src="app/main/main.js"></script>
          <script src="app/order/order.controller.js"></script>
          <script src="app/order/order.js"></script>
          <script src="components/auth/auth.service.js"></script>
          <script src="components/auth/contact.service.js"></script>
          <script src="components/modal/modal.service.js"></script>
          <script src="components/mongoose-error/mongoose-error.directive.js"></script>
          <script src="components/navbar/navbar.controller.js"></script>
          
        

Of course there is no components directory within dist since the javascript is consolidated in  app.js and vendor.js files. This causes a 404  which is fixed simply by deleting these reference in index.html before pushing to heroku... In either case, this is a pain.

**Comment by Awk34** [comment]
check your line endings

**Comment by tharrington** [comment]
can you please elaborate.

**Comment by Awk34** [comment]
https://github.com/DaftMonk/generator-angular-fullstack/issues/491#issuecomment-60721970
