### ISSUE TITLE
Disable livereload

### ISSUE THREAD

**Issue by Kinnardian** [DaftMonk/generator-angular-fullstack#1387]
How do you disable livereload? Specifically the script injection.

**Comment by mcpDESIGNS** [comment]
In your `gruntfile.js` serach for `livereload`

The files section are the rules for what it's looking for to inject if added / modified / deleted / etc.
Comment out the second line in `files[]`, that's the one looking for `.js` files.

      livereload: {
        files: [
          '{.tmp,<%= yeoman.client %>}/{app,components}/**/*.{css,html}',
          '{.tmp,<%= yeoman.client %>}/{app,components}/**/!(*.spec|*.mock).js', 
                 // ^ -- you could comment out this line (notice the .js at the end
          '<%= yeoman.client %>/assets/images/{,*//*}*.{png,jpg,jpeg,gif,webp,svg}'
        ],
        options: {
          livereload: true // <-- this should disable livereload for all of the above
        }
      },
