### ISSUE TITLE
Clean install has python issues

### ISSUE THREAD

**Issue by aceymer** [DaftMonk/generator-angular-fullstack#1388]
After I made a clean angular-fullstack I got a python not installed error and could not complete a npm install.

After changing the "grunt-node-inspector" to version 0.4.1(newest version) everything seems to be running again.
"grunt-node-inspector": "~0.4.1",
  

Anyone knows why and can we maybe fix this so I dont have to change it everytime I make a new project?

Thanks!
Lars

**Comment by Awk34** [comment]
This package has been updated in canary and will be in the next release
