### ISSUE TITLE
grunt task bower install 

### ISSUE THREAD

**Issue by macneib** [DaftMonk/generator-angular-fullstack#1389]
I hit a temporary roadblock when using a build script for an angular-fullstack project.  Apparently doing a bower install from an out of scope directory is not possible.  After investigating  I found grunt-bower-install-simple.  Here's how to set it up in the Gruntfile.  
forgive the lack of camelCase, not my doing.
Hope it helps someone.

```
  // Load grunt tasks automatically, when needed
  require('jit-grunt')(grunt, {
    'bower-install-simple': 'grunt-bower-install-simple'
  });
```
```

    'bower-install-simple': {
      options: {
        color: true
      },
      prod: {
        options: {
          production: true
        }
      },
      dev: {
        options: {
          production: false
        }
      }
    },
```

```
  grunt.registerTask('bower-install', [
    'bower-install-simple'
    ]);
```

and then you should be able to do something like this:

```
grunt --base $buildpath --gruntfile $buildpath/Gruntfile.js bower-install
```

**Comment by macneib** [comment]
You can close the issue if you wish

**Comment by Awk34** [comment]
this is just a grunt task to run the bower dep installer?

**Comment by macneib** [comment]
yep.  I was on a mission to get my angular-fullstack docker container down to 80MB.  
My script executed from /builder/build.sh and when it calls bower, it seemed to get a little lost when traversing the child directories.

```
/builder/builds/angular-fullscatck-build/angular-fullstack/bower.json
```
In grunt you can specify `grunt --base $buildpath --gruntfile $buildpath/Gruntfile.js build` and grunt has the built in features to get into child directories.
