### ISSUE TITLE
GridFS errors

### ISSUE THREAD

**Issue by chinnichaitanya** [DaftMonk/generator-angular-fullstack#1391]
Hello all,
I'm not sure if this comes under generator-fullstack or not. But I hope someone has already faced this issue.
I'm trying to store the files in mongoDB GridFS. The uploading for all types of files is happening perfectly fine (checked the `md5sum` and also checked extracting them using `mongofiles`). But when I try to download these uploaded files **through browser**, there seems to be an issue with `.pdf` and `.zip` files. Those are downloading but getting corrupted. The `pdf` file is only displaying blank content but the number of pages in the file are matching. But the corrupted file is bigger in size than the actual one.
This issue is already reported in stackoverflow [here](http://stackoverflow.com/questions/29562954/downloaded-pdf-files-are-corrupted-when-using-expressjs). 
I've tried with many file types. This is working with `.png`, `.jpg`, `.docx`, `.mp3` but not with `.pdf` and `.zip` files.

MongoDB version - 3.0.7
NodeJS version - 0.12.5

Below is my controller code
```
exports.serve = function(req, res) {
  gfs.findOne({ _id: req.params.id}, function (err, file) {
    if(!file){
      return res.status(404).send({
        message: 'File not found'
      });
    }
    else {
      console.log(file);
    }

    var mimetype = mime.lookup(file.filename);
    res.writeHead(200, {'Content-Type': mimetype});
    
    var readstream = gfs.createReadStream({
      filename: file.filename
    });
 
    readstream.on('data', function(data) {
      res.write(data);
    });

    readstream.on('end', function() {
      res.end();        
    });
 
    readstream.on('error', function (err) {
      console.log('An error occurred!', err);
      throw err;
    });
  });
};
```

Below is `index.js` file
```
'use strict';

var express = require('express');
var controller = require('./upload.controller');

var router = express.Router();


router.get('/:id/:filename', controller.serve);
router.post('/', controller.create);
router.delete('/:id', controller.destroy);

module.exports = router;
```

Screenshot of the output for `pdf's`
![2015-10-27-222051_1366x768_scrot](https://cloud.githubusercontent.com/assets/6941024/10765514/1e11f122-7cf9-11e5-8bb1-4f910b0329ae.png)
 

Any help is appreciated.

**Comment by Awk34** [comment]
The generator doesn't do anything with GridFS at the moment. This is a question best asked elsewhere.

**Comment by chinnichaitanya** [comment]
@Awk34 I just want to know if someone else has already faced this issue and solved it. Anyway, thanks for the help.
