### ISSUE TITLE
latest stable version 2.1.1 does not prompt for auth and socket.io setup

### ISSUE THREAD

**Issue by csreddy** [DaftMonk/generator-angular-fullstack#1397]
Readme says that it'll prompt for those options but it did not.

**Comment by Awk34** [comment]
You need to select Mongoose and/or Sequelize. Did you select to use neither?

**Comment by csreddy** [comment]
Yes, I need to hook up a different database

**Comment by Awk34** [comment]
Which database? Your best bet is probably to select one of the options, and then replace the mongoose/sequelize code with whatever database code you need.

**Comment by csreddy** [comment]
MarkLogic.

Yeah that's what I need to do. I did not realise those options were tied to selecting a database.   It would be nice to show a message or warning when no db is selected.

**Comment by Awk34** [comment]
I've made it more obvious in the README that Auth and Socket.IO require a database to be scaffolded also

**Comment by csreddy** [comment]
cool. thanks
