### ISSUE TITLE
No "views" folder in public/dist

### ISSUE THREAD

**Issue by fcristel** [DaftMonk/generator-angular-fullstack#1401]
Hi

There is no "views" folder inside my "dist" folder. What am I missing here?

I have a "public" folder, and inside it there is a "app" folder (containing the app.js, app.css, vendor.js and vendor.css), and then the "assets" folder and the "bower_components" folder. Where are the html views?

Thanks!

**Comment by Awk34** [comment]
The templates should be in your `app.js` file. We use [grunt-angular-templates](https://github.com/ericclemmons/grunt-angular-templates) to pre-load them in JS.

**Comment by fcristel** [comment]
Ah OK, found them :)

It's just that my production environment doesn't work. Development is OK, but on production I get an error:
<code> Uncaught SyntaxError: Unexpected token < </code> in <code>404:1</code> and I have no idea why.

**Comment by Awk34** [comment]
Is that on a clean install?

**Comment by fcristel** [comment]
it was on a clean install, yes. I will check the dependencies, maybe I'm missing something there. thanks!

**Comment by Awk34** [comment]
If you think there's a bug with the generator, please open a new issue with the error you get, and which versions of things you are using.

**Comment by fcristel** [comment]
Got it solved. 
For anyone in the future, the problem was a little stupid: one of my bower_components had an uppercase and I was going from a Windows environment in development to a Linux in production, and Linux is case-sensitive. Also, another bower that wasn't loading, causing the crash. 
In order to better see what the problem is (I was getting a white screen with no user-friendly error description), upload all "client" folder into the "dist/public" folder, and you'll easily get the location.
