### ISSUE TITLE
Error Message for Yo Version

### ISSUE THREAD

**Issue by DavidHolzgang** [DaftMonk/generator-angular-fullstack#1403]
Hi...

When I install 'generator-angular-fullstack' on a fresh node version, after installing all dependencies, I get the following result:

npm WARN EPEERINVALID generator-angular-fullstack@2.1.1 requires a peer of yo@>=1.2.0 but none was installed.
npm WARN EPEERINVALID generator-ng-component@0.0.10 requires a peer of yo@>=1.0.0 but none was installed.

However, as you can see from this listing, Yo @1.5.0 is installed globally. 
$ npm ls -g --depth=0
/usr/lib
+-- bower@1.6.5
+-- generator-angular-fullstack@2.1.1
+-- grunt-cli@0.1.13
+-- gulp@3.9.0
+-- npm@3.3.10
`-- yo@1.5.0

What's going on??

**Comment by olivierl** [comment]
Same for me...

**Comment by adrienne-at-work** [comment]
Me too

**Comment by zroyer** [comment]
same, please fix!!

**Comment by Awk34** [comment]
See https://github.com/npm/npm/releases/tag/v3.0.0, specifically the paragraph about `peerDependencies`. We don't support npm ^3.0.0 yet.

To prevent the warning from popping up run this instead:
```
npm install --global yo generator-angular-fullstack
```

**Comment by Huaci** [comment]
Me too

**Comment by vijaychauhanssn** [comment]
npm WARN generator-angular-fullstack@2.1.1 requires a peer of yo@>=1.2.0 but ne was installed. 
this cmd not working properly can you give me any answer  please..
