### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by Ricecrispi** [DaftMonk/generator-angular-fullstack#1408]
I am getting the following error when I run my debugger in Webstorm (although grunt serve is working fine):

import express from 'express';
^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

Process finished with exit code 1

Does anyone know what the problem might be? Thanks!

**Comment by MohhamedRafi** [comment]
Go to your package.json and check the version of babel. If the version is v6 or up you need to install the presets es2015 and stage-0 and add to your babelrc http://babeljs.io/blog/2015/10/29/6.0.0/#plugin-presets

**Comment by Awk34** [comment]
What do you mean by 'when I run my debugger in Webstorm'? What is actually getting run?

**Comment by mycompassspins** [comment]
I'm having the same problem. I was getting the same error as the OP when running my app in a production environment (e.g., `grunt serve:dist`). I was able to solve that by taking @MohhamedRafi's suggestion and installing the presets, and then adding the following to my package.json:

    "babel": {
		"presets": ["es2015", "stage-0"]
	}

However, this breaks the development environment. Throws the following error on app start:

`/Applications/XAMPP/xamppfiles/htdocs/NEC/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126
      if (!option) this.log.error("Unknown option: " + alias + "." + key, Refe
                           ^
TypeError: Cannot read property 'error' of undefined
    at OptionManager.mergeOptions (/Applications/XAMPP/xamppfiles/htdocs/NEC/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:28)
    at OptionManager.addConfig (/Applications/XAMPP/xamppfiles/htdocs/NEC/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/Applications/XAMPP/xamppfiles/htdocs/NEC/node_modules/babel-core/lib/transformation/file/options/option-manager.js:171:32)
    at OptionManager.init (/Applications/XAMPP/xamppfiles/htdocs/NEC/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at compile (/Applications/XAMPP/xamppfiles/htdocs/NEC/node_modules/babel-core/lib/api/register/node.js:117:22)
    at normalLoader (/Applications/XAMPP/xamppfiles/htdocs/NEC/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Applications/XAMPP/xamppfiles/htdocs/NEC/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
`

Any further suggestions would be very much appreciated.

**Comment by MohhamedRafi** [comment]
Make sure the the .babelrc is in the root directory and also make sure babel is at v6

**Comment by mcpDESIGNS** [comment]
@Ricecrispi I was getting the same issue. 
@Awk34 I believe this happens from a Grunt serve or grunt serve:dust
It seems babel isn't compiling the server side is files, so import breaks.

@Ricecrispi what errors do you get when you do a grunt build?

**Comment by Awk34** [comment]
@Ricecrispi @mcpDESIGNS which version of the generator does this happen on?

**Comment by mcpDESIGNS** [comment]
For me, it's generator 2.14.7.
Node 4.2.2

I did a fresh install, and didn't have any problems strangely..

It looks like Rice's server files aren't running through `babel` (at least that's my guess)

Because the end result is this for server/app.js for example:

    import express from 'express';
    import mongoose from 'mongoose';
    import config from './config/environment';

Instead of becoming:

    var express = require('express');
    var mongoose = require('mongoose');
    var config = require('./config/environment');

I've been trying to figure this one out for the past week, I was about to just move everything into a new project and see if that fixes it at this point.

**Comment by mcpDESIGNS** [comment]
@Ricecrispi 
So I FINALLY figured it out...

(I'm not sure what fixed it, but it was one of these things)
It's complaining about base.optional so I removed that part from the gruntfile

    babel: {
      //options: { // <-- I removed all of this (I'll try again if it works with it)
      //  sourceMap: true
      //},
      server: {
        options: {
          // optional: ['runtime'], // <-- I removed this
          presets: ['es2015']      //  <--- *** ADDED THIS ***
        },
        // everything else I left the same
        files: [{
          expand: true,
          cwd: '<%= yeoman.server %>',
          src: ['**/*.{js,json}'],
          dest: '<%= yeoman.dist %>/<%= yeoman.server %>'
        }]
      }
    },

Then I ran a few `npm` installs

    npm install --save-dev load-grunt-tasks
    npm install --save-dev grunt-babel     (got this one from you Awk34 https://github.com/DaftMonk/generator-angular-fullstack/issues/1282)
    npm install --save-dev babel-preset-es2015

Made sure I was on Node 0.12.7 (since we're using the 2.14.7 generator)

Works now :)

Thanks for all your help @Awk34

**Comment by Awk34** [comment]
@mcpDESIGNS you needed the es2015 preset because you updated Babel to 6.0.0+. The generator supports 5.x.x, since Babel 6 still has issues.

**Comment by mcpDESIGNS** [comment]
Yup that's definitely it. I'm guessing Rice has the same problem, hopefully it fixes it for him

**Comment by pihomeserver** [comment]
@mcpDESIGNS thank you for advices. Unfortunately it does not work for node 4.2.2 and the generator 3.0.0-rc8
What logs can i provide to you to help you on that ?
