### ISSUE TITLE
Error while installing 3.0.0-rc8 with Node 4.2.2

### ISSUE THREAD

**Issue by lvarayut** [DaftMonk/generator-angular-fullstack#1412]
Based on the #1329, I saw you mentioned that "generator 3.0.0 pre-release experimentally supports node >=4.1.1". I have tried `3.0.0-rc8` with `node 4.2.2`. However, I still got some errors, shown below, while running `npm install`:

<img width="1280" alt="screen shot 2015-11-06 at 11 58 13 pm" src="https://cloud.githubusercontent.com/assets/4281887/11003145/65b03f2e-84e3-11e5-8e4e-b80eadf8b5ed.png">

Any workaround on this issue?

**Comment by Awk34** [comment]
Seems like it's an issue with grunt-contrib-imagemin. Mind asking them about it?
