### ISSUE TITLE
Modules in Client.

### ISSUE THREAD

**Issue by MohhamedRafi** [DaftMonk/generator-angular-fullstack#1413]
Looking over the generator's gruntfile and it looks like there is no browserfiy config. So I wondering how do you guys have modules in the client?

**Comment by gardner** [comment]
https://github.com/bower/bower

**Comment by MohhamedRafi** [comment]
@gardner I dont understand how that helps. I am wonder how can I use common-js modules in client side.

**Comment by gardner** [comment]
This project does not use browserify. bower is a tool used to manage client side dependencies. We manage modules on the client side using bower. A bug tracker isn't the right place to ask questions like this.

**Comment by Awk34** [comment]
@MohhamedRafi as @gardner , all client-side dependencies use Bower. I'm working on getting the project set up with Webpack, and we'll probably try to get Browserify working eventually too.
