### ISSUE TITLE
req.user is undefined using passport strategies

### ISSUE THREAD

**Issue by sandorTuranszky** [DaftMonk/generator-angular-fullstack#1415]
I am implementing passport.authorize() to incorporate information from multiple third-party services. `req.user` is undefined in: 

        passport.use(new LinkedInStrategy({
                consumerKey: config.linkedin.clientID,
                consumerSecret: config.linkedin.clientSecret,
                callbackURL: config.linkedin.callbackURL,
                passReqToCallback: true
            },
            function (req, accessToken, refreshToken, profile, done) {
    
        if (!req.user) {
         //req.user is undefined both with passport.authenticate() and passport.authorize()
          // Not logged-in. Authenticate based on Twitter account.
        } else {
          // Logged in. Associate Twitter account with user.  Preserve the login
          // state by supplying the existing user after association.
          // return done(null, req.user);
        }
    }));

server/auth/linkedin/index.js

    router
      .get('/', passport.authenticate('linkedin', {
        scope: ['r_basicprofile', 'r_emailaddress'],
        failureRedirect: '/signup',
        session: false
      }))
    
      .get('/callback', passport.authenticate('linkedin', {
        failureRedirect: '/signup',
        session: false
      }), auth.setTokenCookie);

So I can not perform any check on req.user.

**Comment by Awk34** [comment]
what does your `server/auth/linkedin/index.js` look like?

**Comment by sandorTuranszky** [comment]
Updated with server/auth/linkedin/index.js

**Comment by sandorTuranszky** [comment]
Which request you mean? 
These:

    // Passport Configuration
    require('./facebook/passport').setup(User, config);
    require('./google/passport').setup(User, config);
    require('./linkedin/passport').setup(User, config);
    
    var router = express.Router();
    
    router.use('/facebook', require('./facebook'));
    router.use('/google', require('./google'));
    router.use('/linkedin', require('./linkedin'));

**Comment by Awk34** [comment]
Add the `appendUser` function to your `server/auth/auth.service.js`, and then change your `linkedin/index.js` to use `.get('/callback', auth.addAuthHeaderFromCookie(), auth.appendUser(), passport.authenticate('linkedin', {`.

```
function appendUser() {
    return compose()
        // Attach user to request
        .use(function(req, res, next) {
            validateJwt(req, res, function(val) {
                if(_.isUndefined(val)) {
                    User.findById(req.user._id, function(err, user) {
                        if(err) {
                            return next(err);
                        } else if(!user) {
                            req.user = undefined;
                            return next();
                        } else {
                            req.user = user;
                            next();
                        }
                    });
                } else {
                    req.user = undefined;
                    next();
                }
            });
        });
}
```

**Comment by Awk34** [comment]
@sandorTuranszky did this get solved?

**Comment by sandorTuranszky** [comment]
Yes, thanks!

**Comment by vicky-gonsalves** [comment]
@Awk34 Worked for me too. Thanks!
