### ISSUE TITLE
NODE v5:npm v3.4 ERR! v8-debug@0.4.6 install: `node-pre-gyp install --fallback-to-build`

### ISSUE THREAD

**Issue by meezyart** [DaftMonk/generator-angular-fullstack#1424]
still happening

**Comment by meezyart** [comment]
https://github.com/DaftMonk/generator-angular-fullstack/issues/1416

please update the repo

**Comment by Awk34** [comment]
That package is already set to its latest version

**Comment by meezyart** [comment]
When install this threw yo I'm still getting the error. what i'm i doing wrong? how do I get the latest package into yo?

**Comment by meezyart** [comment]
its still set to  "grunt-node-inspector": "~0.1.5",

**Comment by meezyart** [comment]
to "grunt-node-inspector": "^0.4.1",

**Comment by meezyart** [comment]
this  "grunt-env": "~0.4.1", is right above that line maybe you change the wrong one..

**Comment by Awk34** [comment]
https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/_package.json#L65
