### ISSUE TITLE
Tooooo loooong Gruntfile.js!

### ISSUE THREAD

**Issue by urosjarc** [DaftMonk/generator-angular-fullstack#1426]
Gruntfile is like a long spaghetti, this need to be fixed. I suggest folowing structure...

Demo Gruntfile.js:
```

	// Define the configuration for all the tasks
	grunt.initConfig({

		// Project settings
		pkg: grunt.file.readJSON('package.json'),

		//---> Here you define all grunt configs
		yeoman: require('./grunt/configs/yeoman'),
		express: require('./grunt/configs/express'),
		open: require('./grunt/configs/open'),
		watch: require('./grunt/configs/watch'),
		jshint: require('./grunt/configs/jshint'),
		clean: require('./grunt/configs/clean'),
		autoprefixer: require('./grunt/configs/autoprefixer'),
		'node-inspector': require('./grunt/configs/node-inspector'),
		nodemon: require('./grunt/configs/nodemon'),
		wiredep: require('./grunt/configs/wiredep'),
		rev: require('./grunt/configs/rev'),
		useminPrepare: require('./grunt/configs/useminPrepare'),
		usemin: require('./grunt/configs/usemin')

	});

        //---> Here you register all tasks
	require('./grunt/tasks/express-keepalive')(grunt);
	require('./grunt/tasks/default')(grunt);

};
```

**Comment by dolanmiu** [comment]
I had this EXACT thought! 

but didn't question it because I assumed how it is done now is good practice (to have all of it in one cute nice file)

**Comment by urosjarc** [comment]
If file in project is long more than 3 pages of scrolling then refactor this spageti monster on any project that you see!

**Comment by dolanmiu** [comment]
hmmm

there must be a reason why this issue is being raised just now and never before. Spaghetti monsters are maybe a good and healthy thing

**Comment by urosjarc** [comment]
I'm on a project that requires a hell lot of the customatization of the grunt init configuration, and belive me when I say its a hell to work with curent gruntfile. Every config for grunt should be in separate folder so that when you want to find watch options you can simply search by the file with name watch.js and bam you are editing. While in gruntfile there could be multiple words with this name so you loose important time while searching for the options. And separate options are better so that when 2 configs options are dependent you can easy open grunt config files for those and start editing side by side in tabs. Curently I'm using ~40 base grunt config options and plugins for grunt file and there will be even more, so there needs to be a better support for gruntfile or even automatization for plugins!

**Comment by Awk34** [comment]
#848
