### ISSUE TITLE
directive and ui-grid template not complied during build

### ISSUE THREAD

**Issue by alaksandarjesus** [DaftMonk/generator-angular-fullstack#1431]
I got my directive and ui-grid templates which are not compiled during build. But its working fine if i use grunt serve

The root for directives will be

rootFolder/app/main/directives/myDirective/myDirective.html
rootFolder/app/main/directives/myDirective/myDirective.js
rootFolder/app/main/directives/myDirective/myDirective.scss

All html files are compiled into js files and so couldnt debug.

**Comment by Awk34** [comment]
your front-end code should live in the `client/components` or `client/app` folder. Also, make sure that the js code is in the build section of `index.html.

**Comment by alaksandarjesus** [comment]
I got it solved. I stated ./rootFolder/app/main/directives/myDirective/myDirective.html in my code.

It was supposed to be
rootFolder/app/main/directives/myDirective/myDirective.html
