### ISSUE TITLE
how to use sass i required

### ISSUE THREAD

**Issue by nuptxxp** [DaftMonk/generator-angular-fullstack#1432]
there is a question,
because index.html no flat-ui , i installed flat-ui by myself
when i install flat-ui(bower install flat-ui)
then i modify index.html , i added
 <script src="bower_components/flat-ui/dist/js/flat-ui.js"></script>
yes , i added releaded css file about flat-ui in index.html

but when i use "grunt serve: to build web server, 
all i added  disappear

please help, what should i do i can add what i added css/js

**Comment by mcpDESIGNS** [comment]
Is flat-ui within your `bower.json` file?

**Comment by Awk34** [comment]
What you're asking is really hard to understand, but it seems like you manually added a CSS file to your `index.html` and it's getting replaced on `grunt serve`. You probably put it inside the wiredep block:

```html
    <!-- bower:css -->
    <!-- endbower -->
```

try putting it outside of that block

**Comment by nuptxxp** [comment]
yes, it's in in my bower.json,but when grunt server runs, i see flat-ui not injected error,
now i solved it, i used css instead of sass

**Comment by Awk34** [comment]
If [Flat-UI](https://github.com/designmodo/Flat-UI) *is* in your bower dependencies, wiredep *should* be able to add its css to your `index.html`, since it [does have it in its bower.json 'main' array](https://github.com/designmodo/Flat-UI/blob/master/bower.json#L6).

**Comment by Awk34** [comment]
Closed due to inactivity
