### ISSUE TITLE
SocketIO Events for Single Clients via Channels

### ISSUE THREAD

**Issue by khwerhahn** [DaftMonk/generator-angular-fullstack#1436]
Hi,

I'm currently trying to find a good solution to push data to a certain client, when data which concerns the user gets updated/created... 

Example: User with id = 6 gets updated. I don't want to inform all clients (in this case) that user 6 was updated, but only user 6, who is connected. 

Has anybody done something like this within generator-angular-fullstack? 

If more people are interested I would submit a PR.

**Comment by Awk34** [comment]
Please refer to the Socket.io documetation

http://socket.io/docs/server-api/#socket#emit(name:string[,-…]):socket
