### ISSUE TITLE
Need help with "grunt build"

### ISSUE THREAD

**Issue by ColoArg93** [DaftMonk/generator-angular-fullstack#1437]
Hello! i have an error when i need build the project.

When i execute the comand "grunt build" i have this error at end:

<code>
Running "ngAnnotate:dist" (ngAnnotate) task
>> 2 files successfully generated.

Running "copy:dist" (copy) task
Created 111 directories, copied 455 files

Running "cdnify:dist" (cdnify) task
Going through dist/public/index.html to update script refs
<p style="color:red;">Fatal error: builder is not defined</span>
</code>

Please, help!

**Comment by mcpDESIGNS** [comment]
Please note what version of the `generator` you are using as well as what preferences you selected.

**Comment by ColoArg93** [comment]
@mcpDESIGNS 

The version is <strong>3.0.0-rc8</strong> and i selected this preferences:


Scripts: Javascript
Markup: HTML
Stylesheets: CSS
Router: ngRoute
Bootstrap: Yes
UI Bootstrap: Yes
MongoDB with mongoose: Yes
Scaffold out an authentication boilerplate: Yes
oAuth strategies: Google, Facebook, Twitter
Socket.io: No

**Comment by Awk34** [comment]
https://github.com/btford/grunt-google-cdn/issues/64

**Comment by ColoArg93** [comment]
@Awk34 
What's the lastest node version that angular-fullstack  support?

**Comment by Awk34** [comment]
2.1.1 supports ~0.12.7
3.0.0-rc8 supports ~4.2.2

**Comment by ColoArg93** [comment]
@Awk34  Thank you!

**Comment by mcpDESIGNS** [comment]
Maybe it would help if we had that on the Readme?

**Comment by ColoArg93** [comment]
@mcpDESIGNS 
Yes, of course. That would be helpful.

**Comment by Awk34** [comment]
Already listed [here](https://github.com/DaftMonk/generator-angular-fullstack/blob/master/package.json#L65), [here](https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/_package.json#L114), and [here](https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/README.md#L65)
