### ISSUE TITLE
Project works on development, but not in production

### ISSUE THREAD

**Issue by uiktiomasfeliz** [DaftMonk/generator-angular-fullstack#1440]
Hi there,
This is mi second project using angular-fullstack, the project works relly good on grunt serve(local).
When i build it and up to openshift, apears blank page, same problem on local(dist folder, runing like this -> NODE_ENV=production node app.js). No errors on console or network.
No error's on grunt build, ang generate me all js and css.
What can produce this?
Sorry for my broken English.
![angularfull]
(https://cloud.githubusercontent.com/assets/5663564/11265313/af5fdc8a-8e9b-11e5-8bb9-ab1f89df185e.png)

This is the only errro i got in console when i run "grunt"

INFO [karma]: Karma v0.12.37 server started at http://localhost:8080/
INFO [launcher]: Starting browser PhantomJS
ERROR [launcher]: No binary for PhantomJS browser on your platform.
  Please, set "PHANTOMJS_BIN" env variable.
Warning: Task "karma:unit" failed. Used --force, continuing.

**Comment by Awk34** [comment]
What is the content of your built `index.html`?

**Comment by uiktiomasfeliz** [comment]
thank you for response, finally i made it working.
Change the package.json and bower.json "latest" to the actual version of all packages and reinstall angular-fullstack.

**Comment by Awk34** [comment]
Yeah, I've been meaning to fix that...
