### ISSUE TITLE
Use options with angular-fullstack:endpoint

### ISSUE THREAD

**Issue by lucaskerdoncuff** [DaftMonk/generator-angular-fullstack#1443]
Hi,
When I'm using options as --models to create a new endpoint: yo angular-fullstack:endpoint --models cepage
I've got the following issue:
Error: Did not provide required argument name!
Any idea ?

**Comment by mcpDESIGNS** [comment]
https://github.com/DaftMonk/generator-angular-fullstack#endpoint

Are you supplying a name at the end?
yo angular-fullstack:endpoint MyEndpointName

**Comment by Awk34** [comment]
Yes, as @mcpDESIGNS says you need to provide a name!

**Comment by lucaskerdoncuff** [comment]
Yes, I supply a name at the end, if I'm doing: yo angular-fullstack:endpoint <name> it works, but if I add an option: yo angular-fullstack:endpoint --models <name>, I have an issue ... May be I missed something during the update ...
