### ISSUE TITLE
Question: Login page first

### ISSUE THREAD

**Issue by ajmarmar** [DaftMonk/generator-angular-fullstack#1446]
Hi,

I new with angularjs and I'm trying use this generator, 

 I want the page login first and not the main, I play with the code and my solution is to add 'authenticate: true' in MainCtrl
```javascript
angular.module('myapp')
  .config(function ($stateProvider) {
    $stateProvider
      .state('main', {
        url: '/',
        templateUrl: 'app/main/main.html',
        controller: 'MainCtrl',
        authenticate: true
      });
  }); 
```
and comment the line 'event.preventDefault();' in app.js in the run function
```javascript
.run(function ($rootScope, $location, Auth) {
    // Redirect to login if route requires auth and you're not logged in
    $rootScope.$on('$stateChangeStart', function (event, next) {
      Auth.isLoggedInAsync(function(loggedIn) {
        if (next.authenticate && !loggedIn) {
          //event.preventDefault();
          $location.path('/login');
        }
      });
    });
```
But I'm not sure is this changes are good or there are other best solutions.

Regards.

**Comment by pihomeserver** [comment]
Hi. Not a reference but i did the same for main.js but not for app.js. Why did you comment the line in app.js ?

**Comment by ajmarmar** [comment]
HI,

Thank for answer. I commented the this line because if this line is active when I access to main, don't redirect to login page and I've got a black page.

**Comment by pihomeserver** [comment]
Ok. I do not have that issue

**Comment by ajmarmar** [comment]
Hi guy,

Any suggestion on this???

**Comment by Jargonius** [comment]
Change the `main.js` like so:
```angular.module('myapp')
  .config(function($stateProvider) {
    $stateProvider
      .state('main', {
        url: '/login',
        templateUrl: 'app/account/login/login.html',
        controller: 'LoginCtrl',
        controllerAs: 'login'
      });
  });```

Then change `client/app.js` like this:
```.config(function($stateProvider, $urlRouterProvider, $locationProvider, $httpProvider) {
    $urlRouterProvider
      .otherwise('/login');```

**Comment by Awk34** [comment]
@ajmarmar from what I understand, you want to redirect someone loading your site fresh (meaning not being routed from another page on your site) to the login screen if they aren't logged in. You can try adding this code to your app/auth module:

```js
  .run(function($rootScope, $state, Auth) {
    $rootScope.$on('$stateChangeStart', function(event, toState, toParams, fromState, fromParams) {
      if(!fromState || !fromState.name) {
        Auth.isLoggedIn(1).then(is => {
          if(is) return;

          $state.go('login');
        })
      }
    });
  })
```

It will check if the user isn't being routed from somewhere else in the app, then check if the user is not logged in, and then bring him/her to the login page.

**Comment by Jargonius** [comment]
Sorry, I forgot that my solution kind of sidesteps the main page.  I personally didn't want to use it.  @Awk34's solution is much better.

**Comment by ajmarmar** [comment]
HI, thank very much .

Regards.

**Comment by ajmarmar** [comment]
@Awk34 this solution is for v3.0.1 or v2.2.1??? Now I test v3.0.1

Regards.

**Comment by Awk34** [comment]
I based that code off of 3.0.1, but it shouldn't be all too different with 2.1.1

**Comment by ajmarmar** [comment]
Thx

**Comment by ajmarmar** [comment]
I installed a v3, and I'm trying add this code in client/components/auth/auth.module.js

'use strict';

angular.module('test2App.auth', [
  'test2App.constants',
  'test2App.util',
  'ngCookies',
  'ui.router'
])
  .config(function($httpProvider) {
    $httpProvider.interceptors.push('authInterceptor');
  }).run(function($rootScope, $state, Auth) {
    $rootScope.$on('$stateChangeStart', function(event, toState, toParams, fromState, fromParams) {
      if(!fromState || !fromState.name) {
        Auth.isLoggedIn(1).then(is => {
          if(is) {return;}

          $state.go('login');
        });
      }
    });
  });

But don't run, the web don't navigate and not load page.

**Comment by Abdizriel** [comment]
I've tried to do that with v3.1:

```javascript
.run(function($rootScope, $state, Auth) {
    // Redirect to login if route requires auth and the user is not logged in, or doesn't have required role
    $rootScope.$on('$stateChangeStart', function(event, next) {
      if(!next.authenticate) {
        return;
      }

      if(typeof next.authenticate === 'string') {
        Auth.hasRole(next.authenticate, _.noop).then(has => {
          if(has) {
            return;
          }

          event.preventDefault();
          return Auth.isLoggedIn().then(is => {
            $state.go(is ? 'main' : 'login');
          });
        });
      } else {
        Auth.isLoggedIn(_.noop).then(is => {
          if(is) {
            return;
          }

          event.preventDefault();
          $state.go('login');
        });
      }
    });
  });
```

But it didn't help. Do you know solution for that with v3.1?

**Comment by Awk34** [comment]
@ajmarmar I'm not sure, but you *might* need to but that `.run` on your main 'test2App' module

**Comment by ajmarmar** [comment]
@Awk34 HI, I didn't test, because I try to learn angularjs, but in 3.0.2 with setting "authenticate:true" in the route for me is fine. I recommend you that we can to choose if we want set the login page first or no when we create a project

**Comment by Awk34** [comment]
@ajmarmar That would only add complication to the project, since I believe it's not something many people would want in the first place. It shouldn't be too hard to implement anyway, especially with the information provided in this issue.
