### ISSUE TITLE
Why do I get this error message?

### ISSUE THREAD

**Issue by ahsanbagwan** [DaftMonk/generator-angular-fullstack#1456]
I get this error when running the `yo angular-fullstack`. Can anyone guide me out of this issue? 

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Object [object Object] has no method 'isAbsolute'
    at Generator.processDirectory (C:/Users/ahbagwan/AppData/Roaming/npm/node_mo
dules/generator-angular-fullstack/util.js:110:19)
    at Generator.generateProject (C:/Users/ahbagwan/AppData/Roaming/npm/node_mod
ules/generator-angular-fullstack/app/generator.js:399:14)
    at C:\Users\ahbagwan\AppData\Roaming\npm\node_modules\generator-angular-full
stack\node_modules\yeoman-generator\lib\base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:354:15)

**Comment by JuanSomniis** [comment]
You need write the application name .
```
yo angular-fullstack [nameProject]
```

**Comment by Awk34** [comment]
Actually, you don't *need* to provide a name. If you don't, it will use the name of the directory you're currently in. @ahsanbagwan which version of Node are you using?

**Comment by anotherweblog** [comment]
I have the same problem as well.

I have tried it with Node versions v0.10.21, v4.2.3 and v5.1.1.

**Comment by Awk34** [comment]
The error comes from the `path` module not having the `isAbsolute` method. The lowest version of Node you should be using is 0.12.9. Here's the doc for `path`: https://nodejs.org/docs/v0.12.9/api/path.html . 

@anotherweblog are you sure you got the same error when using 4.2.3?

**Comment by anotherweblog** [comment]
@Awk34 My bad, I tried it again with Node 4.2.3 and it worked. I must have been using 0.10.21 by misstake. Thanks for the quick reply!

**Comment by Awk34** [comment]
Cool, no problem. I assume @ahsanbagwan has the same problem, so I'm going to close the issue.
