### ISSUE TITLE
Sass and ruby 

### ISSUE THREAD

**Issue by asinghsoften** [DaftMonk/generator-angular-fullstack#1458]
how can solve it error message .
 Running "sass:server" (sass) task
    Warning: 
    You need to have Ruby and Sass installed and in your PATH for this task to work.
    More info: https://github.com/gruntjs/grunt-contrib-sass
     Use --force to continue.

    Aborted due to warnings.

**Comment by Awk34** [comment]
I think that error message is pretty self-explanatory..
