### ISSUE TITLE
Swig render option

### ISSUE THREAD

**Issue by kevinawoo** [DaftMonk/generator-angular-fullstack#193]
Is it possible to have an option for swig? http://paularmstrong.github.io/swig/

Here's a snippet of what I did for swig under `lib/config/express.js`
I changed the default control statements:
```
var swig = require('swig'),
    _ = require('lodash'),
    swigConfig = {
        varControls: ['<%=', '%>'],
        tagControls: ['<%', '%>'],
        cmtControls: ['<#', '#>']
    };


...

if ('development' === env ) {

...

    // Swig will cache templates for you, but you can disable
    // that and use Express's caching instead, if you like:
    app.set('view cache', false);
    // To disable Swig's cache, do the following:
    _.extend(swigConfig, {
        cache: false
    });
    // NOTE: You should always cache templates in a production environment.
    // Don't leave both of these to `false` in production!
}

...

    app.engine('html', swig.renderFile);
    swig.setDefaults(swigConfig);
```

**Comment by kevinawoo** [comment]
I'm not using the generator for swing anymore. Closing case.

**Comment by Awk34** [comment]
..One year later..   XD

**Comment by kevinawoo** [comment]
In my defense, I generated once, head downs develop for a year, project shutdown, and I'm here to generate a second time.

Also durning that time, I learned swig had some very troublesome scoping issues and would not recommend moving forward. Haha.. Happy to help though!
