### ISSUE TITLE
Search User by :id

### ISSUE THREAD

**Issue by mrowles** [DaftMonk/generator-angular-fullstack#249]
It would be good to be able to search for a user by id, rather than /users/me. Setting up the routing is causing a few headaches, [the second answer](http://stackoverflow.com/questions/11534710/angularjs-how-to-use-routeparams-in-generating-the-templateurl) in this link might help. I'm going to try and work on this over the weekend, as well as an article/blog template, see how I go.

**Comment by Awk34** [comment]
Looks like this was done: https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/server/api/user(auth)/index.js#L14
