### ISSUE TITLE
ngtemplates build step misses out on revisioning

### ISSUE THREAD

**Issue by Climax777** [DaftMonk/generator-angular-fullstack#360]
Hi

The ngtemplates build task will not have rev'd assets. Is it possible to rewrite the built templates as a final step? Maybe a regex replace will be enough.

I not only need to revision rewrite them, but I would also like to CDN prepend them with my CDN. 

I've managed to do this for non-template related includes (like css etc.), but not angular templates.

This is all necessary for me, because I need to serve all assets from CDN, and currently template dependencies will not be served.

**Comment by aendrew** [comment]
I'm having the same issue, and I think #802 is a dupe of this.
