### ISSUE TITLE
Session timeout

### ISSUE THREAD

**Issue by agaskell** [DaftMonk/generator-angular-fullstack#381]
I changed the `signToken` function to this in auth.service:

    function signToken(id) {
      return jwt.sign({ _id: id }, config.secrets.session, { expiresInMinutes: 9000000 });
    }

My users are being prompted to login daily, sometimes multiple times per day. Is there anything else I need to configure for session persistence?

**Comment by Awk34** [comment]
Will hopefully be fixed with #444
