### ISSUE TITLE
requesting larger chunks of json is not working…

### ISSUE THREAD

**Issue by kevinfoerster** [DaftMonk/generator-angular-fullstack#413]
hi there,

i just tried to request some records from mongodb and saw some strange behavior, in my case I requested all records of a given table, in this case 429 records, after receiving them successfully I used `res.json(200, videos)` to output that object as a json.

it seems like my browser does not receive the full 429 records (look like twice the same output), therefor it is not valid json and cant be used for anything. while investigating this issue, i found out that limiting the number of results by using `videos = videos.slice(0, 43);` before sending the json solves that issue but limits the output.

including one more item of the videos array will break the json again… there is nothing wrong with next entry as `videos = videos.slice(20, 60);` is also working as well, displaying 45 elements will break it again.

i tried to output the same data using an older version of the generator (1.4.3) without any problems, all 429 records show as expected.

intresting tidbit: chrome, firefox and safari seem to render the json twice which makes it invalid,a simple `curl http://localhost:9000/api/videos | subl` does not show the json duplicated. I tried a second computer to be sure that its not my browser plugins messing with me.

btw… how can i figure out which version generator-angular-fullstack was used to create a project and is there a way to update an existing project?

**Comment by kingcody** [comment]
I can confirm the issue as well. If anyone would like to follow along or take a stab: https://github.com/expressjs/compression/issues/20

**Comment by kingcody** [comment]
Hmm, it would seem that `connect-livereload@0.4.x` was actually causing the issue; but only when used with `expressjs/compression`.

By upgrading (`npm install --save-dev connect-livereload@0.5.3`) to the newest version the issue was resolved in my tests.

@kevinfoerster, @benjipott, @mathieuartu, @Awk34 can you all confirm this?

**Comment by Awk34** [comment]
So this issue was only happening in dev?

**Comment by kingcody** [comment]
It would seem so. Were you able to confirm the resolution?

**Comment by Awk34** [comment]
nah I'm still at work, will take a look when I get home

**Comment by dougwilson** [comment]
As additional information, someone needs to make a PR to change https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/_package.json#L75 to require some version of `connect-livereload >= 0.5.0`; before 0.5.0, it does not play nice with any modules that also overwrite `res.write`, like `express-session` and `compression`, to name just a few popular ones.

**Comment by kingcody** [comment]
closed by #1065
