### ISSUE TITLE
Role in client route authorization

### ISSUE THREAD

**Issue by f2net** [DaftMonk/generator-angular-fullstack#423]
I think it would be useful to have "authorization:admin" or "authorization:user" inside the client routes. Otherwise a user could see the admin interface of a page which doesn't call an API (thus returning the 401 error). It is true that the HTML interface should contain no secrets, but I think it is better not to allow the routing to an admin page to a simple user.

**Comment by trainerbill** [comment]
I just create a PR:

https://github.com/DaftMonk/generator-angular-fullstack/pull/839

Now you can place a param authorize on the ui state to check if its an admin user.

**Comment by Awk34** [comment]
This has been resolved with the Auth module, thanks to @kingcody
