### ISSUE TITLE
Problems loading embedded SVGs via URI

### ISSUE THREAD

**Issue by SundayLab** [DaftMonk/generator-angular-fullstack#488]
i made a custom directive using d3.js for displaying a graph. The graph is well styled. I added a route and included a graph specific css file (use plain css) in that folder. The problematic thing is the graph just will show up correctly if i use the directive in the main.html. Whenever i include it in another view the additional svgs are missing like arrows and so on.

**Comment by psmilburn** [comment]
I believe a colleague of mine found a workaround for this issue. He said it was "something to do with how angular handles fragment paths". 

Simply add location.href to the url as below:

`.attr("marker-end", function(d) { return "url("+location.href+"#" + d.type + ")"; })`
