### ISSUE TITLE
grunt serve:dist not concated all of app.js

### ISSUE THREAD

**Issue by Kageetai** [DaftMonk/generator-angular-fullstack#491]
Hi there,

I tried out your generator for a project and am generally very happy with it. But after working on it for a while and several commits to my project, I wanted to try out deploying to Heroku and ran `grunt serve:dist` but when the process ran through and the browser window opens I notice several 404s for all the apps script files. After looking into the generated `index.html` in `dist`I saw that the said files don't seem to get put into the minified `app.js` like here:

```html
<script src="app/93e24447.vendor.js"></script>

        <!-- build:js({.tmp,client}) app/app.js -->
        <script src="app/cf3a9943.app.js"></script>
          <!-- injector:js -->
          <script src="app/account/account.js"></script>
          <script src="app/account/login/login.controller.js"></script>
          <script src="app/account/settings/settings.controller.js"></script>
          <script src="app/account/signup/signup.controller.js"></script>
          <script src="app/admin/admin.controller.js"></script>
          <script src="app/admin/admin.js"></script>
          <script src="app/main/main.controller.js"></script>
          <script src="app/main/main.js"></script>
          <script src="components/auth/auth.service.js"></script>
          <script src="components/auth/user.service.js"></script>
          <script src="components/mongoose-error/mongoose-error.directive.js"></script>
          <script src="components/navbar/navbar.controller.js"></script>
          <!-- endinjector -->
        <!-- endbuild -->
```

I generated a new project with the generator again and everything works fine. So I checkout out my very first commit in my project, where I just commited the unchanged code the yeoman generated. Still the same problem!
I even compared both projects file by file now and besides the names (and hashes of course) there are now differences in them at all!

Does anyone know about this problem and can help me out?

**Comment by Kageetai** [comment]
I just stumbled upon that again in another project. Any progress on integrating that into the generator?

**Comment by Awk34** [comment]
@Kageetai .editorconfig and .jscsrc in canary validate line breaks

**Comment by Lo5t** [comment]
+1

**Comment by rkumar1904** [comment]
Hey @Meg4mi  That's awesome !
