### ISSUE TITLE
Angular-fullstack:Heroku fails with "App not found"

### ISSUE THREAD

**Issue by jamescrowley** [DaftMonk/generator-angular-fullstack#504]
I've just created a vanilla angular-fullstack , and then tried to run angular-fulstack:heroku. However, Im getting "App not found". I'm just taking all the default options presented (random name, region US). If I run through again specifying a name, and then specifying again, I then get "Name already taken". 

Logs below:

    $ yo angular-fullstack:heroku
    [?] Name to deploy as (Leave blank for a random name): 
    [?] On which region do you want to deploy ?

    Initializing deployment repo
    Reinitialized existing Git repository in /Users/X/Development/X/dist/.git/

    Creating heroku app and setting node environment
    Creating obscure-temple-X... done, region is eu
    http://obscure-temple-X.herokuapp.com/ | git@heroku.com:obscure-temple-X.git

    Setting config vars and restarting X... 
    failed

    ✗ { [Error: Command failed:  !    App not found
    ] killed: false, code: 1, signal: null }

**Comment by shashvattrip** [comment]
I am also facing this problem. I created an app which failed to deploy to heroku because of the same error. Not when I try to rerun the yo angular-fullstack:heroku command, I think it looks for the older app that I deleted.
Can you help me fix this?

**Comment by Awk34** [comment]
@shashvattrip If you're still having this issue with a fresh install of the generator, would you open a new issue?

**Comment by shashvattrip** [comment]
Hey @Awk34 . I don't remember what I did but the issue was resolved. I don't think it was an issue with angular-fullstack, probably with my code. Thanks for asking though!

**Comment by SILVERjl** [comment]
For me, I had to re-clone my repository, do "bower install", "npm install", and then run the command again.  

There must have been something in the build cycle that got left over from my countless deploys.  I'd recommend this if all else fails.

~Jedi
