### ISSUE TITLE
socket.service not updating during scope digest

### ISSUE THREAD

**Issue by ericmcgregor** [DaftMonk/generator-angular-fullstack#519]
I'd like to put this out there to see if anybody else was having this issue in certain situations.  I ran into a problem where, possibly due to the way i was passing my factory objects around or using references to individual objects, the syncUpdates function in the components/socket/socket.service.js file was not triggering an update.   

What i found was that by replacing array.splice with _.merge near line 44 solved the issue for me.  My current code looks like this:

          // replace oldItem if it exists
          // otherwise just add item to the collection
          if (oldItem) {
            // array.splice(index, 1, item);
            //switched to merge.  triggers scope digest.
            _.merge(array[index], item);
            event = 'updated';
          } else {
            array.push(item);
          }

My thought was that using the splice method might break references to that original object elsewhere, while merge would preserve that reference during dirty checking.  This could very well be an edge case, as this service works great in most situations, but I thought it might be worth noting and getting feedback on.  thanks.

**Comment by BennySamir** [comment]
@ericmcgregor i use _.assign (https://lodash.com/docs#assign) for the references problem:
```JS
if oldItem
  #array.splice index, 1, item
  ###*
   * Overwrite the oltItem
  ###
  _.assign(oldItem, item)
  event = 'updated'
else
  array.push item

**Comment by Awk34** [comment]
Closed due to inactivity.
