### ISSUE TITLE
spin.js breaks whole build process

### ISSUE THREAD

**Issue by 9mm** [DaftMonk/generator-angular-fullstack#522]
So this person decided to name their bower package with a file extension... really kind of stupid I think.

What is the easiest way to fix all this? The original problem was with rev, i tried a hacky fix and now the problem is with usemin:js.

Is there a way to rename a folder with bower or something, or an easier way I'm not thinking of? Thanks!

**Comment by Pirhoo** [comment]
I've got the same issue with [animate.css](https://github.com/daneden/animate.css). I solved it by excluding directories with `.css` or `.js` at the first level of `bower_components`:

```javascript
rev: {
  dist: {
    files: {
      src: [
        '<%= yeoman.dist %>/public/{,*/}*.js',
        '<%= yeoman.dist %>/public/{,*/}*.css',
        '<%= yeoman.dist %>/public/assets/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}',
        '<%= yeoman.dist %>/public/assets/fonts/*',
        '!<%= yeoman.dist %>/public/bower_components/*.{css,js}'
      ]
    }
  }
}
```

**Comment by Unitiser** [comment]
I had a similar issue, stefbach pointed out that this issue was resolved in v3 of usemin. I did not try it, but this could be a great improvement!
http://stackoverflow.com/questions/28442613/uglify-cant-parse-flow-js/28709677#28709677

**Comment by ascheucher** [comment]
If you do not want to exclude the whole bower_components directory, you can exclude the affected library. Here an example for 'auth0.js':

            '<%= yeoman.dist %>/public/{,*/}*.js',
            '!<%= yeoman.dist %>/public/bower_components/auth0.js',
            '<%= yeoman.dist %>/public/bower_components/auth0.js/{,*/}*.js',
