### ISSUE TITLE
Ability to generate "clean" application

### ISSUE THREAD

**Issue by hannupekka** [DaftMonk/generator-angular-fullstack#525]
Is there any way to generate application without any controllers, views etc.? Or easily remove generated ones?

**Comment by larrysharpe** [comment]
I'd like this feature. To be more specific, a way to generate without thing endpoint and a way to basically remove generated features like routes and endpoints.

**Comment by kingcody** [comment]
We can easily generate the project now without the `thing` endpoint as it is generated by the endpoint sub-gen now. Which client-side controllers, directives, and views would you propose be omitted for a `--bare` project?
