### ISSUE TITLE
Suggestion: supertest-as-promised for unit tests.

### ISSUE THREAD

**Issue by gintsgints** [DaftMonk/generator-angular-fullstack#544]
This project:

https://www.npmjs.org/package/supertest-as-promised

allows to use promises instead of putting calls inside calls for tests. May be it is worth to take look.

**Comment by kingcody** [comment]
@gintsgints is this something that you would like to contribute still?

**Comment by gintsgints** [comment]
Not sure I have much time. But I can try.

Which branch I have to check for latest development code?

**Comment by kingcody** [comment]
That would be `canary`

BTW, I hope you have been well (:

**Comment by gintsgints** [comment]
I think we can close this now. Because tests already done differently in canary and they are not stacking anymore.

**Comment by kingcody** [comment]
Thank you for reviewing this @gintsgints.
