### ISSUE TITLE
Bower dependencies are not updated in Karma.config.js 

### ISSUE THREAD

**Issue by azachar** [DaftMonk/generator-angular-fullstack#594]
Hi, 
is there a possibility to integrate this feature https://github.com/stephenplusplus/grunt-wiredep/issues/35 into your generator?

Thank you for your answer.

Best regards,
Andrej

**Comment by yoshiokatsuneo** [comment]
Now, PR for update karma.conf.js was merged in generator-angular.
https://github.com/yeoman/generator-angular/issues/856
How about merging the commit to generator-angular-fullstack, too ?
