### ISSUE TITLE
wrong path for less file injection from `client/components`

### ISSUE THREAD

**Issue by matantsu** [DaftMonk/generator-angular-fullstack#596]
i added a less file for the navbar in `client/components/navbar/navbar.less` , sure enough it gets injected into `client/app/app.less` but the path is `navbar/navbar.less` instead of `../components/navbar/navbar.less`

**Comment by Awk34** [comment]
It's actually because of `filePath = filePath.replace('/client/components/', '');` in the Less injector task. I've made it use the proper relative path in the Gulp file, and plan to change it in Grunt too
