### ISSUE TITLE
Nice bootstrap social buttons

### ISSUE THREAD

**Issue by azachar** [DaftMonk/generator-angular-fullstack#640]
Hey Tyler!
What about to integrate http://lipis.github.io/bootstrap-social/

It is quite simple and looks great!

If you want I can also provide you a login page with a focus to social providers rather than to local login/password. Here is the example:

![image](https://cloud.githubusercontent.com/assets/4659019/4657830/2b32def0-54f2-11e4-9758-82fe3b50d128.png)

Best regards,
Andrej

**Comment by Awk34** [comment]
@azachar did you ever get anywhere with making a PR?

**Comment by azachar** [comment]
Well I have implemented it, but have not time to finalize for PR.

**Comment by johntmyers** [comment]
I just did a `bower install bootstrap-social` on my project and everything worked just fine, the HTML exists to use this lib, but it's not included in bower by default when you scaffold out the project.

**Comment by azachar** [comment]
Here is the PR of my changes - https://github.com/DaftMonk/generator-angular-fullstack/pull/1151
