### ISSUE TITLE
Creation of route does not write js or controller to index.html

### ISSUE THREAD

**Issue by jfraboni** [DaftMonk/generator-angular-fullstack#658]
I tried to create a route, using:

`yo angular-fullstack:route myroute`

The documentation says it will wire up all the boilerplate, which the generator did, BUT, strangely it didn't include the javascript or controller for the new route into a tag within the index.html file, and I had to manually include this tags.

I'm on the current stable of node, yo@1.3.3 and current version of angular-fullstack.

I do, however, have these warnings:

    npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/normalize-package-
    data requires github-url-from-git@'~1.1.1' but will load
    npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/github-url-from-git,
    npm WARN unmet dependency which is version 1.4.0
    npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/normalize-package-data requires github-url-from-username-repo@'^0.2.0' but will load
    npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/github-url-from-username-repo,
    npm WARN unmet dependency which is version 1.0.0

**Comment by yuwendaocloud** [comment]
@Awk34 same problem. resolved after re-running `grunt serve`. thanks.

**Comment by Awk34** [comment]
@yuwendaocloud np! This issue should be closed.
