### ISSUE TITLE
GET /fonts/glyphicons-halflings-regular.woff 304 2ms

### ISSUE THREAD

**Issue by Kageetai** [DaftMonk/generator-angular-fullstack#692]
There have been similar issues, but I have the issue with the not appearing fonts like the glyphicons and every text using them just appearing as boxes.
I noticed a 304 code in the shell when accessing the page.
My entire project is available here so maybe someone could try it out on his machine, I would appreciate it: https://github.com/Kageetai/JayMap
I even created another project with the generator again, where everything works and compared everything for anything but nothing helps.

**Comment by behrad** [comment]
You can serve your static dist by sth like Nginx to see that if this is really a 404 Not Found problem which built-in node server is swallowing it by sending text/html content I guess.
If yes, it should be related to https://github.com/DaftMonk/generator-angular-fullstack/issues/421#issuecomment-73580925
