### ISSUE TITLE
Bootstrap UI Components don't work

### ISSUE THREAD

**Issue by Nolanus** [DaftMonk/generator-angular-fullstack#703]
I just created 3 fresh projects using angular-fullstack generator and all suffer from non working bootstrap components. No other changes have been applied to any files (running Windows 7, nodeJs v0.10.32)
My generator configuration:
```
# Client

? What would you like to write scripts with?: JavaScript
? What would you like to write markup with?: HTML
? What would you like to write stylesheets with?: Sass
? What Angular router would you like to use?: uiRouter
? Would you like to include Bootstrap?: Yes
? Would you like to include UI Bootstrap?: Yes

# Server

? Would you like to use mongoDB with Mongoose for data modeling?: Yes
? Would you scaffold out an authentication boilerplate?: Yes
? Would you like to include additional oAuth strategies?: Google
? Would you like to use socket.io?: Yes
```
Another time I did not use Mongoose and I tried without Sass.

The non-working can easily be seen when hovering over the List at the bottom, which should bring up a tooltip. Adding other bootstrap components to the page does not work either.

**Comment by Awk34** [comment]
Seems to be working ATM
