### ISSUE TITLE
Best practice how to provide a config variable into javascript from a process environment.

### ISSUE THREAD

**Issue by azachar** [DaftMonk/generator-angular-fullstack#706]
Hello All!
I run into an interesting dilemma, how to provide an environment based configuration variable into a client javascript from a server process environment.

In my case I want to set stripe the publishable key from my hosting,  something like
 
```
export STRIPE_KEY=BLA
```

Then after some magic I expect to be able to use this key in my client javascript
```
Stripe.setPublishableKey('<STRIPE_KEY>');
```

Is there any good practice?

Initially I thought it would be sufficient to the magic with grunt replace but this is not an option since I need to be able to deploy 1 build into 2 different environments (one staging and one production) without a code change.

Thank you for any suggestions.

Best regards,
Andrej

**Comment by Awk34** [comment]
Feel free to open another issue if you still have questions

**Comment by elis** [comment]
Any tips on creating 'client' configuration inside /config/environment/ that will be used via grunt in the angular app?

**Comment by Awk34** [comment]
@elis does [this](https://github.com/DaftMonk/generator-angular-fullstack/issues/1227) discussion help?

**Comment by elis** [comment]
Actually I was looking for something that could have end dependent variable
not necessarily API keys, but rather API prefix, or other 'non secret'
configuration.

**Comment by azachar** [comment]
In the end of the day I made a simple grunt task that does  find and replace. All other solutions were just too complicated.

**Comment by jrogatis** [comment]
I know thats a old question but is for some reason wrong use the dotenv pagkage at client side ?
