### ISSUE TITLE
Error sass when build mode product

### ISSUE THREAD

**Issue by PhucPM** [DaftMonk/generator-angular-fullstack#710]
Hello!
When I build the application mode (production) but it is an error as below. Hope you help me solve direction.
p / s: I tried the url of the file refining of Bootstrap but not sass.
```console
* Error
Error: File to import not found or unreadable: bootstrap-sass-official/vendor/assets/stylesheets/bootstrap/
	Load paths:
	  on line 4 of app.scss

1: $icon-font-path: "/bower_components/bootstrap-sass-official/vendor/assets/fonts/bootstrap/";
2: $fa-font-path: "/bower_components/font-awesome/fonts";
```
* File app.scss
```scss
$icon-font-path: "/bower_components/bootstrap-sass-official/vendor/assets/fonts/bootstrap/";
$fa-font-path: "/bower_components/font-awesome/fonts";

@import 'bootstrap-sass-official/vendor/assets/stylesheets/bootstrap';
@import 'font-awesome/scss/font-awesome';
```

**Comment by jwhitmarsh** [comment]
@PhucPM I'm having the same issue, did you get anywhere with this in the end?

**Comment by timv2** [comment]
lines in the scss should be

$icon-font-path: "../bower_components/bootstrap-sass-official/vendor/assets/fonts/bootstrap/";
$fa-font-path: "../bower_components/font-awesome/fonts";

@import '../bower_components/bootstrap-sass-official/vendor/assets/stylesheets/bootstrap';
@import '../bower_components/font-awesome/scss/font-awesome';

**Comment by jwhitmarsh** [comment]
Thanks @timv2 that's working now :)
