### ISSUE TITLE
img tag in jade, when compiled it changes it source name

### ISSUE THREAD

**Issue by nschurmann** [DaftMonk/generator-angular-fullstack#719]
Hey guys, i have a image tag in a jade template, when running with `grunt serve` works smooth. But when i make a `grunt build:dist` it changes the name of this images and, of course, it will never find them.

How can i make sure that, if the name of the images changes, the routes in the image tag of the jade templates also changes?

**Comment by Awk34** [comment]
This seems to be working. Open the issue back up if you feel otherwise.
