### ISSUE TITLE
Socket Export

### ISSUE THREAD

**Issue by xeroxoid** [DaftMonk/generator-angular-fullstack#721]
I think that exporting socket out of socket has the following problem:

```javascript
.controller('SomeCtrl', function ($scope, $http, socket, $window) {
 .....
 socket.on(.....) //this will not work obviously
 ....
}
```

the working code would be more like:
```javascript
 socket.socket.on(.....) //this will work but looks like crap no?
```

More a 'keepin it clean' issue I suppose, OR am I missing something bigger?

**Comment by Awk34** [comment]
This is because `socket` in this instance is the front-end Socket.io Angular service from `socket.service.js`, which contains a client instance of Socket.io.
