### ISSUE TITLE
Using angular-fullstack only for the front end

### ISSUE THREAD

**Issue by kosz** [DaftMonk/generator-angular-fullstack#724]
This could sound silly at first, but due to the way the code is organized in this project, I would much rather prefer using it's Front End generators, rather than the traditional standalone generators from the generator-angular project. 

Since generator-angular-fullstack comes with backend MEAN stack generators, it's not ideal to be used with other technologies, Rails/Java/etc ...

However I would very much like to use this generator in my Rails and Java projects. Have you ever considered providing an alternative to use the generator without a back end ?

**Comment by Awk34** [comment]
This doesn't really make sense for a "Full-stack" generator. If you like only the front end, it should be easy enough to just not use the generated back-end.
