### ISSUE TITLE
grunt build and grunt serve:dist on Windows generates GET 404 errors.

### ISSUE THREAD

**Issue by Svenskunganka** [DaftMonk/generator-angular-fullstack#732]
When running `grunt build` or `grunt serve:dist` on Windows and accessing the project through localhost:9000 or the project in production the browser console and command prompt spits out 404 not found.

Output of Command Prompt:
```
GET /app/main/main.controller.js 404 7ms
GET /app/main/main.js 404 3ms
GET /app/rules/rules.controller.js 404 4ms
GET /app/rules/rules.js 404 3ms
GET /app/test/test.controller.js 404 3ms
GET /app/test/test.js 404 2ms
GET /components/modal/modal.service.js 404 2ms
GET /components/navbar/navbar.controller.js 404 2ms
```

The project works perfectly fine even though 404 Not Found is logged. This only happens when built on Windows. Tested on OS X and Ubuntu and no 404 Not Found is logged there.

**Comment by Awk34** [comment]
updated versions of the generator include a few ways of ensuring LF line endings

**Comment by dolanmiu** [comment]
What about existing projects? Would I have to re-generate the project, and copy source files across?

**Comment by kingcody** [comment]
Here is one of the changes: https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/.gitattributes

And here is another that might help: https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/.editorconfig

You may already have the `.editorconfig` but `.gitattributes` should enforce `LF` when commiting.

**Comment by dolanmiu** [comment]
So what do I do, just change my ```.gitattributes``` and add a ```.editorconfig``` file? (I do not have an ```.editorconfig```

**Comment by kingcody** [comment]
That would be good to start with. You can also use the `dos2unix` tool to recursively make the changes.

**Comment by dolanmiu** [comment]
Would I have to use ```dos2unix``` every time I crate a new file, and every time before a build? That is so cumbersome! There MUST be a better way

This right: http://sourceforge.net/projects/dos2unix/

**Comment by kingcody** [comment]
You would use `dos2unix` one time to ensure all your files are currently using `LF`, however after that, git should correct any files that you add or modify.

**Comment by hcbelias** [comment]
I'm having this issue in version 3.6.1.  Which release contains this fix?
