### ISSUE TITLE
Asynchronous Socket Authentication

### ISSUE THREAD

**Issue by stephengardner** [DaftMonk/generator-angular-fullstack#738]
Any plan to add asynchronous socket authentication?
If I log-in asynchronously, it doesn't look like my socket is going to be authenticated, since in socket.service that handshake only works when the socket first opens up.  However, if I log in, and then refresh the page, all goes well.

But I very well may want my socket open even when I'm un-authenticated.
If I want to see all the "Things" update in real-time even when I'm un-authenticated, is there a way to do this and have other requests necessitate authentication on the same socket?

**Comment by audrummer15** [comment]
+1

**Comment by chinnichaitanya** [comment]
Related to https://github.com/DaftMonk/generator-angular-fullstack/issues/690
