### ISSUE TITLE
when I attempt to connect from android application :GET /socket.io/?EIO=3&transport=polling 200 4ms

### ISSUE THREAD

**Issue by letroll** [DaftMonk/generator-angular-fullstack#740]
Hello,

when I attempt to connect from android application to socket.io server, all I see in console is :GET /socket.io/?EIO=3&transport=polling 200 4ms

but the application is not connecting.

Can you help me please?

**Comment by victorhugoviiii** [comment]
Hello,
i am getting de same Error
GET /socket.io/?EIO=3&transport=polling 200 4ms

I generated a project with angular fullstack, sockectio on browser work good,
but i tried to add adroid aplicacion chat 
https://github.com/nkzawa/socket.io-android-chat
not work server is showing "GET /socket.io/?EIO=3&transport=polling 200 4ms" every time
someone can help me?
Thanks

**Comment by Awk34** [comment]
`200` status code is the `OK` status, not an error. Look here for more info on socket.io debugging: http://socket.io/docs/logging-and-debugging/
