### ISSUE TITLE
How to remove old openshift setup

### ISSUE THREAD

**Issue by simonh1000** [DaftMonk/generator-angular-fullstack#743]
I've changed the name of my openshift app, but every time I use `grunt buildcontrol:openshift` it still points to the old version. I've tried manually changing files in .git and running `yo angular-fullstack:openshift` again, but it still keeps looking for my old destination. What do I need to delete to start afresh?

**Comment by shawnzam** [comment]
I think deleting the .git folder in /dist should do it.
