### ISSUE TITLE
User not in session

### ISSUE THREAD

**Issue by gpessa** [DaftMonk/generator-angular-fullstack#749]
So, i want to add to the current logged user tre credential for a new account (Withings). So the idea is that a user that is logged in can also add other way to make the login by using WIthings or twitter or facebook.

Those are my route:

```
router
.get('/', passport.authorize('withings', { 
    failureRedirect: '/'
}))

.get('/callback', passport.authorize('withings', {
    successRedirect : '/settings',
    failureRedirect : '/'
}));
```

and this the callbacks implementation :

```
passport.use(new WithingsStrategy({
    consumerKey: config.withings.clientID,
    consumerSecret: config.withings.clientSecret,
    callbackURL: config.withings.callbackURL,
    passReqToCallback: true
  },
  function(req, token, tokenSecret, profile, done) {

    console.log('user' + req.user);

    return done(null, null);

  }
));
```

the point is that when i get back to the function, even if i was logged the req.user is always undefined.

Do someone have an idea? I read that you need a couple of function like deserializeUser and serializeUser but they are never called.

Ideas? I'm new on this kind of things and after 3-4 night is getting frustrated :(

PS: this is my configuration

```
  app.set('views', config.root + '/server/views');
  app.engine('html', require('ejs').renderFile);
  app.set('view engine', 'html');
  app.use(compression());
  app.use(bodyParser.urlencoded({ extended: false }));
  app.use(bodyParser.json());
  app.use(methodOverride());
  app.use(cookieParser());
  app.use(passport.initialize());
  app.use(passport.session()); //persistent login session




  // Persist sessions with mongoStore
  // We need to enable sessions for passport twitter because its an oauth 1.0 strategy
  app.use(session({
    secret: config.secrets.session,
    resave: true,
    saveUninitialized: true,
    store: new mongoStore({ mongoose_connection: mongoose.connection })
  }));

  if ('production' === env) {
    app.use(favicon(path.join(config.root, 'public', 'favicon.ico')));
    app.use(express.static(path.join(config.root, 'public')));
    app.set('appPath', config.root + '/public');
    app.use(morgan('dev'));
  }

  if ('development' === env || 'test' === env) {
    app.use(require('connect-livereload')());
    app.use(express.static(path.join(config.root, '.tmp')));
    app.use(express.static(path.join(config.root, 'client')));
    app.set('appPath', 'client');
    app.use(morgan('dev'));
    app.use(errorHandler()); // Error handler - has to be last
  }
```

**Comment by joachimroeleveld** [comment]
I have the exact same problem!

I think it has to do something with the folder structure.. no idea what is causing it however.

**Comment by gardner** [comment]
It seems as if the generator is creating different code now. If I understand gpessa correctly then I am experiencing the same issue. When authorized via facebook strategy, the frontend does not ever have a token set. This seems to be due to the use of ``successRedirect`` which causes the middleware never to call ``auth.setTokenCookie()``. I removed ``successRedirect`` and handle it in ``auth.setTokenCookie()`` now.

**Comment by Awk34** [comment]
see #1028
