### ISSUE TITLE
Express global exception handler

### ISSUE THREAD

**Issue by Toub** [DaftMonk/generator-angular-fullstack#750]
In case of uncaught exception in Express, Express server crashes.
What about catching and logging uncaught exceptions in app.js?

    // catch global exceptions
    process.on('uncaughtException', function (err) {
        console.log('Caught exception: ',  err);
    });

**Comment by Awk34** [comment]
Automatically catching and absorbing all uncaught exceptions is a bad practice IMO. If your app wants to crash, you should let it crash. If you don't let it crash, and instead just eat the error, it's likely that your app will be put into an unknown/unrecoverable state.

The preferred prevention mechanism for app crashes is to use a process monitoring service like `forever` to automatically restart your app. That way the app can re-bootstrap itself and ensures that you know what its state is. You could also grab uncaught exceptions and add them to some persistent logging service, before throwing it on through.
