### ISSUE TITLE
Default Update controller should use _.extend instead of _.merge

### ISSUE THREAD

**Issue by balmasi** [DaftMonk/generator-angular-fullstack#752]
Lets say you have an array such as 
```
 {
     someProperty:
       [ 
         {  _id: 1,
            message: 'text1' 
         },
         {  _id: 2,
            message: 'text2'
         }
       ]
}
```
and you want to add ``` { _id: 3, message: 'text3' } ``` using the **UPDATE** route. It has been my experience that **_.merge** sets this  to
```
 {
     someProperty:
       [ 
         {  _id: 1,
            message: 'text1' 
         },
         {  _id: 1,
            message: 'text1' 
         },
         {  _id: 1,
            message: 'text1' 
         },
       ]
}
```
whereas the expected behaviour is from **_.extend** or **_.assign** which is 
```
 {
     someProperty:
       [ 
         {  _id: 1,
            message: 'text1' 
         },
         {  _id: 2,
            message: 'text2' 
         },
         {  _id: 3,
            message: 'text3' 
         },
       ]
}
```

**Comment by joelkelly** [comment]
Thanks.  This fixed an issue for me that was driving me up the wall.

**Comment by georgschlenkhoff** [comment]
+1 this is definitely a PR. was annoyed by same thing today.

**Comment by georgschlenkhoff** [comment]
Current lodash syntax is _.assign()

**Comment by ABCDEline** [comment]
This bug is very annoying... Thanks @balmasi !

**Comment by bartbaas** [comment]
+1

 Noticed the same today for ObjectId refs and populate() hooks. @balmasi: thanks a lot

**Comment by Awk34** [comment]
Closing as HTTP PUT isn't really an update, but a replace. There are plans to support HTTP PATCH.
