### ISSUE TITLE
added things container in another html file and use ng-include

### ISSUE THREAD

**Issue by yabasha** [DaftMonk/generator-angular-fullstack#753]
Hi Guys,

I removed things container from main.html to external.html file, and I used `<div ng-include="external.html"></div>` in main.html

The problem is that thing form stopped from working when I used `ng-include`, and when I put the container of things back in main.html it works, can any one explain that for me? is it bug?

Thanx,

**Comment by Albizures3601** [comment]
try <div ng-include=' "external.html" '>

**Comment by Albizures3601** [comment]
try ``` <div ng-include=' "external.html" '> ```

**Comment by Awk34** [comment]
Might need to transclude
