### ISSUE TITLE
Naught + grunt-express-server = ?

### ISSUE THREAD

**Issue by xeroxoid** [DaftMonk/generator-angular-fullstack#759]
Hi,

I had gotten naught to work fine with my app but realised that because the app starts via "node /dist/app.js" some stuff (such as the local.env.js) are not loaded. I don't see another way of utilising naught that way, of adding/loading the file at the beginning of app.js, but it seems dodgy and I am not sure if I will still miss something else.

I have already posted a question here: https://github.com/andrewrk/naught/issues/69

How would one go around that? I need some basic clustering/rolling update mechanism and I don't want to go the nginx way yet... Any ideas would be much appreciated!

Thanks!

**Comment by Awk34** [comment]
Seems like this is more of a question for that repo, not this one, yes?
