### ISSUE TITLE
Footer should be a component

### ISSUE THREAD

**Issue by caulagi** [DaftMonk/generator-angular-fullstack#762]
It is common for websites to have a footer with About, Privacy, Contact.  Right now, the footer seems to be part of 'main' app.  Instead, is it a good idea to have a footer component similar to navbar component with these illustrative pages?  Are you open to a PR for this feature?

**Comment by Abdizriel** [comment]
I agree with you. I have make footer as component in my project and it's usefull.

**Comment by kingcody** [comment]
I think that would be a great idea @caulagi. :+1:

**Comment by Awk34** [comment]
Closed with cf298a7
