### ISSUE TITLE
grunt:build fails on imagemin task

### ISSUE THREAD

**Issue by inicio** [DaftMonk/generator-angular-fullstack#765]
From a fresh build out of the generator and subsequent call to 'grunt-build' I'm getting this error: 

    Running "concurrent:dist" (concurrent) task
        Warning: Loading "imagemin.js" tasks...ERROR
        >> Error: Cannot find module 'imagemin-gifsicle'
        Warning: Task "imagemin" failed. Use --force to continue.
    
        Aborted due to warnings.
    
    
        Execution Time (2015-01-02 23:53:12 UTC)
        loading tasks  2.2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
        Total 2.2s Use --force to continue.
        
            Aborted due to warnings.

Removing the imagemin task will allow me to build the project successfully (but without the image directory). I've troubleshooted the problem by installing the dependency manually, using other versions of npm, and clearing npm's cache, but these attempts do not seem to fix the problem. 

Might be similar to the error documented here (https://github.com/npm/npm/issues/6051). Though I've followed all the suggestions without success.

**Comment by bappy004** [comment]
+1. same here

**Comment by wengcd** [comment]
try this
```bash
npm install grunt-contrib-imagemin
```

**Comment by regreceive** [comment]
Good!!! @wengcd 
Suggesting change "grunt-contrib-imagemin": "~0.9.2" to package.json

**Comment by tcrosen** [comment]
Confirming `grunt-contrib-imagemin` version ~`0.9.2` works.

**Comment by aratin** [comment]
Working for me also  thanks..

**Comment by Awk34** [comment]
this package has been updated in canary
