### ISSUE TITLE
coffeescript option does not translate server/api/*.js

### ISSUE THREAD

**Issue by svenwoldt** [DaftMonk/generator-angular-fullstack#768]
If I generate a project based on coffscript... it does so in the client but not on the server side...
Is it possible to also have this option:

yo angular-fullstack:endpoint message --coffee

and it then creates that endpoint in .coffee
Many thanks for the best generator available ^^
Sven

**Comment by rriemann** [comment]
Have a look at issue #92! I think this is a dublicate.

**Comment by speedingdeer** [comment]
me too
