### ISSUE TITLE
Generator tests location?

### ISSUE THREAD

**Issue by ianjohnmadrid** [DaftMonk/generator-angular-fullstack#769]
Hi there,

the generator seems to create the tests at the same time as creating i.e a controller / endpoint etc.

Wanting to write TDD code, I normally place my tests in /tests for example, so I don't need to think about the structure of anything before writing my first failed test.

Is there a way to change this behaviour, or is this actually a better way ?

I was using a very old version before of the generator and I believe there was a test directory separated into client and server for all specs...  Has this been abandoned ?

Thanks

**Comment by JaKXz** [comment]
Hi @ianjohnmadrid, apologies for the delayed response. If you look at the [readme](https://github.com/DaftMonk/generator-angular-fullstack#project-structure) you'll note the new structure which keeps all files to do with a component together.
