### ISSUE TITLE
How to update an existing project?

### ISSUE THREAD

**Issue by softBarbarian** [DaftMonk/generator-angular-fullstack#772]
How does one update an existing project to next release?
What is the best approach?
Is it as simple as updating the generator with npm update and then running grunt build?

**Comment by dancancro** [comment]
This question was asked [before](https://github.com/DaftMonk/generator-angular-fullstack/issues/521).  The answer was to rerun the generator and prepare for overwrites or bring things in one by one.

**Comment by softBarbarian** [comment]
Got it thanks.
