### ISSUE TITLE
grunt build won't move videos to /dist

### ISSUE THREAD

**Issue by HarrisRobin** [DaftMonk/generator-angular-fullstack#777]
I have tried adding videos (.webm) to my assets in images or by creating a new folder in assets called videos or media but despite what i do, building the project to production does not actually include the video. How do I get past this ?

Here's the app
https://projectsju.herokuapp.com/

Thanks ,
Harris

**Comment by rommelxcastro** [comment]
take a look a t the copy section in your grunt file

**Comment by thgil** [comment]
I just ran into the same issue. I fixed it by adding `'assets/videos/**/*',` to the copy section as suggested above.
```
copy: {
      dist: {
        files: [{
          expand: true,
          dot: true,
          cwd: '<%= yeoman.client %>',
          dest: '<%= yeoman.dist %>/public',
          src: [
            '*.{ico,png,txt}',
            '.htaccess',
            'bower_components/**/*',
            'assets/images/{,*/}*.{webp}',
            'assets/videos/**/*',
            'assets/fonts/**/*',
            'index.html'
          ]
        }, {
...
```
