### ISSUE TITLE
Endpoint response based on the request

### ISSUE THREAD

**Issue by 21ronak** [DaftMonk/generator-angular-fullstack#778]
Is it possible for an endpoint to give different responses based on the request it receives ?

**Comment by rommelxcastro** [comment]
if request === something return something else

**Comment by andrewstuart** [comment]
If you want to inspect the request before sending your response, you can definitely do that.

For example,

```javascript
if(req.hello) {
  return res.send('Hello there');
} else if (req.goodbye) {
  return res.send('See ya later!');
}
```

Obviously, you can do much more complicated logic. The important thing is that when you're ready to send, you `res.send(whateverYouWant)`. I'd suggest checking out the examples in `/server/api/thing/`, specifically `thing.controller.js` for more complex examples.
