### ISSUE TITLE
Running "uglify:generated" (uglify) task takes a very long time.

### ISSUE THREAD

**Issue by genu** [DaftMonk/generator-angular-fullstack#788]
I'm not sure if its because my application is that big (it really isn't), but this task takes about 1 hour to run. Does this process all the bower components as well? How can I speed this up?

![screen shot 2015-01-21 at 1 09 36 pm](https://cloud.githubusercontent.com/assets/928780/5841929/d0e66cea-a16e-11e4-9e94-fdecef4c555f.png)

**Comment by genu** [comment]
Upon further investigation it seems that it runs so long because I'm using KendoUI in my project. That is I have all of the kendo js files inside of  components/kendo. My guess is that it is going through each of these and minifying?

I suppose the best solution to only include the JS files from kendo that I need?

**Comment by Konnigun** [comment]
@genu thanks for figuring out that it was Kendo. Was the same thing in my case, so what I did was moving `<script src="bower_components/kendo-ui-core/js/kendo.ui.core.min.js"></script>` from `<!-- build:js(.) scripts/vendor.js -->` section to `<!-- build:js({.tmp,app}) scripts/scripts.js -->` in my `index.html` file.   

So, before: 
```
<!-- build:js(.) scripts/vendor.js -->
<!-- bower:js -->
<script src="bower_components/jquery/dist/jquery.js"></script>
<script src="bower_components/angular/angular.js"></script>
...
<script src="bower_components/kendo-ui-core/js/kendo.ui.core.min.js"></script>
<!-- endbower -->
<!-- endbuild -->

<!-- build:js({.tmp,app}) scripts/scripts.js -->
<script src="scripts/app.js"></script>
<script src="scripts/factories/factories.js"></script>
<script src="scripts/services/services.js"></script>
<!-- endbuild -->
```

After:
```
<!-- build:js(.) scripts/vendor.js -->
<!-- bower:js -->
<script src="bower_components/jquery/dist/jquery.js"></script>
<script src="bower_components/angular/angular.js"></script>
...
<!-- endbower -->
<!-- endbuild -->

<!-- build:js({.tmp,app}) scripts/scripts.js -->
<script src="bower_components/kendo-ui-core/js/kendo.ui.core.min.js"></script>

<script src="scripts/app.js"></script>
<script src="scripts/factories/factories.js"></script>
<script src="scripts/services/services.js"></script>
<!-- endbuild -->
```
And it changed uglify time from 8 minutes to 20 seconds.

**Comment by Awk34** [comment]
I'm not sure what your best option is, but this isn't the place to ask.
