### ISSUE TITLE
duplicate key errors

### ISSUE THREAD

**Issue by chovy** [DaftMonk/generator-angular-fullstack#803]
Is there a good way to handle duplicate key errors?

They aren't surfaced and aren't related to form validation errors. So it seems we need another way to handle generic db errors.

**Comment by Awk34** [comment]
Are you talking about MongoDB? Because Mongo rejects duplicate indexes..

**Comment by anthonyettinger** [comment]
I mean if you put unique attribute. Mongo throws an error but the UI isn't handling it.

**Comment by Awk34** [comment]
I don't understand what you're getting at. Please provide an example

**Comment by anthonyettinger** [comment]
If my schema has `{ foo { type: String, unique: true } }` and then I try to post a duplicate item (foo is equal to a previous value in the collection), then the backend throws a Mongodb error, but the front-end doesn't have any code to handle it.

**Comment by Awk34** [comment]
Not sure what to tell you here. Handle it however you see fit: console.log, toast, dialog...
