### ISSUE TITLE
Question - Server side scripts

### ISSUE THREAD

**Issue by stramel** [DaftMonk/generator-angular-fullstack#809]
My apologies for putting a question in the issues, but I was unsure where to post this.

I have an application which needs to do some api polling on a daily basis through cron. I didn't know where I should organize these scripts into the existing folder structure. I'm assuming somewhere in the server folder, any suggestions?

**Comment by Awk34** [comment]
Maybe not even in the site folder, since it would be running completely out of the scope of what the generator produces, no?

**Comment by stramel** [comment]
The trouble I am having with keeping it outside of the site folder is that the script drives most of the content for the overall site and is thus related to the site. Since it is out of scope of what the generator produces, would it make more sense to have a utility or scripts folder that resides in the root?

**Comment by Awk34** [comment]
Hmmm, that sounds more like it. I would then put a `scripts` folder in the root or in the `server` folder (make sure grunt tasks copy it properly). Can you explain a bit more on what your script is doing? Maybe you want to convert your script to a node script?

**Comment by stramel** [comment]
So the script will probably be a node script, that checks for updates, if an update is found starts a bunch of API requests then stores the data to Mongo.

**Comment by Awk34** [comment]
Okay, so this sounds like something that shouldn't be a `cron` job, but instead something in `server/app.js` like this:

```javascript
// Start server
server.listen(config.port, config.ip, function() {
    console.log('Express server listening on %d, in %s mode', config.port, app.get('env'));

    setInterval(function() {
        checkForUpdates();
    }, 3600000);  //every hour
});
```

**Comment by stramel** [comment]
@Awk34 That's a good point, hadn't thought of doing it like that. Would I just create a service.js file for it, similar to auth? Or keep a scripts folder? BTW, I appreciate your suggestions and thoughts.

**Comment by Awk34** [comment]
It's up to you. I would suggest making a `scripts` folder inside of the `server` folder (I updated my previous comment to reflect that), but that's up to you. As long as you have a function in `myScript.js` as `exports.checkForUpdates = function() {}` my suggested approach will work. Then stick whatever you need into that function.

Glad to help!
