### ISSUE TITLE
Cannot use canary branch

### ISSUE THREAD

**Issue by khwerhahn** [DaftMonk/generator-angular-fullstack#812]
Hey,

trying to use the canary branch of the generator, but I cannot get it to work. I get a 404
```
sudo npm install -g https://github.com/DaftMonk/generator-angular-fullstack.git@canary
```

**Comment by gaboesquivel** [comment]
AFAIK you cannot specify branches with npm, just tarballs, versions, tags https://docs.npmjs.com/cli/install

you can use [npm link](https://docs.npmjs.com/cli/link)
```
git clone -b canary git@github.com:DaftMonk/generator-angular-fullstack.git
cd generator-angular-fullstack
npm link
```
and where you want to run the generator do
```
npm link generator-angular-fullstack
```

**Comment by khwerhahn** [comment]
Thx, but I don't really know how this 'advanced' git stuff works...

I have installed generator-angular-fullstack gobally.
Now I tried:
```
git clone -b canary git@github.com:DaftMonk/generator-angular-fullstack.git   
Cloning into 'generator-angular-fullstack'...
ssh: connect to host github.com port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Not sure what to do with that info....

**Comment by gaboesquivel** [comment]
try https://github.com/DaftMonk/generator-angular-fullstack.git instead

**Comment by khwerhahn** [comment]
Perfect thank you that worked
