### ISSUE TITLE
What's the point of /server/config/local.env.sample.js?

### ISSUE THREAD

**Issue by honkskillet** [DaftMonk/generator-angular-fullstack#814]
What's the point of /server/config/local.env.sample.js?  It's essentially identical to local.env.js and it doesn't actually contain any samples id/secrets.  Plus, it isn't listed in the gitignore file, so it seems like it might easily be a spot where a secret is accidentally pasted then broadcast to the world.

**Comment by dotch** [comment]
Since the local.env.js is on .gitignore, when someone checks out your project's repository, he will not have it. So he has to create his own. The local.env.sample.js helps him create one.

**Comment by honkskillet** [comment]
Ah. OK.  Thank you.
