### ISSUE TITLE
Can't use modules

### ISSUE THREAD

**Issue by alihalabyah** [DaftMonk/generator-angular-fullstack#816]
In the router file and whenever you try to use/extend another module the stateProvider will become unknown:

In this example I'm trying to use ngMaterial module.

```
'use strict';

angular.module('testApp', ['ngMaterial'])
  .config(function ($stateProvider) {
    $stateProvider
      .state('test', {
        url: '/test',
        templateUrl: 'app/test/test.html',
        controller: 'TestCtrl'
      });
  });

```

This will be printed in the console:

```
Error: [$injector:unpr] Unknown provider: $stateProvider
```

**Comment by Awk34** [comment]
First of all, you shouldn't bee including `ngMaterial` in your router module.

Did you initialize the project using `ui-router`?

**Comment by alihalabyah** [comment]
Yes, thank you this was solved :)

**Comment by honkskillet** [comment]
@alihalabyah Please close issue.
