### ISSUE TITLE
Grunt build overrides bower configuration

### ISSUE THREAD

**Issue by Toub** [DaftMonk/generator-angular-fullstack#824]
The current grunt build ignore some bower resources:

    // Automatically inject Bower components into the app
    wiredep: {
      target: {
        src: '<%= yeoman.client %>/index.html',
        ignorePath: '<%= yeoman.client %>/',
        exclude: [/bootstrap-sass-official/, /bootstrap.js/, '/json3/', '/es5-shim/', /bootstrap.css/, /font-awesome.css/ ]
      }
    },

So if I want to include bootstrap.js to the application, I have to add the following line to index.html:

    <script src="bower_components/bootstrap/dist/js/bootstrap.js"></script>

It could be better to remove the grunt "exclusion" and override bootstrap bower.json in our project bower.json file:

    "overrides": {
        "bootstrap": {
            "main": [ ]
        }
    }

so if I want to include bootstrap.js, I simply update the bower ovverides to:

    "overrides": {
        "bootstrap": {
            "main": ["dist/js/bootstrap.js"]
        }
    }

**Comment by DaftMonk** [comment]
That's how wiredep intended exclude to be used, and I think thats the best place to keep that wiredep specific build info.
