### ISSUE TITLE
Recommendations for sharing code between client/server

### ISSUE THREAD

**Issue by beanhedge** [DaftMonk/generator-angular-fullstack#826]
What are your recommendations for sharing a lot of code between client and server?  I'm developing a game and I would like to share the game logic between the client (for gameplay) and server (for validation).  A lot of people recommend using browserify for this generator uses bower.

**Comment by nottinhill** [comment]
I am pretty sure this question is out of context for this project.

**Comment by tbehrsin** [comment]
@nottinhill Actually very much in context... this is the top link in google for the generator. The generator is opinionated in that it decides that some code lives on the client, some on the server. There should be a 'common' directory, that is by default included in the grunt build. Currently we have to include, potentially ES6 code, by running through babel and importing from the client modules into the server modules. The generator could handle production of a common directory shared by both layers when creating the Gruntfile.

**Comment by amejiarosario** [comment]
@beanhedge @tbehrsin I'm just wondering... What are some common use cases to share code between client and servers?

**Comment by tbehrsin** [comment]
@amejiarosario Anything that they both need to use. Validation code is one. Model definitions could be another (but this is a more complex case, as you'd need to wrap mongoose schemas). I myself am dealing with a case that I need both builder/parser functionality in three tiers of my app, each tier can build and parse (it is more than just client-server). Look at any large Java or .NET project and you'll find one or more shared libraries that are specific to the platform (i.e. you wouldn't publish on maven/nu/npm/etc.)
