### ISSUE TITLE
Very slow when port forwarding mongodb

### ISSUE THREAD

**Issue by jitowix** [DaftMonk/generator-angular-fullstack#831]
Not sure if I'm doing something wrong but the project is extremely slow when I host the database on a remote server (aws) and use port forwarding to connect to it from my computer.
It runs fine when mongodb is running locally. Everything is also fine in production (aws too), so the issue comes from port forwarding I guess. The page takes about 10 times longer to load.

Can somebody help me?

**Comment by jitowix** [comment]
It was because of express sessions. I've disabled them in express.js and now it's much better (there was a db query for each loaded file)

**Comment by digitalmint00** [comment]
Thanks for the follow up
