### ISSUE TITLE
Grunt build doesn't work

### ISSUE THREAD

**Issue by gbourgneuf** [DaftMonk/generator-angular-fullstack#838]
I tried to generate the production version of my application running "grunt" but without any success.

What do I need to modify into the GruntFile to be able to generate my app ?

Currently I have the following error:
Running "wiredep:target" (wiredep) task
Warning: Cannot read property 'main' of undefined Use --force to continue.

Can I generate the gruntfile automatically to fit with my project ?

**Comment by gbourgneuf** [comment]
This error is solved.
It was due to the bower dependency Animate.css.
I resolved it using "bower install animate-css --save"

but now I have the new error:
>> No "cssmin" targets found.
Warning: Task "cssmin" failed. Use --force to continue.

**Comment by digitalmint00** [comment]
Might be a dumb thought but-- did you $ bower install && npm install ? Is a
file/folder permission precluding the install process from completing
successfully or do they complete without errors?

**Comment by gbourgneuf** [comment]
Yes I did.

Ok I find it : it was because I deleted line like this  in my file index.html


But another question is:
- I added some folders into my client directory and each folder have child folders or files (js / cs / ...) how can I include them into my dist build ?

**Comment by DaftMonk** [comment]
All scripts in the `app` and `components` folders should get loaded into the the index.html through the grunt injector task. That said, if you manually include a script in or css inside the html build blocks (but outside of the injector blocks) they should also be included in the build.

**Comment by Darksoulsong** [comment]
@DaftMonk Can you explain a little bit more? I just downloaded the generator and I can't build because of this very same problem.

Here's the verbose log of Grunt

	c:\fakepath\test>grunt build
	Running "clean:dist" (clean) task
	>> 12 paths cleaned.

	Running "wiredep:app" (wiredep) task

	Running "wiredep:test" (wiredep) task

	Running "wiredep:sass" (wiredep) task

	Running "useminPrepare:html" (useminPrepare) task
	Configuration changed for concat, uglify, cssmin

	Running "concurrent:dist" (concurrent) task

	Running "svgmin:dist" (svgmin) task
	Total saved: 0 B

	Done, without errors.


	Execution Time (2015-09-08 10:06:29 UTC)
	loading tasks          9ms  ███ 6%
	loading grunt-svgmin  97ms  ██████████████████████████ 63%
	svgmin:dist           47ms  █████████████ 31%
	Total 154ms

	Running "imagemin:dist" (imagemin) task
	Minified 1 image (saved 5 kB)

	Done, without errors.


	Execution Time (2015-09-08 10:06:29 UTC)
	loading tasks                     9ms  █ 1%
	loading grunt-contrib-imagemin  488ms  ██████████████████████ 70%
	imagemin:dist                   196ms  █████████ 28%
	Total 694ms

	Running "compass:dist" (compass) task
	directory .tmp/styles
	        write .tmp/styles/main.css (0.933s)

	Done, without errors.


	Execution Time (2015-09-08 10:06:29 UTC)
	loading grunt-contrib-compass  41ms  █ 2%
	compass:dist                   2.5s  ███████████████████████████████ 98%
	Total 2.5s

	Running "autoprefixer:server" (autoprefixer) task
	Autoprefixer's process() method is deprecated and will removed in next major rel
	ease. Use postcss([autoprefixer]).process() instead
	File .tmp/styles/main.css created.

	Running "autoprefixer:dist" (autoprefixer) task
	Autoprefixer's process() method is deprecated and will removed in next major rel
	ease. Use postcss([autoprefixer]).process() instead
	File .tmp/styles/main.css created.

	Running "ngtemplates:dist" (ngtemplates) task
	File .tmp/templateCache.js created.
	>> Usemin has not created uglify.generated yet!

	Running "concat:generated" (concat) task

	Running "ngAnnotate:dist" (ngAnnotate) task
	>> No files provided to the ngAnnotate task.

	Running "copy:dist" (copy) task
	Copied 12 files

	Running "cdnify:dist" (cdnify) task
	Going through dist/404.html, dist/area1.html, dist/area2.html, dist/area3.html t
	o update script refs
	✔ bower_components/angular/angular.js changed to //ajax.googleapis.com/ajax/libs
	/angularjs/1.4.4/angular.min.js
	✔ bower_components/angular-animate/angular-animate.js changed to //ajax.googleap
	is.com/ajax/libs/angularjs/1.4.4/angular-animate.min.js
	✔ bower_components/angular-cookies/angular-cookies.js changed to //ajax.googleap
	is.com/ajax/libs/angularjs/1.4.4/angular-cookies.min.js
	✔ bower_components/angular-resource/angular-resource.js changed to //ajax.google
	apis.com/ajax/libs/angularjs/1.4.4/angular-resource.min.js
	✔ bower_components/angular-route/angular-route.js changed to //ajax.googleapis.c
	om/ajax/libs/angularjs/1.4.4/angular-route.min.js
	✔ bower_components/angular-sanitize/angular-sanitize.js changed to //ajax.google
	apis.com/ajax/libs/angularjs/1.4.4/angular-sanitize.min.js
	✔ bower_components/angular-touch/angular-touch.js changed to //ajax.googleapis.c
	om/ajax/libs/angularjs/1.4.4/angular-touch.min.js
	✔ bower_components/angular/angular.js changed to //ajax.googleapis.com/ajax/libs
	/angularjs/1.4.4/angular.min.js
	✔ bower_components/angular-animate/angular-animate.js changed to //ajax.googleap
	is.com/ajax/libs/angularjs/1.4.4/angular-animate.min.js
	✔ bower_components/angular-cookies/angular-cookies.js changed to //ajax.googleap
	is.com/ajax/libs/angularjs/1.4.4/angular-cookies.min.js
	✔ bower_components/angular-resource/angular-resource.js changed to //ajax.google
	apis.com/ajax/libs/angularjs/1.4.4/angular-resource.min.js
	✔ bower_components/angular-route/angular-route.js changed to //ajax.googleapis.c
	om/ajax/libs/angularjs/1.4.4/angular-route.min.js
	✔ bower_components/angular-sanitize/angular-sanitize.js changed to //ajax.google
	apis.com/ajax/libs/angularjs/1.4.4/angular-sanitize.min.js
	✔ bower_components/angular-touch/angular-touch.js changed to //ajax.googleapis.c
	om/ajax/libs/angularjs/1.4.4/angular-touch.min.js
	✔ bower_components/angular/angular.js changed to //ajax.googleapis.com/ajax/libs
	/angularjs/1.4.4/angular.min.js
	✔ bower_components/angular-animate/angular-animate.js changed to //ajax.googleap
	is.com/ajax/libs/angularjs/1.4.4/angular-animate.min.js
	✔ bower_components/angular-cookies/angular-cookies.js changed to //ajax.googleap
	is.com/ajax/libs/angularjs/1.4.4/angular-cookies.min.js
	✔ bower_components/angular-resource/angular-resource.js changed to //ajax.google
	apis.com/ajax/libs/angularjs/1.4.4/angular-resource.min.js
	✔ bower_components/angular-route/angular-route.js changed to //ajax.googleapis.c
	om/ajax/libs/angularjs/1.4.4/angular-route.min.js
	✔ bower_components/angular-sanitize/angular-sanitize.js changed to //ajax.google
	apis.com/ajax/libs/angularjs/1.4.4/angular-sanitize.min.js
	✔ bower_components/angular-touch/angular-touch.js changed to //ajax.googleapis.c
	om/ajax/libs/angularjs/1.4.4/angular-touch.min.js
	✔ bower_components/angular/angular.js changed to //ajax.googleapis.com/ajax/libs
	/angularjs/1.4.4/angular.min.js
	✔ bower_components/angular-animate/angular-animate.js changed to //ajax.googleap
	is.com/ajax/libs/angularjs/1.4.4/angular-animate.min.js
	✔ bower_components/angular-cookies/angular-cookies.js changed to //ajax.googleap
	is.com/ajax/libs/angularjs/1.4.4/angular-cookies.min.js
	✔ bower_components/angular-resource/angular-resource.js changed to //ajax.google
	apis.com/ajax/libs/angularjs/1.4.4/angular-resource.min.js
	✔ bower_components/angular-route/angular-route.js changed to //ajax.googleapis.c
	om/ajax/libs/angularjs/1.4.4/angular-route.min.js
	✔ bower_components/angular-sanitize/angular-sanitize.js changed to //ajax.google
	apis.com/ajax/libs/angularjs/1.4.4/angular-sanitize.min.js
	✔ bower_components/angular-touch/angular-touch.js changed to //ajax.googleapis.c
	om/ajax/libs/angularjs/1.4.4/angular-touch.min.js
	>> No "cssmin" targets found.
	Warning: Task "cssmin" failed. Use --force to continue.

	Aborted due to warnings.


	Execution Time (2015-09-08 10:06:28 UTC)
	wiredep:app                   185ms  █ 2%
	concurrent:dist                  3s  ██████████ 30%
	loading grunt-autoprefixer    194ms  █ 2%
	autoprefixer:server           312ms  █ 3%
	loading grunt-google-cdn      735ms  ███ 7%
	cdnify:dist                    5.3s  █████████████████ 52%
	loading grunt-contrib-cssmin  110ms  █ 1%
	Total 10.3s


	c:\fakepath\test>

And here goes one of my app.html files (there are 3 of them and they are exactly the same):

  <!doctype html>
  <html>
    <head>
      <meta charset="utf-8">
      <title></title>
      <meta name="description" content="">
      <meta name="viewport" content="width=device-width">
      
      
      
      <link rel="stylesheet" href="bower_components/animate.css/animate.css" />
      
      
      
      <link rel="stylesheet" href="styles/main.css">
      
    </head>
    <body ng-app="testeApp">
      

      
      <div class="header">
        <div class="navbar navbar-default" role="navigation">
          <div class="container">
            <div class="navbar-header">

              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#js-navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>

              <a class="navbar-brand" href="#/">teste</a>
            </div>

            <div class="collapse navbar-collapse" id="js-navbar-collapse">

              <ul class="nav navbar-nav">
                <li class="active"><a href="#/">Home</a></li>
                <li><a ng-href="#/about">About</a></li>
                <li><a ng-href="#/">Contact</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <div class="container">
      <div ng-view=""></div>
      </div>

      <div class="footer">
        <div class="container">
          <p><span class="glyphicon glyphicon-heart"></span> from the Yeoman team</p>
        </div>
      </div>


      
       <script>
         !function(A,n,g,u,l,a,r){A.GoogleAnalyticsObject=l,A[l]=A[l]||function(){
         (A[l].q=A[l].q||[]).push(arguments)},A[l].l=+new Date,a=n.createElement(g),
         r=n.getElementsByTagName(g)[0],a.src=u,r.parentNode.insertBefore(a,r)
         }(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

         ga('create', 'UA-XXXXX-X');
         ga('send', 'pageview');
      </script>

      
      
      <script src="bower_components/jquery/dist/jquery.js"></script>
      <script src="bower_components/angular/angular.js"></script>
      <script src="bower_components/angular-animate/angular-animate.js"></script>
      <script src="bower_components/angular-cookies/angular-cookies.js"></script>
      <script src="bower_components/angular-resource/angular-resource.js"></script>
      <script src="bower_components/angular-route/angular-route.js"></script>
      <script src="bower_components/angular-sanitize/angular-sanitize.js"></script>
      <script src="bower_components/angular-touch/angular-touch.js"></script>
      <script src="bower_components/bootstrap-sass-official/assets/javascripts/bootstrap.js"></script>
      
      

          
          <script src="scripts/app.js"></script>
          <script src="scripts/controllers/main.js"></script>
          <script src="scripts/controllers/about.js"></script>
          
  </body>
  </html>

**Comment by Awk34** [comment]
@Darksoulsong do you have `grunt-cssmin` installed? Look for a directory named that inside your `node_modules` folder.

**Comment by Darksoulsong** [comment]
@Awk34 Yes, "grunt-contrib-cssmin".

**Comment by Awk34** [comment]
Hmm, you might not even need cssmin. try commenting it out from the build task for now.
