### ISSUE TITLE
How to push  informations to all clients except self.

### ISSUE THREAD

**Issue by mateutek** [DaftMonk/generator-angular-fullstack#844]
I would like to create notifications for all clients except the one who changed "Things".
I tried chaning the <code>syncUpdates</code>
by adding 
```javascript
socket.on(modelName+ ':notify', function (message){
    notifications.notify(message);
});
```

```javascript
notifyClients: function (modelName,message){
    socket.emit(modelName+':notify',message);
}
```

and adding to <code>main.controller.js</code>

```javascript
$scope.addThing = function () {
    if ($scope.newThing === '') {
        return;
    }
    $http.post('/api/things', { name: $scope.newThing });
    var message = Auth.getCurrentUser().name+' created new item: '+$scope.newThing;
    socket.notifyClients('thing', message);
    $scope.newThing = '';

 };
````
but i don't get anything out.

    notifications.notify(message)
is just  console.log(message);

**Comment by Awk34** [comment]
I think that on the server-side you would have to emit the message to each connected client individually, skipping the ID of the client that sent the message

**Comment by kingcody** [comment]
@mateutek something like this maybe?
```javascript
// server/config/socketio.js
...
// When the user connects.. perform this
function onConnect(socket) {
  socket.on('someAction', function() {
    // send event to all clients except sender
    socket.broadcast.emit('someEvent', 'some message or data');
  });
}
...
```

**Comment by lricoy** [comment]
+1 for the use of broadcast

**Comment by mateutek** [comment]
I will test it on the weekend, but i suppose it's still not what i am looking for.
Still learning angular so maybe i will come up with idea :)
