### ISSUE TITLE
service generator produces service named with lowerCase?

### ISSUE THREAD

**Issue by sedina** [DaftMonk/generator-angular-fullstack#850]
We started using angular-fullstack very recently and something that we realized is that the service and factory generator puts name on the service/factory with lowerCase.
While for instance the controller generator is naming the controller with UpperCase.

Is there a logical reason behind this behaviour or?
Is it possible to change/correct?

**Comment by kingcody** [comment]
I'd say it was because controllers are constructor functions and 'class' like. Also, the [angular guide for controllers](https://docs.angularjs.org/guide/controller) suggests doing it that way.
