### ISSUE TITLE
documentation needed

### ISSUE THREAD

**Issue by dezechristophe** [DaftMonk/generator-angular-fullstack#852]
I post this on stackoverflow.com http://stackoverflow.com/questions/28751792/how-to-deploy-yeoman-angular-fullstack-project
Can you help me ?

**Comment by kingcody** [comment]
The easiest thing to do, if you just wanted to serve your built project, would be to goto your `dist` folder and then serve it with `NODE_ENV=production npm start`.

**Comment by johnathontieman** [comment]
I would like to know this as well. I tried what kingcody suggested, but it didn't work (I got errors that the secret should be set, when it is set in the local.env.js file). The code builds, runs, and I can grunt serve and grunt serve:dist, and both work. So how can I take the dist/ folder and serve it outside of grunt? Or is the intended use that grunt actually serve the production site? Thanks!

**Comment by dezechristophe** [comment]
thanks really easy !
