### ISSUE TITLE
scope doesn't update after socket event

### ISSUE THREAD

**Issue by khwerhahn** [DaftMonk/generator-angular-fullstack#853]
For some reason the $scope doesn't get updated after a socket event. The socket works finde, I can log the data out if the socket event occurs, but the dom doesn't get updated. 

```javascript
angular.module('App')
  .controller('TransactionCtrl', function($scope, socket, Transaction) {
    $scope.transactions = [];

    Transaction.query(function(transactions){
       $scope.transactions = transactions;
       socket.syncUpdates('transaction', $scope.transactions);
    });
    
    
    $scope.$on('$destroy', function() {
      socket.unsyncUpdates('transaction');
    });

  });
```

```
<div class="row" ng-repeat="trx in transactions">
      <div class="col-sm-6">{{ trx.id }}</div>
</div>
```

**Comment by JaKXz** [comment]
Could you add your `Transaction` service code as well? I *think* if you're returning a promise from the service method you need to use the `.then` handler and pass your success and failure callbacks there.

**Comment by khwerhahn** [comment]
I had to to update the socket part fom ._id to .id since I'm using sequelize.
