### ISSUE TITLE
router load after errorhandler middleware

### ISSUE THREAD

**Issue by Daniel-Xu** [DaftMonk/generator-angular-fullstack#855]
```
require('./config/express')(app);
```

```
require('./routes')(app);
```

Configuration is put before router, and errorhandler middleware is in config module. 
So,  router will be after the errorhandler. Isn't it a problem?

**Comment by kingcody** [comment]
From my understanding, I believe you are correct. Here's how I have several of my projects laid out:
```javascript
// Configure Express
require('./config/express')(app);
// Define server routes
require('./routes')(app);
// Express error handling
require('./config/errors')(app);
```

From the [express error handling guide](http://expressjs.com/guide/error-handling.html):
> You define error-handling middleware last, after other app.use() and routes calls

**Comment by Daniel-Xu** [comment]
@kingcody should we pull request to change it? 

by the way, after authentication, the actual user object has been attached on the req.user object.

so there's no need to query database again in user.controller when creating a new user!!

**Comment by kingcody** [comment]
I think a small PR to cover that would be welcomed :smile:

--------------------------------------------------

> after authentication, the actual user object has been attached on the req.user object

That is correct.

> no need to query database again in user.controller when creating a new user

I don't believe that happens in `server/api/user/user.controller.js#create`.

However there is a 're-query' in `server/api/user/user.controller.js#me`, but I guess one could argue that its to get the profile sans `salt` and `hashedPassword`. Also there is a chance that middleware could modify the `req.user` object adding or changing data from what is in the db, so I guess it could be considered safer to get a fresh query (minus sensitive data).

**Comment by Daniel-Xu** [comment]
```
exports.changePassword = function(req, res, next) {
  var userId = req.user._id;
  var oldPass = String(req.body.oldPassword);
  var newPass = String(req.body.newPassword);

  User.findById(userId, function (err, user) {
    if(user.authenticate(oldPass)) {
      user.password = newPass;
      user.save(function(err) {
        if (err) return validationError(res, err);
        res.send(200);
      });
    } else {
      res.send(403);
    }
  });
};
```
@kingcody  Sorry, I was referring the change password method in user controller. There's no need to query database, because we don't need to get rid of the sensitive data.

but the second concern is convictive :smile_cat: , thank you very much.
