### ISSUE TITLE
Socket.io multiple connection of same client

### ISSUE THREAD

**Issue by gbourgneuf** [DaftMonk/generator-angular-fullstack#857]
Hi,

I'm currently facing an issue with Socket.io:

1. When a client connect to the server socket.address is 'undefined:undefined' because socket.handshake.address.address and socket.handshake.address.port don't exist (socket.address is like "127.0.0.1" with string directly not object

2. If my client (my browser on the same machine - cause I'm in development phase) refresh the page a new connection is created and all api sockets are registered again with the conclusion that when an event is emitted it is emitted many times (depending on a many times the page has been refreshed).

How to avoid the same client to be connected many times and avoiding many registration of socket events for the same client ?

Thanks in advance.

**Comment by Petro-Kashpurenko** [comment]
+1 UP

**Comment by georgeportillo** [comment]
This is also something I encountered

**Comment by javierbq** [comment]
+1 this drove me crazy! I just added logic to the front end so it would ignore repeated messages.

**Comment by bstanleycm** [comment]
Same problem here with #2.  I'm logging multiple emits from the server (seemingly based on the number of times a browser has been refreshed).

**Comment by kingcody** [comment]
See #490
