### ISSUE TITLE
How to prevent params injection? 

### ISSUE THREAD

**Issue by Daniel-Xu** [DaftMonk/generator-angular-fullstack#860]
``` 
exports.create = function (req, res, next) {
  var newUser = new User(req.body);
```

here we use req.body to create a new user, but what if I use curl to post a request with `{role: admin}` added to params, will this be a bug?  is there any whitelist mechanism in ExpressJS?

**Comment by equero** [comment]
If you have admin roles, you're fucked... But, to prevent human fails, you can make a security token system. 

The token is sent only when the user click a button ( for example, create account) and it uses the clock time (Still being an example) and ip adress to generate the token code.

Greetings

PD: You must create the validator in the backend too. Dont make it impossible or NSA cool stuff, rsa algorithm.... be logic

**Comment by Awk34** [comment]
If you look [here](https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/server/api/user(auth)/user.controller.js#L29), you'll see that `role` is always set to `user`.

**Comment by bwasnie1** [comment]
Or...you just create a new user with fixed data. For example:
```
var newUser = new User({
  email: req.body.email,
  password: req.body.password,
  username: req.body.username
});
```
