### ISSUE TITLE
JSHint ignoring jshintrc?

### ISSUE THREAD

**Issue by benjamincharity** [DaftMonk/generator-angular-fullstack#861]
I hesitated even posting this as I'm sure it's due to my set up rather than the project...but honestly I'm at a loss and hoping someone here has dealt with this..

JSHint seems to be ignoring my jshintrc.  I get errors for every constant possible despite them being included in the project specific jshintrc (I also tried creating a global jshintrc).

![screen shot 2015-03-02 at 7 15 06 am](https://cloud.githubusercontent.com/assets/270193/6440575/483c3c1e-c0ac-11e4-8bf6-bb81d0c7aca6.png)

![screen shot 2015-03-02 at 7 15 11 am](https://cloud.githubusercontent.com/assets/270193/6440571/430aee48-c0ac-11e4-8aa1-7315b7c20953.png)

Using JSHint has definitely benefited my code, but the constant errors are driving me mad. I've read through the jshint docs and it sure seems like there is almost nothing I could do to screw this up. Does anyone have any ideas of what I could check/change? Currently I'm using the unedited jshintrc that the project generates.

Thanks in advance!

**Comment by Awk34** [comment]
how about some more details on your specific setup?

**Comment by benjamincharity** [comment]
Thanks for the response @Awk34. 

I got some help from a fellow engineer who was able to help solve my issue.

My understanding was that JSHint would look for a `jshintrc` in the working directory and then on up to find any global `jshintrc`. But apparently the plugin that integrates JSHint into Vim overrides that behavior completely and _only_ uses it's own JSHint options file.

So for now I can edit that file while I try to figure out how to make the plugin respect repo specific JSHint options.

Thanks again for reaching out to help!
