### ISSUE TITLE
When starting build with node or nodemon torrent of 404s appears

### ISSUE THREAD

**Issue by nottinhill** [DaftMonk/generator-angular-fullstack#864]
On a fresh angular-fullstack install entering   

    $ nodemon dist/server/app.js

yields:

3 Mar 17:09:02 - [nodemon] app crashed - waiting for file changes before starting...
3 Mar 17:09:20 - [nodemon] restarting due to changes...
3 Mar 17:09:20 - [nodemon] starting `node dist/server/app.js`
Express server listening on 9000, in development mode
finished populating users
GET / 200 8ms
GET /bower_components/bootstrap/dist/css/bootstrap.css 304 13ms
GET /bower_components/font-awesome/css/font-awesome.css 304 4ms
GET /app/admin/admin.css 200 13ms - 35b
GET /app/account/login/login.css 200 13ms - 348b
GET /app/app.css 200 16ms
GET /app/main/main.css 200 13ms - 472b
GET /components/modal/modal.css 404 11ms
GET /bower_components/jquery/dist/jquery.js 304 5ms
GET /bower_components/angular-resource/angular-resource.js 304 3ms
GET /bower_components/angular/angular.js 304 4ms
GET /bower_components/angular-cookies/angular-cookies.js 304 3ms
GET /bower_components/angular-sanitize/angular-sanitize.js 304 3ms
GET /bower_components/angular-bootstrap/ui-bootstrap-tpls.js 304 3ms
GET /bower_components/lodash/dist/lodash.compat.js 304 2ms
GET /bower_components/angular-ui-router/release/angular-ui-router.js 304 5ms
GET /bower_components/angular-socket-io/socket.js 304 6ms
GET /app/account/login/login.controller.js 200 6ms - 686b
GET /app/account/account.js 200 6ms - 574b
GET /app/app.js 200 10ms
GET /app/account/settings/settings.controller.js 200 8ms - 609b
GET /app/account/signup/signup.controller.js 200 7ms - 1006b
GET /app/admin/admin.controller.js 200 7ms - 413b
GET /app/admin/admin.js 200 7ms - 236b
GET /app/main/main.controller.js 200 7ms - 687b
GET /components/auth/auth.service.js 404 7ms
GET /app/main/main.js 200 9ms - 227b
GET /components/auth/user.service.js 404 7ms

I managed to get rid of a few 404s by adding this to my routes.js`:

      var appPath = app.get('appPath');
      app.use('/bower_components', express.static(appPath + "/bower_components/"));
      app.use('/app', express.static(appPath + "/app/"));

Why is this not by default in the `routes.js`? Also after building I don't see `/components/modal/modal.css` beeing deployed, as a matter of fact the /components/ dir is almost completely empty.

**Comment by JaKXz** [comment]
I would recommend following the generator's best practices and using `grunt serve` for development. The tasks in the Gruntfile have been iterated on quite a bit, and you're welcome to contribute improvements.
