### ISSUE TITLE
"wanted" vs "current" version of Node

### ISSUE THREAD

**Issue by michaelcheng429** [DaftMonk/generator-angular-fullstack#867]
Everything works fine, but just wondering about these warnings during installation:

    npm WARN engine karma@0.12.31: wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"0.12.0","npm":"2.5.1"})

    npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.0","npm":"2.5.1"})

Is this worth any concern?

**Comment by Awk34** [comment]
nope
