### ISSUE TITLE
Authentication calling callback before the user is loaded

### ISSUE THREAD

**Issue by Toub** [DaftMonk/generator-angular-fullstack#874]
Auth.login function on client side is calling the callback to early, so the page after direction may have to watch until the user is loaded before to display the template.

This code: 

    currentUser = User.get();
    deferred.resolve(data);
    return cb();

should be replaced by:

    currentUser = User.get(function () {
        deferred.resolve(data);
        return cb();
    });

and also better manage the error (but not sure if we have to call cb() in case of error here):

    currentUser = User.get(function () {
        deferred.resolve(data);
        return cb();
    }, function (err) {
        deferred.deffer(err);
    });

**Comment by Daniel-Xu** [comment]
angular will automatically fill the user data, so no need to put it into callback.

**Comment by Toub** [comment]
Yes, angular will do it, but too late, as it is an asynchronous call.

The next page has been called and some controller tried to get the undefined user data.

Except if the next page is watching the getCurrentUser() method, the page won't be updated once angular fill the user data..

**Comment by Awk34** [comment]
This is what I have changed mine to:

```javascript
currentUser = User.get();
currentUser.$promise.then(function() {
    deferred.resolve(data);
});
```

**Comment by smirciat** [comment]
I ran into the same problem and was happy to find a solution right here.  Has anyone generated a pull request on this?

**Comment by kingcody** [comment]
I'd suggest keeping the promise|callback behavior similar:
```diff
 /**
  * Authenticate user and save token
  *
  * @param  {Object}   user     - login info
- * @param  {Function} callback - optional, function(error)
+ * @param  {Function} callback - optional, function(error, user)
  * @return {Promise}
  */
 login: function(user, callback) {
   return $http.post('/auth/local', {
     email: user.email,
     password: user.password
   })
   .then(function(res) {
     $cookies.put('token', res.data.token);
     currentUser = User.get();
-    safeCb(callback)();
-    return res.data;
-  }, function(err) {
+    return currentUser.$promise;
+  })
+  .then(function(user) {
+    safeCb(callback)(user);
+    return user;
+  })
+  .catch(function(err) {
     this.logout();
     safeCb(callback)(err.data);
     return $q.reject(err.data);
   }.bind(this));
 }
```
