### ISSUE TITLE
Heroku app build failing: "No app specified"

### ISSUE THREAD

**Issue by adamgillfillan** [DaftMonk/generator-angular-fullstack#881]
First of all, thanks for the great generator! This is my first app using most of these technologies.

I build my app using `sudo grunt build`. There are no errors. The dist folder is built and the app works great using `sudo grunt serve:dist`. When I try to deploy to heroku for the first time, it fails using `yo angular-fullstack:heroku` from project root.

I receive the following error:  
   
    $ yo angular-fullstack:heroku
    [?] Name to deploy as (Leave blank for a random name): 
    [?] On which region do you want to deploy ?

    Initializing deployment repo
    Creating heroku app and setting node environment
    Creating myapp... done, stack is cedar-14
    
    https://myapp.herokuapp.com/ | https://git.heroku.com/myapp.git
    
    { [Error: Command failed:  !    No app specified.
     !    Run this command from an app folder or specify which app to use with --app APP.
    ] killed: false, code: 1, signal: null }`

My server is an HTTPS server, so I am not sure if that is interfering with anything.

from app.js:

```javascript
var options = {
  pfx: fs.readFileSync(__dirname + '/server.pfx'),
  passphrase: 'password'
};
// Setup server
var app = express();
var server = require('https').createServer(options, app);
```
I am using the latest version of generator-angular-fullstack: version 2.0.13. I am also using the latest version of the heroku toolbelt: version 3.28.2. I'm on a linux machine, ubuntu 14.xx.

**Comment by mariostesla** [comment]
i had the same problem
but you can do it "manually" (not really, just a few commands)

in dist folder

    heroku git:remote -a <app name>

only the first time 

then  use these commands to update your app
    
    git add .
    git commit -am "make it better"
    git push heroku master

you may also need a Procfile in the dist folder containing "web: node server/app.js"

**Comment by adamgillfillan** [comment]
Thank you. This helped but did not end up solving my problem. After some tinkering I got `yo angular-fullstack:heroku` working correctly.

**Comment by tharrington** [comment]
@adamgillfillan What did you have to do to get the deployment working?
