### ISSUE TITLE
error in npm install DaftMonk/grunt-build-control

### ISSUE THREAD

**Issue by LuisTJap** [DaftMonk/generator-angular-fullstack#883]
I have an error generating a project, in npm install, i have the next error:
```
Error: No compatible version found: grunt-build-control@'DaftMonk/grunt-build-control'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5","0.1.6","0.1.7","0.1.8","0.2.0","0.2.1","0.2.2","0.3.0"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
```
I solved it installing grunt-build-control without an especific version, but i don't know if it will be conflicts with other packages.

Congrats for this excellent project!

Regards,
Luis

**Comment by lbroudoux** [comment]
Same issue here with same workaround. So +1 !
Thanks for great job !

Regards,

**Comment by Awk34** [comment]
I would just use the original package: https://github.com/robwierzbowski/grunt-build-control

It's more updated.

**Comment by adamhadani** [comment]
Hey @DaftMonk - 
Is there a reason to keep the grunt-build-control package version at your fork ("grunt-build-control": "DaftMonk/grunt-build-control",)  ? It seems to be many commits behind the original repo.
If there is a reason, it would be helpful to update the README on the fork to reflect what the differences are and whether package is undergoing active maintenace
