### ISSUE TITLE
Error in Karma while running grunt

### ISSUE THREAD

**Issue by shashvattrip** [DaftMonk/generator-angular-fullstack#887]
Hey everyone!

I ran the command grunt to build my app and got this error. I have Phantomjs installed on my ubuntu 14.04 but I don't think that's the error. Something to do with karma running tests on phantomjs.
How do you fix this? Or am I doing something wrong?

Running "karma:unit" (karma) task
INFO [karma]: Karma v0.12.31 server started at http://localhost:8080/
INFO [launcher]: Starting browser PhantomJS
ERROR [launcher]: No binary for PhantomJS browser on your platform.
  Please, set "PHANTOMJS_BIN" env variable.
WARN [watcher]: Pattern "/home/shash/Desktop/apps/ga4g/beaconconsole/bob/client/app/app.coffee" does not match any file.
WARN [watcher]: Pattern "/home/shash/Desktop/apps/ga4g/beaconconsole/bob/client/components/**/*.coffee" does not match any file.
WARN [watcher]: Pattern "/home/shash/Desktop/apps/ga4g/beaconconsole/bob/client/components/**/*.jade" does not match any file.
WARN [watcher]: Pattern "/home/shash/Desktop/apps/ga4g/beaconconsole/bob/client/app/**/*.coffee" does not match any file.
WARN [watcher]: Pattern "/home/shash/Desktop/apps/ga4g/beaconconsole/bob/client/app/**/*.jade" does not match any file.
Warning: Task "karma:unit" failed. Use --force to continue.

Aborted due to warnings.

**Comment by Awk34** [comment]
Can you [pastebin](http://pastebin.com) your Gruntfile?

**Comment by shashvattrip** [comment]
Hey, 
It's done now. I think the doc was right, my ubuntu installation was screwing it up.
Thanks for the help though!
