### ISSUE TITLE
angular-fullstack command for factory generator still generates a service

### ISSUE THREAD

**Issue by asheeshv** [DaftMonk/generator-angular-fullstack#893]
Hello there,

I'd like to congratulate you for a wonderful piece of work which has provided me an out of the box framework to work with. However, I've been running into issues trying to use its factory generator. When I invoke the command you angular-fullstack:factory sampleFactory. The resulting output is still a service, where as I was expecting a factory created instead. I wanted to check if there's a different way to invoke the factory generators. Also, If I run the above command without providing the factory name argument, I get an error in events.js stating unhandled 'error' event. Please let me know as to what's the correct way to create a generator based factory?.

Many thanks!
Asheesh

**Comment by asheeshv** [comment]
This is a non-issue. Since I use perforce, and by-default all files are read-only. Trying to run the factory command failed as I hadn't checked out some of the other files. checking out the relevant files caused the factory to be created successfully. Hence I'm closing this issue.

**Comment by LunarDevelopment** [comment]
Hello! 

I'm new to Yo and I'm having a similar issue, when I run:factory <name> I get a file named <name>.service.coffee (as I'm using coffeescript) 

Inside the file is a .factory (which is what I want of course), 

Is this as it should be or do I have this "perforce" running somewhere in my directory? (when I run a file search for "perforce" I find nothing however) 

Lewis
