### ISSUE TITLE
optipng.exe Warning - Windows 7

### ISSUE THREAD

**Issue by daveteply** [DaftMonk/generator-angular-fullstack#896]
**Dev env**
- Windows 7

**angular-fullstack configuration**

*Client*
- Scripts: JavaScript
- Markup: HTML
- Stylesheets: Less
- Angular Routers: ui-router

*Server*
- Database: None

**Issue**
- Warning: Running "imagemin:dist" (imagemin) task Warning: spawn …\byo-web-ui\src\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin\vendor\optipng.exe ENOENT Use --force to continue.

**Workaround**
- Manually installing optimg
- `npm install grunt-contrib-imagemin --save-dev`

**Comment by Awk34** [comment]
I dev in Win8.1 and haven't seen this before.

**Comment by daveteply** [comment]
Thanks Awk43, as stated in the issue title and in the issue contents the environment is Windows 7 (my work laptop).  You are correct: I just tried it on my Windows 8.1 computer (my personal desktop) and it works great.  I guess I'll mark this one as closed?
