### ISSUE TITLE
grunt build error

### ISSUE THREAD

**Issue by khwerhahn** [DaftMonk/generator-angular-fullstack#898]
Hi,

I get the following error:

Running "rev:dist" (rev) task
dist/client/app/app.js >> 8551cad9.app.js
dist/client/app/vendor.js >> 0121d770.vendor.js
Warning: Unable to read "dist/client/bower_components/Chart.js" file (Error code: EISDIR). Use --force to continue.

The bower component is there. Very strange. Can anybody pls help?

**Comment by Awk34** [comment]
**EISDIR** means Error IS DIRectory. Is `Chart.js` a directory, and instead you want to get something from inside that directory?

**Comment by khwerhahn** [comment]
Its the chart.js library (https://github.com/carlcraig/tc-angular-chartjs). There are files (i.e. dist) in the directory (dist/client/bower_components/Chart.js/dist/....). I don't know why grunt throws an error since it is a normal directory?

**Comment by mariostesla** [comment]
it's because the Chart.js ends in .js and it thinks it's a javascript file, a solution would be to exclude it from the grunt tasks.
add the exclude rule to src of rev like this

    rev: {
      dist: {
        files: {
          src: [ ...,  '!**/Chart.js/**' ] 

and something similar for usemin

    usemin: {
      js: [...,  '!**/Chart.js/**']

**Comment by Awk34** [comment]
Thanks @mariostesla .
In the final `index.html`, it should import `/bower_components/Chart.js/dist/tc-angular-chartjs.min.js`, not `/bower_components/Chart.js`. It's bad practice to include dots in directory names :/

**Comment by khwerhahn** [comment]
Ok thanks. I have posted it in the tc-angular-chartjs.min.js project.

**Comment by jromero-onclick** [comment]
I am facing the same error with the library Filesaver.js (https://github.com/alferov/angular-file-saver)

Warning: Unable to read "dist/public/bower_components/file-saver.js" file (Error code: EISDIR). Use --force to continue.

**Comment by Awk34** [comment]
@jromero-onclick see #1064
