### ISSUE TITLE
recursive socket io logs in terminal after 'grunt serve' 

### ISSUE THREAD

**Issue by InterwebCounty** [DaftMonk/generator-angular-fullstack#899]
I created a new angular-fullstack site and chose to use socket.io - and now when I run 'grunt serve' on any other angular-fullstack created site I get this for infinity:

GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1426902928383-8 200 12ms
GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1426902928423-9 200 7ms
GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1426902928451-10 200 4ms

etc, etc, etc...

I've tried uninstalling and reinstalling angular-fullstack, clearing the npm cache, not sure what to try next.  

Any ideas?

**Comment by Awk34** [comment]
`200` is HTTP `OK`; All looks fine to me.

**Comment by InterwebCounty** [comment]
But why is it outputting that every 7ms?

**Comment by Awk34** [comment]
I believe it's some sort of debug output, like what's described here: http://socket.io/docs/logging-and-debugging/. Enter `localStorage.debug` into your browser's console and it will show you what debug settings you have on.

**Comment by InterwebCounty** [comment]
It turned out to be Aurelia: http://aurelia.io/ which also runs on port 9000 and uses browsersync and socket io.  Deleting all of the Aurelia stuff and restarting fixed things.

**Comment by edweena** [comment]
hey guys, having the same problem but no aurelia installed. any ideas?
