### ISSUE TITLE
npm install problem with cloning

### ISSUE THREAD

**Issue by molerat619** [DaftMonk/generator-angular-fullstack#904]
Hi,

I just ran npm install on my computer and got this error in the error log. I'm really sorry if this topic already exists, I couldn't find sufficient help with Google.

What I did: I cloned my repo, ran bower install (worked) and then npm install. The same thing works on my other computer and on my macbook.

2228 verbose stack Error: Command failed: git -c core.longpaths=true clone --template=C:\Users\APIS\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/DaftMonk/grunt-build-control C:\Users\APIS\AppData\Roaming\npm-cache\_git-remotes\https-github-com-DaftMonk-grunt-build-control-7e4d577b
2228 verbose stack Cloning into bare repository 'C:\Users\APIS\AppData\Roaming\npm-cache\_git-remotes\https-github-com-DaftMonk-grunt-build-control-7e4d577b'...
2228 verbose stack fatal: unable to access 'https://github.com/DaftMonk/grunt-build-control/': Failed connect to github.com:443; No error
2228 verbose stack
2228 verbose stack     at ChildProcess.exithandler (child_process.js:744:12)
2228 verbose stack     at ChildProcess.emit (events.js:110:17)
2228 verbose stack     at maybeClose (child_process.js:1008:16)
2228 verbose stack     at Socket.<anonymous> (child_process.js:1176:11)
2228 verbose stack     at Socket.emit (events.js:107:17)
2228 verbose stack     at Pipe.close (net.js:476:12)
2229 verbose cwd C:\xampp\htdocs\blabla
2230 error Windows_NT 6.1.7601
2231 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
2232 error node v0.12.0
2233 error npm  v2.5.1
2234 error code 128
2235 error Command failed: git -c core.longpaths=true clone --template=C:\Users\APIS\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/DaftMonk/grunt-build-control C:\Users\APIS\AppData\Roaming\npm-cache\_git-remotes\https-github-com-DaftMonk-grunt-build-control-7e4d577b
2235 error Cloning into bare repository 'C:\Users\APIS\AppData\Roaming\npm-cache\_git-remotes\https-github-com-DaftMonk-grunt-build-control-7e4d577b'...
2235 error fatal: unable to access 'https://github.com/DaftMonk/grunt-build-control/': Failed connect to github.com:443; No error
2236 error If you need help, you may report this error at:
2236 error     <http://github.com/npm/npm/issues>
2237 verbose exit [ 1, true ]

Thanks guys

**Comment by Awk34** [comment]
Change `"grunt-build-control": "DaftMonk/grunt-build-control",` in `package.json` to `"grunt-build-control": "0.3.0",` and try again

**Comment by molerat619** [comment]
Thx for your answer. Why would that fix it, if it works on all my other computers?

After applying your change, The error did not occur anymore, but now I get some other errors.

npm WARN package.json karma-chrome-launcher@0.1.7 No README data
npm WARN package.json karma-coffee-preprocessor@0.2.1 No README data
npm WARN package.json karma-firefox-launcher@0.1.4 No README data
npm WARN package.json karma-phantomjs-launcher@0.1.4 No README data
npm WARN package.json passport-local@0.1.6 No README data
npm WARN unmet dependency C:\xampp\htdocs\blabla\node_modules\grunt requires lodash@'~0.9.2' but will load
npm WARN unmet dependency C:\xampp\htdocs\blabla\node_modules\lodash,
npm WARN unmet dependency which is version 2.4.1
npm WARN unmet dependency C:\xampp\htdocs\blabla\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-gifsicle\node_modules\gifsicle\node_modu
les\bin-build\node_modules\download requires nopt@'^2.2.0' but will load
npm WARN unmet dependency C:\xampp\htdocs\blabla\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\nopt,
npm WARN unmet dependency which is version 3.0.1
npm WARN unmet dependency C:\xampp\htdocs\blabla\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-gifsicle\node_modules\gifsicle\node_modu
les\bin-wrapper\node_modules\download requires nopt@'^2.2.0' but will load
npm WARN unmet dependency C:\xampp\htdocs\blabla\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\nopt,
npm WARN unmet dependency which is version 3.0.1
npm WARN unmet dependency C:\xampp\htdocs\blabla\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-jpegtran\node_modules\jpegtran-bin\node_
modules\bin-build\node_modules\download requires nopt@'^2.2.0' but will load
npm WARN unmet dependency C:\xampp\htdocs\blabla\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\nopt,
npm WARN unmet dependency which is version 3.0.1
npm WARN unmet dependency C:\xampp\htdocs\blabla\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-jpegtran\node_modules\jpegtran-bin\node_
modules\bin-wrapper\node_modules\download requires nopt@'^2.2.0' but will load
npm WARN unmet dependency C:\xampp\htdocs\blabla\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\nopt,
npm WARN unmet dependency which is version 3.0.1
npm WARN unmet dependency C:\xampp\htdocs\blabla\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin\node_mo
dules\bin-build\node_modules\download requires nopt@'^2.2.0' but will load
npm WARN unmet dependency C:\xampp\htdocs\blabla\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\nopt,
npm WARN unmet dependency which is version 3.0.1
npm WARN unmet dependency C:\xampp\htdocs\blabla\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin\node_mo
dules\bin-wrapper\node_modules\download requires nopt@'^2.2.0' but will load
npm WARN unmet dependency C:\xampp\htdocs\blabla\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\nopt,
npm WARN unmet dependency which is version 3.0.1

and so on. Why is that?

**Comment by molerat619** [comment]
anybody please?

**Comment by molerat619** [comment]
This might have been an issue with my nodeJS version. I don't know which version I had, but after installing the latest version, I was able to do `npm install` even with `"grunt-build-control": "DaftMonk/grunt-build-control"`.
