### ISSUE TITLE
Dynamic Page Title

### ISSUE THREAD

**Issue by imomin** [DaftMonk/generator-angular-fullstack#906]
What would be a right way to dynamically set page title?

Following is what I am thinking:
1) Create "page" factory in client/app/app.js
.factory('page', function() {
    var title = 'default title';
    return {
      title: function() { return title; },
      setTitle: function(newTitle) { title = newTitle }
    };
  })

2) Create "pageTitleCtrl" controller in client/app/app.js
  .controller('pageTitleCtrl', function($scope, page) {
      $scope.page = page;
  })

3) Move ng-app from body tag to html. However, I am not sure if I need to add it to all the html tags for different IE version as well? Finally add controller to &lt;head&gt; and add {{page.title()}} to &lt;title&gt; tag.
&lt;!doctype html&gt;<br/>&lt;!--[if lt IE 7]&gt;      &lt;html class=&quot;no-js lt-ie9 lt-ie8 lt-ie7&quot;&gt; &lt;![endif]--&gt;<br/>&lt;!--[if IE 7]&gt;         &lt;html class=&quot;no-js lt-ie9 lt-ie8&quot;&gt; &lt;![endif]--&gt;<br/>&lt;!--[if IE 8]&gt;         &lt;html class=&quot;no-js lt-ie9&quot;&gt; &lt;![endif]--&gt;<br/>&lt;!--[if gt IE 8]&gt;&lt;!--&gt; &lt;html class=&quot;no-js&quot; ng-app=&quot;myApp&quot;&gt; &lt;!--&lt;![endif]--&gt;<br/>  &lt;head ng-controller=&quot;pageTitleCtrl&quot;&gt;<br/>    &lt;meta charset=&quot;utf-8&quot;&gt;<br/>    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;<br/>    &lt;base href=&quot;/&quot;&gt;<br/>    &lt;title&gt;{{page.title()}}&lt;/title&gt;

4) "page" can be injected into any controller and dynamically set the page title.
.controller('MainCtrl', function ($scope, $http, socket,page) {
    $scope.awesomeThings = [];
    page.setTitle("home page");
...

**Comment by jnuserful** [comment]
something like https://coderwall.com/p/vcfo4q/angularjs-change-title-based-on-route

**Comment by Awk34** [comment]
I have a similar setup:

```javascript
angular.module('aksiteApp', [...])
    .run(function($rootScope, $location, Auth) {
        // Redirect to login if route requires auth and you're not logged in
        $rootScope.$on('$stateChangeStart', function(event, next) {
            $rootScope.title = 'Andrew Koroluk';
            Auth.isLoggedInAsync(function(loggedIn) {
                if(next.authenticate && !loggedIn) {
                    $location.path('/login');
                }
            });
        });

        $rootScope.titleRoot = 'AK';
        $rootScope.title = 'Andrew Koroluk';
    });
```
```javascript
angular.module('aksiteApp')
    .config(function($stateProvider) {
        $stateProvider
            .state('admin', {
                abstract: true,
                url: '/admin',
                templateUrl: 'app/admin/admin.html',
                controller: 'AdminCtrl',
                onEnter: function($rootScope) {
                    $rootScope.title = $rootScope.titleRoot + ' | Admin';
                }
            });
    });
```

Whenever the route changes, the title defaults to my name. Then, for routes that I define it, such as admin, the title changes to something like 'AK | Admin'.

**Comment by dmarcelino** [comment]
:+1:

**Comment by dmarcelino** [comment]
BTW, I end up using [angular-ui-router-title](https://github.com/nonplus/angular-ui-router-title) and I'm quite happy. More about the subject in http://stackoverflow.com/questions/23813599/set-page-title-using-ui-router

**Comment by Awk34** [comment]
Thanks for the info!
