### ISSUE TITLE
Cannot PUT /api/users

### ISSUE THREAD

**Issue by minmur** [DaftMonk/generator-angular-fullstack#907]
Question

I want to update user, but always get 404 (Cannot PUT /api/users). Calling `api/users` to `router.put('/:id', auth.isAuthenticated(), controller.update);`, but it looks like update method is never called and some middleware interrupts. Unfortunately, i lack experience in node stack and can't find.
What am i missing? How do you solve user update thing?

**Comment by madjae** [comment]
Just checking:

1) You are already authenticated?
2) You are passing the Authentication header in your request?
Authorization: Bearer <token>

**Comment by minmur** [comment]
Yes, i'm authenticated and want to update other user's information. Like phone, address.

**Comment by jimmyalcala** [comment]
Please show your controller where you call the api!

**Comment by ericmdantas** [comment]
Isn't it supposed to be ```/api/users``` instead of ```api/users```? Looks like there's a slash missing, right before ```api```.

**Comment by minmur** [comment]
Found the problem: retrieved user's data for editing, didn't contained _id. Now i added it to user.profile and everything works as expected.

**Comment by comoss** [comment]
@minmur I am experiencing the same issue, can you share your code?
