### ISSUE TITLE
ENOENT error when not started from project root

### ISSUE THREAD

**Issue by Lotes** [DaftMonk/generator-angular-fullstack#908]
I deployed an angular-fullstack project on my Raspberry Pi. I start the server during a reboot using a crontab entry:
```
@reboot /usr/local/bin/node /root/my-project/server/app.js
```
When I query the "index.html" everything is fine.
When I navigate to an "angular link" like "/projects" (not a file on the server, but a route in the angular config) the page will be loaded.
But when I press refresh on "/projects" I get an error message in my browser:
```
Error: ENOENT, stat 'client/index.html'
```

I can reproduce this behaviour on windows, when I don't start the "server/app.js" from the projects folder, e.g. from "C:\Data\Projekte\" not from "C:\Data\Projekte\my-project\".
```
Error: ENOENT, stat 'C:\Data\Projekte\client\index.html' at Error (native)
```

How can I solve this? Does a "__dirname" missing somewhere?

**Comment by tomasalmeida** [comment]
Hi, 

Take a look on issue #712. It helped me.

Regards,

Tomás
