### ISSUE TITLE
logout doesn't log out

### ISSUE THREAD

**Issue by wmertens** [DaftMonk/generator-angular-fullstack#909]
All logout does is remove the token, but on the server side the token is still valid.

The server should have a `/auth/logout` call that invalidates the session.

**Comment by mariostesla** [comment]
i am not an expert but i think it's because we don't keep track of the logged in users (no sessions, it's stateless) so the token is valid until its expiry date or if you change secret

**Comment by wmertens** [comment]
@mariostesla ah yes indeed... except when you use twitter: https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/server/config/express.js#L34-L44
