### ISSUE TITLE
Upgrade to jsonwebtoken 4.2.2

### ISSUE THREAD

**Issue by trainerbill** [DaftMonk/generator-angular-fullstack#916]
Vulnerability exists in jsonwebtoken:

https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/

Updating to 4.2.2 alone breaks the mongo interaction.  Trying to figure out why but am stumped

**Comment by trainerbill** [comment]
Mongo connection was me being an idiot.  I did upgrade to jsonwebtoken 4.2.2 and it seems to be working fine.

**Comment by yayolius** [comment]
i have an issue with this because after installing the new version and running a npm update, i started getting a jwt session expired error

**Comment by aendrew** [comment]
Still, this should be done so people scaffolding out new projects aren't introducing a vulnerability from the get-go. Is it as difficult as just updating `package.json`?

**Comment by MichaelJCole** [comment]
Hey, this is a serious issue.  Basically every app made with your stack has wide open security.

https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/

**Comment by MichaelJCole** [comment]
`npm install jsonwebtoken@5` will update the package.  I didn't test if it works - I had to move on to other things.

**Comment by Awk34** [comment]
Has been upgraded to version 5
