### ISSUE TITLE
Change $location.path('/login') to $state.go('login') or $location.url('/login') in 'logout' function in navbar.controller.js

### ISSUE THREAD

**Issue by chinnichaitanya** [DaftMonk/generator-angular-fullstack#919]
Hello,
I stumbled upon this issue today in my generator-angular-fullstack app. 

In my app, I have a 'state' with ```url: /xyz/abc?p&q&r```

Once I visit that particular 'state', and then I logout immediately (without visiting any other state in-between), the redirected page has url something like this: ```/login?p=<...>&q=<...>&r=<...>``` instead of  ```/login```. The parameter values of the previous state are not cleared.

I got two possible solutions for this.
In logout() function in navbar.controller.js, change the line ```$location.path('/login')``` to ```$location.url('/login')``` or include ```$state``` in our controller and change it to ```$state.go('login')``` instead. 

Any suggestions on which solution is better ?

Reference : http://stackoverflow.com/questions/17376416/angularjs-how-to-clear-query-parameters-in-the-url
Screenshots: 
My 'state' with ```url: /xyz/abc?p&q&r``` : 
![2015-04-05-235325_1366x768_scrot](https://cloud.githubusercontent.com/assets/6941024/6997988/27d3d03c-dbef-11e4-9c35-0d70db905cd6.png)

url after logging out immediately without visiting any other state in-between :
![2015-04-05-235348_1366x768_scrot](https://cloud.githubusercontent.com/assets/6941024/6997991/6bb152de-dbef-11e4-9742-ce349e13200e.png)

**Comment by chinnichaitanya** [comment]
By the way, I'm using 'ui-router' module.

**Comment by chinnichaitanya** [comment]
Any thoughts on this anyone ?

**Comment by chinnichaitanya** [comment]
@Awk34 Any views on this ?

**Comment by kingcody** [comment]
@chinnichaitanya I believe your issue has been addressed in the `canary` branch by https://github.com/DaftMonk/generator-angular-fullstack/commit/6aadee6d956cefb9a787eb0851d287654dfca111
