### ISSUE TITLE
How to add OAuth support after the project creation ?

### ISSUE THREAD

**Issue by pihomeserver** [DaftMonk/generator-angular-fullstack#923]
Hello,

I built my project with the standard yo command but said no for authentication support. Now i would like to add it. Is there an easy way to do so (with yo command) without loosing my current developments ? Or do i have to do it from scratch with passportjs ?

Regards

**Comment by Awk34** [comment]
Your best bet is probably generating a new project with all the same options as last time, but adding OAuth. Then, copy over the code that you need.

**Comment by pihomeserver** [comment]
Ok thanks.
I made this and was able to simulate the process. Now i have to remove MongoDb and replace it with SQLite ....
