### ISSUE TITLE
yo angular-fullstack:heroku suddenly stuck 

### ISSUE THREAD

**Issue by andrea-spotsoftware** [DaftMonk/generator-angular-fullstack#925]
Hello everyone,
I'm trying to deploy my app on heroku, but after seeing in terminal the string "Creating heroku app and setting node environment", nothing happens and looks like everything is freezed. 
No errors logged in console.

The only few things that i did, were moving the shell on the root of application (where the Gruntfile is located) and launching the command "yo angular-fullstack:heroku".

Anyone experienced the same issue?

Thanks

**Comment by jgodi** [comment]
The first time doing this could take some time. It's more on the heroku servers then anything I believe.

**Comment by andrea-spotsoftware** [comment]
Well, I waited like two hours but nothing changed. 
Another detail, i selected EU region.

**Comment by orcocacchio** [comment]
I'm having the same issue. Have you got any further information?

**Comment by adam-back** [comment]
What kind of messages do you get when you run `heroku logs` in the terminal?

**Comment by ccrypticc** [comment]
Had the same problem. Login to heroku before running deploy.

**Comment by mateutek** [comment]
Same problem, loging to heroku via
heroku auth:login
fixed it.
