### ISSUE TITLE
Question : Why mongoose-bird is used instead of mongoose-q

### ISSUE THREAD

**Issue by programming-kid** [DaftMonk/generator-angular-fullstack#926]
i am curious why fullstack is using mongoose-bird instead of widely used mongoose-q (based on github stars) .
And is it drop-in replacement for mongoose-q ?? can i replace mongoose-bird with mongoose-q

#JustCurious 

thanks

**Comment by Awk34** [comment]
Many people believe that Bluebird is a better promise library than Q

**Comment by programming-kid** [comment]
i thought it must be the reason too, but i was not entirely sure about that

**Comment by arg20** [comment]
@programming-kid performance. Most people choose bluebird over Q for performance reasons, I don't have any benchmarks but if I can I'll look it up
