### ISSUE TITLE
cloudinary-angular, authInterceptor problems????

### ISSUE THREAD

**Issue by wikett** [DaftMonk/generator-angular-fullstack#931]
I would like to use cloudinary_angular in my angular project I´ve spent two days trying to use it but I have always the same problem and I don't know how to solve it.

I get this error in the console log, using cloudinary example (https://github.com/cloudinary/cloudinary_angular/blob/master/samples/photo_album/app/js/controllers.js#L69)
```
XMLHttpRequest cannot load https://api.cloudinary.com/v1_1/djhqderwy/upload. Request header field Authorization is not allowed by Access-Control-Allow-Headers.
```

I dont have much experience with CORS the use of authInterceptor, Has someone experience with this kind of problems?

Thanks in advance

**Comment by mariostesla** [comment]
using $http i was adding this
```
          $http({
            method: 'GET',
            url: ' ',
            transformRequest: function (data, headersGetter) {
              var headers = headersGetter();
              delete headers['Authorization'];
              return headers;
            }
          }).success(function (response) {
```
i don't know however in your case if it helps, another way is to edit the authInterceptor factory in app.js and expand the if statement that checks if there is a token to also check if the url does not contain `cloudinary.com` for example.

**Comment by wikett** [comment]
I dont know how to use your example in my project :(

I have this code in my /client/app/app.js
```
  .config(function ($stateProvider, $urlRouterProvider, $locationProvider, $httpProvider) {
    $urlRouterProvider
      .otherwise('/');

    $locationProvider.html5Mode(true);
    $httpProvider.interceptors.push('authInterceptor');

    $httpProvider.defaults.headers.common['Access-Control-Allow-Headers'] = '*';
    delete $httpProvider.defaults.headers.common['X-Requested-With'];
  })
```
just in case... but it doesn't work...

**Comment by mariostesla** [comment]
i mean [this line](https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/client/app/app(js).js#L25).

This adds the authorization header to every request.
And you can edit it like this. It's not the best way but it will fix it i believe.
```
        if ($cookieStore.get('token') && config.url.indexOf('api.cloudinary.com')===-1) {
          config.headers.Authorization = 'Bearer ' + $cookieStore.get('token');
        }

```

**Comment by wikett** [comment]
Thanks for your help

**Comment by jackrobertscott** [comment]
May also fix problem by altering server side as opposed to client side. Simply implement the 'cors' npm package in app.js file like shown in answer to: http://stackoverflow.com/questions/28552593/cross-domain-origin-problems-when-deploying-angular-full-stack-app-on-server. This worked for me.

**Comment by Awk34** [comment]
It looks like this was resolved. Re-open if not.
