### ISSUE TITLE
Problem with req.user

### ISSUE THREAD

**Issue by epworthhh** [DaftMonk/generator-angular-fullstack#937]
Hi, thanks for the generator!

I have a problem, i need to use the logged User object (req.user) in another controller, not in User controller.

But req.user in the other controller is null. any idea?

Thanks,

**Comment by chinnichaitanya** [comment]
You need to include ```isAuthenticated()``` function to populate the (req.user) with the current user. 
For that you need to include ```auth.service.js``` file in (auth) folder in (server) into your (index.js) for the corresponding controller. 
Have a look at (index.js) file in (user) module in server.

**Comment by epworthhh** [comment]
Is included in that file, but i show u that i wanna do. I have users and buttons (i'm using sequelize instead of mongoose) and i have an association between users and buttons, so when I create a button, i have to add the user object in a button (to the association table). Do u know how I cant take the User Object for use it in the .complete() after .save() when i save a new button? 

exports.create = function(req, res, next) {
  var newButton = Button.build(req.body);
  newButton.provider = 'local';

  newButton
  .save()
  .complete(function(err, newButton, user) {
    if (err) return handleError(res, err);
      newButton.addUser(req.user);
...

Thanks

**Comment by chinnichaitanya** [comment]
Can you please show the ```index.js``` file for this controller ?

**Comment by Awk34** [comment]
Closed as no response
