### ISSUE TITLE
Problem with socket.io jwt

### ISSUE THREAD

**Issue by jnuserful** [DaftMonk/generator-angular-fullstack#939]
I have uncommented on config/socketio.js:

``` javascript
socketio.use(require('socketio-jwt').authorize({
    secret: config.secrets.session,
    handshake: true
  }));
```

But when i do somethink like:

``` javascript
socketio.on('connection', function (socket) {
    console.info(socket.handshake.decoded_token);
}
```

Result is undefined.

also, in client side i have uncommented these lines on socket.service.js:
``` javascript
var ioSocket = io('', {
      // Send auth token on connection
      query: 'token=' + Auth.getToken(),
      path:  '/socket.io-client'
    });
```

**Comment by Awk34** [comment]
make sure your client `socket.service` has something like this:
```javascript
        var ioSocket = io($window.location.origin + '/chat', {
            // Send auth token on connection, you will need to DI the Auth service above
            query: 'token=' + Auth.getToken(),
            path: '/socket.io-client'
        });
```

You can find the token in `socket.handshake.headers.cookie` on the server side.

**Comment by jnuserful** [comment]
¿does it work also with something like?

``` javascript

var ioSocket = io('', {
      // Send auth token on connection
      query: 'token=' + Auth.getToken(),
      path:  '/socket.io-client'
    });
```

**Comment by Awk34** [comment]
You can decode it manually with `jwt.verify(token, config.secrets.session, function(err, decoded) {})`

**Comment by jnuserful** [comment]
Thank you. That is a good idea.

**Comment by anoopknayak** [comment]
It might not make sense now to comment to this, but just like to add that decoded_token is available directly under socket i.e **socket.decoded_token**. Might serve this for future referrers of this thread :)
