### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by AliceRossa** [DaftMonk/generator-angular-fullstack#946]
Hello,

I am a beginner with AngularJS, I want to create a dashboard accessible only by administrators.

I renamed the "admin" folder with "dashboard" and I want that access is allowed to administrators. So I added "authenticate: true" to Controller "dashboard.js" but all registered users can also access /dashboard

I will wish to add the rule "auth.hasRole ('admin')" somewhere but I don't know where to insert it.

----

I created a "news" module, which is the best way to create functions to create, edit, delete, accessible only for admins.
What is the best way?
"news" -> news.html (news list accessible to all)
            -> "dashboard" -> create-news.html, news-edit.html, delete-news.html
OR
"dashboard" -> "news" -> create-news.html, news-edit.html, delete-news.html

----

One last thing, is it normal to have access to the login page when one is already connected?

Thank you very much for your help, greetings from France!

**Comment by chinnichaitanya** [comment]
For handling client side permissions, you can use some angular modules like https://github.com/Narzerus/angular-permission

For handling permissions in the server side, you can always use ```auth.hasRole('amin');``` or any other role you have created and want access to.

Regarding the access to login page, I'm not completely sure about it's consequences. But I've tried once logging in again with different account after I was connected and it simply changed the logged in user to the latest one.

**Comment by Awk34** [comment]
It looks like your question was answered. Feel free to re-open if you still need help.
