### ISSUE TITLE
yo angular-fullstack:route do not work

### ISSUE THREAD

**Issue by jackkum** [DaftMonk/generator-angular-fullstack#947]
I'm try to create a route as mentioned here https://github.com/DaftMonk/generator-angular-fullstack#route 
$ yo angular-fullstack:route companies
? Where would you like to create this route? clinet/app
? What will the url of your route be? /companies

And more nothing. 
What i'm doing wrong?

yo --version
1.4.6
bower --version
1.4.0
node --version
v0.10.24

**Comment by Awk34** [comment]
Can you provide more information?

**Comment by jackkum** [comment]
@Awk34 what information you need?
![angular-fullstack](https://cloud.githubusercontent.com/assets/2418167/7340301/9057154e-ecb4-11e4-91ba-c3f6cc76a208.png)

**Comment by jackkum** [comment]
looks like is a not angular-fullstack trouble
https://github.com/DaftMonk/generator-ng-component/blob/master/util.js#L120 
this method always return false

**Comment by jackkum** [comment]
this helped to me https://github.com/brutalhonesty/linesPerBeat/blob/master/.yo-rc.json
append to .yo-rc.json block generator-ng-component
