### ISSUE TITLE
Custom IP for deployment with nginx

### ISSUE THREAD

**Issue by hugesuccess** [DaftMonk/generator-angular-fullstack#948]
I'm trying to deploy my app on digital ocean with an nginx reverse proxy. The express app needs to listen on a private ip for requests. Where do I define a custom IP address?

**Comment by Koslun** [comment]
Well Digital Ocean has some great tutorials on this. If you haven't solved this yet you can check this tutorial out: https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-14-04.

To possibly save you some time: don't think you should need to change anything in the express app to do a reverse proxy. Just be sure to set the node variable to production with 'export NODE_ENV=production' and the default settings from this generator should make it start at: http://127.0.0.1:8080. In development mode it instead launches at port 9000, but still at localhost.

So just be sure to enter that at the 'proxy_pass http://127.0.0.1:8080;' as you can see in the guide.  Where 'localhost' is another name for that private IP address which you can see in the Express app.

**Comment by hugesuccess** [comment]
Hey thanks this worked perfect. Digital Ocean is pretty nice for node apps.
