### ISSUE TITLE
npm ERR! peerinvalid Peer mongoskin@1.4.13 wants mongodb@~1.4

### ISSUE THREAD

**Issue by ShylockGou** [DaftMonk/generator-angular-fullstack#950]
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "generator-angular-fullstack"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package mongodb does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer mongoskin@1.4.13 wants mongodb@~1.4

npm ERR! Please include the following file with any support request:

**Comment by Awk34** [comment]
And the award for least explained issue goes to...

**Comment by remicastaing** [comment]
Could be the node version. Try to downgrade to a previous node version, @ShylockGou.
