### ISSUE TITLE
generates the wrong controller name

### ISSUE THREAD

**Issue by kjr247** [DaftMonk/generator-angular-fullstack#951]
I am documenting this as it happens and I'm not sure quite why, but It seems that generating a controller will generate it with the Ctrl appended at the end of the name of the controller instead of the required: "Controller" which causes it not to work at all. This is a problem with the generator-angular-fullstack as far as I can tell so far, but I am really unsure why it does this.

So example: 

You want to generate a controller with:

    yo angular-fullstack:controller user

This generates a controller with the name: userCtrl.

Which as far as I thought isn't even a convention for Angular unless you give it a nickname in the html. If anyone has any ideas why it is doing it this way please explain. 

Replicating the issue:
The way that I came about this was by simply generating a controller as seen above and then referencing something from the scope in html. It won't populate and simply pops out the {{ message }} in the html. Then I copy and paste exact code from the angular site using the proper Controller appended name and everything works fine.

**Comment by Awk34** [comment]
You can name your controllers whatever you want, it's a user preference
