### ISSUE TITLE
What about using $resource at client side ?

### ISSUE THREAD

**Issue by gintsgints** [DaftMonk/generator-angular-fullstack#952]
Why we do not use $resource service instead $http ?

Like:
    angular.module('crudApp')
      .factory('Thing', function($resource) {
        return $resource('/api/things/:id');
      });
and
    var things = Thing.query(function() {
      $scope.awesomeThings = things;
    });

**Comment by deebloo** [comment]
$http provides more flexibility. but that is just an opinion on my part

**Comment by Awk34** [comment]
Coding it out with `$http` makes it more apparent what's really going on, but if you're doing standard API resource calls, `$resource` is quite convenient
