### ISSUE TITLE
Serve Static JSON Files

### ISSUE THREAD

**Issue by hugesuccess** [DaftMonk/generator-angular-fullstack#953]
I have some static data that I don't want to hard code into my templates and don't see the need to store in a database (footer links, navigation links, etx). Ideally I would like to serve static JSON files that angular could pull into the app via $http. I've placed the .json files in 'assets/json' directory, which works fine locally. In production I cannot get a response. I've checked and the .json makes it into the production build -- but when I try to ping the endpoint in a browser I get redirected back to the main angular page, and postman cannot return a response. Any thoughts on what could be going on, or best practices on how to accomplish this? I'm stumped. :(

**Comment by deltreey** [comment]
grunt serve:dist to see what's happening in production locally.

**Comment by Awk34** [comment]
Make sure you have edited your `Gruntfile.js` so that it copies the contents of your `assets/json` file when the project is built.

**Comment by Awk34** [comment]
Do you need any more help with this?
