### ISSUE TITLE
edit users

### ISSUE THREAD

**Issue by ccshannon123** [DaftMonk/generator-angular-fullstack#954]
Can anyone please provide details on how to expand the admin section to edit user information. I am having trouble with the api routes

**Comment by chinnichaitanya** [comment]
It can be done in many ways. You need to create an api call for retrieving all the details of a particular user and also an api for updating the user details. 
It would be great if you can tell us how did you try to implement it and where exactly you are facing issues.

**Comment by Awk34** [comment]
You would need to add an endpoint for editing a user, such as 
```js
exports.update = function(req, res) {
    if (req.body._id) {
        delete req.body._id;
    }
    User.findById(req.params.id, function(err, user) {
        if (err) {
            return handleError(res, err);
        }
        if (!trip) {
            return res.status(404).send('Not Found');
        }
        var updated = _.merge(user, req.body);
        updated.save(function (err) {
            if (err) {
                return handleError(res, err);
            }
            return res.status(200).json(user);
        });
    });
};
```

and then send data to that endpoint from your UI.
