### ISSUE TITLE
Socket emitting Hashed Password and Salt

### ISSUE THREAD

**Issue by vicky-gonsalves** [DaftMonk/generator-angular-fullstack#956]
Whenever User Object is Saved or Removed, Socket emits the complete User Object including sensitive info(Hashed Password and Salt) as in this code snippet:
```
function onSave(socket, doc, cb) {
  socket.emit('user:save', doc);
}

function onRemove(socket, doc, cb) {
  socket.emit('user:remove', doc);
}

```
Is it safer to allow socket emit this data?

**Comment by Awk34** [comment]
No, you should never emit a password hash and/or salt
