### ISSUE TITLE
It is not clear how to use modal?

### ISSUE THREAD

**Issue by maryampashmi** [DaftMonk/generator-angular-fullstack#960]
Hey, i am in trouble with modal. Please can help me to solve that.
 I don't know how to use it here at all. If i have several template for modal where i have to put them? inside which folder? if i have several modal function where i have to put them? I don't know even how i use it in my html. In my case while i click on edit have to open modal. This is what i have in HTML:
button class="btn btn-xs btn-info pull-right"  ng-click="modalUpdateProvider('size',provider)">Edit</button

Then where i have to define "modalUpdateProvider" Moreover inside modal template i have a call to cancel and ok. Honestly i don't know how i use modal. I read Modal Service #580 but i didn't get. There is not any steps or simple structure which explain it well.
I posted my problem in  https://gitter.im/DaftMonk/generator-angular-fullstack but i didn't get any answer.
Please if u can give one sample example it would be helpful for everybody.

I am suggesting that to improve documentation in fullsatck as all the people are not professional with having several years of experience. Documentation is completely abstraction.

**Comment by wikett** [comment]
+1

**Comment by kingcody** [comment]
The modal service that is included is an example of wrapping [UI-Bootstrap#modal](https://angular-ui.github.io/bootstrap/#/modal) to have a higher level, reusable modal, such as a delete modal; which is what is included (`Modal.confirm.delete`).

This is an [example](https://gist.github.com/kingcody/6badcfc04c6138fff15c) of using the delete confirmation modal.

**Comment by gabrielsr** [comment]
Thanks!
