### ISSUE TITLE
Creating service on route creation

### ISSUE THREAD

**Issue by MartinWeb** [DaftMonk/generator-angular-fullstack#961]
Hi,

It would be great to allow service creation when we created a route for the client.
I don't know if it's possible, regardless to the folder architecture. I'd like to have your opinion on that point.

Thanks for your reply and for the work you on the lib :)

**Comment by Awk34** [comment]
What exactly do you mean?

**Comment by MartinWeb** [comment]
Hi,

I'll try to explain.
Practically every time i created a route with yo angular-fullstack:route, i need afterwards to create a service related to that route.
I was wondering if you think the service creation could be an option directly when the route is created.

Hope it's clearer.

**Comment by Awk34** [comment]
I don't see very many people having the same situation. It's easy enough to create a route, and then a service. I'd rather have two distinct commands for that than an annoying second option. Thanks for the feedback though.

**Comment by MartinWeb** [comment]
Yes i understand.
My project was a backoffice so for practically for each view i need to have a service to call an api. But as you said it's not the primary use case.

Thanks for the reply.
