### ISSUE TITLE
Recursive Process, Maximum Call Stack Size Exceeded

### ISSUE THREAD

**Issue by laiello** [DaftMonk/generator-angular-fullstack#964]
Hopefully I won't make a fool of myself here, I am running it in a clean environment (Ubuntu) with no modifications made to the base setup/install. When I run "grunt" and view the application in the /dist/public/ folder it works perfectly.

When I run "grunt serve", I receive a ton of node warnings and then it crashes. Abbreviated log below.

    (node) warning: Recursive process.nextTick detected. This will break in the next version of node.     Please use setImmediate for recursive deferral.
    [.......lots of these.......]
    (node) warning: Recursive process.nextTick detected. This will break in the next version of node.     Please use setImmediate for recursive deferral.
    
    util.js:35
      var str = String(f).replace(formatRegExp, function(x) {
                          ^
    RangeError: Maximum call stack size exceeded

**Comment by Awk34** [comment]
I don't believe you're on a clean install, as there is no `util.js` included in a clean install AFAIK

**Comment by laiello** [comment]
@Awk34 , there is no util.js in the root directory (http://puu.sh/hLJBq/1a7821a9c9.png). All I have done is added a README file.

**Comment by Awk34** [comment]
Which operating system are you on?

**Comment by laiello** [comment]
Ubuntu 14.04

**Comment by zoltanseer** [comment]
same problem here. xubuntu 15.04

**Comment by laiello** [comment]
That did the trick.
