### ISSUE TITLE
Change name in modal

### ISSUE THREAD

**Issue by louisscruz** [DaftMonk/generator-angular-fullstack#965]
I currently have a delete confirmation modal setup. This is my controller:

    $scope.deleteBioEntry = Modal.confirm.delete(function(entry) {
          $http.delete('/api/bio_entries/' + entry._id);
    });

When the modal pops up, it says: "Are you sure you want to delete [object Object] ?"

How can I change the name "[object Object]" to the title associated with the object being deleted?

I'm guessing I need to change `name` in my controller somehow.

    var args = Array.prototype.slice.call(arguments),
               name = args.shift(),
               deleteModal;

**Comment by kingcody** [comment]
@louisscruz sorry for the late reply. Your controller code looks fine, but in your template I have a feeling that you are passing the entry as the first argument?

`$scope.deleteBioEntry` calling signature is: `fn(NAME, [CALLBACK_ARGS...])`

I hope that clears things up a bit.

**Comment by kingcody** [comment]
Template example:
```html
<button ng-repeat="entry in entries" ng-click="deleteBioEntry(entry.name, entry)">
Delete entry {{entry.name}}
</button>
```

**Comment by louisscruz** [comment]
I've finally mastered the modal. Thank you @kingcody!
