### ISSUE TITLE
Git modified 'client/index.html client/app/app.scss'

### ISSUE THREAD

**Issue by Kageetai** [DaftMonk/generator-angular-fullstack#967]
Hi there,

just a question for my convenience: Everytime I run `grunt serve`, even if there were no new files to inject into `client/index.html` or `client/app/app.scss`, git marks them as modifified, which is pretty annoying when commiting to always need to reset or ignore them.
Is there any way to prevent that or something else?

**Comment by Awk34** [comment]
I noticed this also. I'm not exactly sure how to solve it, but haven't really tried to do any digging yet.

**Comment by Awk34** [comment]
Closing this as it's not specific to this repo

**Comment by Kageetai** [comment]
Did you find any general solution or hints?
