### ISSUE TITLE
How to Change Theme with Bootswatch

### ISSUE THREAD

**Issue by GarySwift** [DaftMonk/generator-angular-fullstack#968]
This isn't an with issue angular-fullstack as such so I will close this if requested.

My question is this. What is the best practice for installing a Bootstrap theme from [Bootswatch](https://bootswatch.com/superhero/)?

Their documentation says it I should replace the original bootsrap CSS (or LESS, or SASS) files with those downloaded from Bootswatch. However, these files are in the **bower_compenents** directory and, as such, are listed in the *.gitignore* file. So any changes I make here will not be part of version control.

Placing the files into the scss is of a route does not work and feels like the wrong approach anyway.

Is there a way I can install these using bower? Any suggestions are welcome.

**Comment by GarySwift** [comment]
After some searching I found this <https://github.com/dbtek/bootswatch-dist> which sounds exacly like what I was looking for. I should be able to install using something like:

```bower install bootswatch-dist#3.1.1-superhero --save```

Which installs a full Bootstrap installation as shown below:

```
@bootswatch-dist$ tree
.
├── bower.json
├── css
│   ├── bootstrap.css
│   └── bootstrap.min.css
├── fonts
│   ├── glyphicons-halflings-regular.eot
│   ├── glyphicons-halflings-regular.svg
│   ├── glyphicons-halflings-regular.ttf
│   └── glyphicons-halflings-regular.woff
└── js
    ├── bootstrap.js
    └── bootstrap.min.js
```

But this is still not working for me after a grunt build. I guess i should be deleting the original Bootstrap but this breaks the grunt build.

And why is there CSS, LESS and SASS in my *bower_components*? Shouldn't i just have one of these?
``` ├── bootstrap
 ├── bootstrap-less
 ├── bootstrap-sass-official```

**Comment by msjoshi** [comment]
Did this work for you at all? I'm going to try tonight and see if it works.

**Comment by GarySwift** [comment]
No, I couldn't get it working in the end so I've had to move on for the moment. As I mentioned already, [bootswatch-dist](https://github.com/dbtek/bootswatch-dist) installed all of the required bootstrap depenencies. (Unfortunately in CSS and not SASS). 

So what I would imagine the next step to be is was to remove the original bootstrap files. I was guessing this meant deleting the folders from _bower_components_ and changing _bower.json_ also.

However, I did not have any success as this caused the grunt build to fail. ( And probably rightly so).

Maybe I have approached this in the wrong way so I'll welcome any suggestions as to how this should be be done.

Another thing that was confusing was having bootstrap in CSS, SASS and LESS  format in _bower_components_. I'm using SASS in my project I would have expected to have bower install SASS files only.

Let me know how you get on anyway.

**Comment by Awk34** [comment]
You should never be editing anything inside `bower_components`.

The main Bootstrap project includes LESS and the CSS generated from it. If you don't use a stylesheet transpiler, you'll want to just include the CSS. If you use LESS, you will probably want to import Bootstrap's LESS to your own LESS so that you have access to it's variables and what not. For us Sass/SCSS users, there's the `bootstrap-sass-official` package, so that we have the same kinds of access to variables/mixins that we would have had with the main package if we had been using LESS.

I haven't read anything about bootswatch, but I assume that it wants you to remove bootstrap's official stylesheets. If you're using Sass, it's as easy as removing the `@import` inside your `app.scss` file.

**Comment by pnadig** [comment]
I have tried to include the bootswatch in one of my projects. I used the following method:
a) For ex: I wanted flatly theme, I copied the css from bootswatch site: https://bootswatch.com/flatly/bootstrap.css
into a file - mytheme.css in client/app/ folder. 
b) Now the grunt task would pick up mytheme.css and build the project. If there were any modifications required or override the default bootstrap settings : as mentioned by @Awk34 , just removed default imports from app.scss.

**Comment by GarySwift** [comment]
Ok, that makes sense. Thanks for the help.

**Comment by Awk34** [comment]
Did you get this sorted out?

**Comment by GarySwift** [comment]
@Awk34 Yes, I did get it working on my last project. However, I just tried again on a fresh install so I could show other people how to do it. This did not go so well. 

I used https://github.com/dbtek/bootswatch-dist but that causes a conflict with angular versions. Eg.

```
Unable to find a suitable version for bootswatch-dist, please choose one:
    1) bootswatch-dist#yeti which resolved to 313dca639c
    2) bootswatch-dist#~3.3.1+2-readable which resolved to 3.3.1+2-readable and is required by bootswatch
```
'app.scss' then need to modified to something like this:

```scss
$fa-font-path: "/bower_components/font-awesome/fonts";
@import "bootswatch-scss/superhero/variables";
@import "bootstrap-sass-official/assets/stylesheets/bootstrap/variables";
@import "bootstrap-sass-official/assets/stylesheets/bootstrap";
@import "bootswatch-scss/superhero/bootswatch";
@import 'font-awesome/scss/font-awesome';
```
I tried both options but both cause the grunt build to fail. Basically, it can work, but it is a messy procedure. If I find a cleaner solution I will post back here.

**Comment by Awk34** [comment]
It's probably asking what version to use because you specified the wrong one in your `bower.json`. It looks like it's asking you what `bootswatch-dist` version to use, not `angular`.

What exactly is breaking with builds? Maybe show some stack traces?

**Comment by GarySwift** [comment]
If I get time later I will later I will try again and post details here.

**Comment by EJanuszewski** [comment]
@GarySwift Did you ever get this working? I'm curious in seeing if it's possible using bower to manage this or if the only option might be to just copy the css into a stylesheet within the /app directory.

**Comment by GarySwift** [comment]
@EJanuszewski Yes, I got it working using https://github.com/dbtek/bootswatch-dist. This installed Sass versions of all the bootswatch themes. However, When I attempted to repeat the process I ran into angular conflict issues. I gave an overview of the procedure above.

**Comment by EJanuszewski** [comment]
@GarySwift Thanks for the quick reply, I'll take a look at that and see what I can manage.

**Comment by gurolayanlar** [comment]
@GarySwift you should this; add lines to it bower.json

"overrides": {
	"bootstrap": {
	  "main": "dist/css/bootstrap-flatly.css"
	}
}
  
Do you want more information? you can search for it there 
https://github.com/taptapship/wiredep#bower-overrides
