### ISSUE TITLE
Microsoft.Cpp.Default.props - not found, installation problem.

### ISSUE THREAD

**Issue by eslotwinski** [DaftMonk/generator-angular-fullstack#970]
Hi, i've a problem with installation of this generator at my local pc, i get  some kind of weird bug within this message:

here is a question: http://stackoverflow.com/questions/30309432/node-modules-installation-failed-missing-file-windows
if there is anyone who could take a look on it i would really appreciate.

**Comment by Awk34** [comment]
Looks like it's a problem with Phantom JS
