### ISSUE TITLE
Get original request parameters of an OAuth authorization

### ISSUE THREAD

**Issue by pihomeserver** [DaftMonk/generator-angular-fullstack#972]
Hello,

I use a local strategy using a SQLite database. I implemented an authorization (not authentication) for Google APIs using passport and source code of the generator. The chain works like a charm but i can't find a way to store the returned cookie from Google in the user profile. 
The passport callback request lost all parameters i passed to the original request so when it's called i can't find the ID of my user to save the token

I use the passReqToCallback parameter but can't find any useful information

Here is the content of the req.session passed to the callback (req.user is empty): 
```
{ cookie:
   { path: '/',
     _expires: Wed May 20 2015 17:00:30 GMT+0200 (CEST),
     originalMaxAge: 60000,
     httpOnly: true },
  passport: {} }
```

Do you have any idea how i could find the parameters of my first request within the success function of the passport callback ?

**Comment by Awk34** [comment]
Look at my [auth.service.js](https://github.com/Awk34/aksite/blob/master/server/auth/auth.service.js) for the `appendUser` function, and my [auth/google/index.js](https://github.com/Awk34/aksite/blob/master/server/auth/google/index.js) for how I use it in the callback.

**Comment by pihomeserver** [comment]
Sounds magic, smells magic and is magic !!!

I did not thought it was possible to call others functions before the authentication validation

Thanks so much !
