### ISSUE TITLE
Warn that mongohq costs money

### ISSUE THREAD

**Issue by adamzerner** [DaftMonk/generator-angular-fullstack#973]
If you're using mongoDB you will need to add a database to your app:

```
heroku addons:add mongohq
```

- - -

I think that it should be noted that this costs money!

**Comment by Awk34** [comment]
Not if you use a sandbox...

**Comment by ratracegrad** [comment]
You should instead run heroku addons:add mongolab .  That is free and will provide you with a mongodb that you require.

**Comment by mcpDESIGNS** [comment]
Why is using MongoDB so expensive anyway (on top of how much you have to pay to even run a VM that can handle Node, etc)
