### ISSUE TITLE
Deploying to an Azure website

### ISSUE THREAD

**Issue by jamesla** [DaftMonk/generator-angular-fullstack#980]
Hi I was wondering how I can deploy this to an azure website - I have looked around but can't find any tutorials etc. Can anybody provide any instructions or examples?

**Comment by kmcnellis** [comment]
1. add azure to your gruntfile under buildcontrol
```
    buildcontrol: {
      options: {
        dir: 'dist',
        commit: true,
        push: true,
        connectCommits: false,
        message: 'Built %sourceName% from commit %sourceCommit% on branch %sourceBranch%'
      },
      azure: {
        options: {
          remote: 'azure',
          branch: 'master'
        }
      }
    },
```

2. Run ```grunt build``
3. ```cd dist```
4. Make a new git repo under dist if it is not already one ```git init```
5. Add your azure repo as a remote (the git remote url can be gotten from the azure portal, for a web app setup with local git repo deployment)
6. Run ```grunt buildcontrol:azure``` or commit all and push master to azure

It should at this point show the deployment log from the server, and the deployment tab for your web app in azure should be updated to reflect your build status

**Comment by dustintheweb** [comment]
@kmcnellis :+1:
