### ISSUE TITLE
Mongoose Schemas Not Created

### ISSUE THREAD

**Issue by iantanwx** [DaftMonk/generator-angular-fullstack#983]
Hello, I've been using this generator to write a CMS. Unfortunately, it seems that Mongoose will not initialise any of the schemas I've created, except for the schema in seed.js. I've tried to initialise a schema in seed.js to test, and even that schema doesn't get initialised. The only schema getting initialised seems to be the Users schema.

The really odd thing is that saving Users from the front end with $resource works, but saving any other type of document in any other collections simply doesn't insert anything, and doesn't throw any errors. All HTTP response codes are also good. I'm really not sure what could be causing this issue.

I suspect it's a connection problem, but can't quite figure out what it is. I am doing this in dev environment with safe: set to true.

Thanks!

**Comment by Awk34** [comment]
If you can save users I doubt it's a connection problem. Other than that it is impossible to help you without seeing any of the code that you changed.

**Comment by iantanwx** [comment]
Sorry guys/girls, it was because I didn't call next() on one of my models. Stupid me. Took me half a day to realise I wasn't calling next().
