### ISSUE TITLE
Not getting Authentication Bolilerplate option if Database selected as "None"

### ISSUE THREAD

**Issue by becjit** [DaftMonk/generator-angular-fullstack#985]
Hi,
  When I tried  to generate the app using yo angular-fullstack [app-name] it is not giving me authentication boilerplate option if I have chosen Database as None.  I do not want to use Mongo as a backend for my application
Any workaround?

**Comment by Awk34** [comment]
If you checkout the canary branch and run it, you'll get the option to use sequelize.

**Comment by Awk34** [comment]
Did this answer your question?

**Comment by becjit** [comment]
Yes thanks
