### ISSUE TITLE
Install error on nodev0.12.4 on Ubuntu

### ISSUE THREAD

**Issue by pareeks** [DaftMonk/generator-angular-fullstack#987]
I am running an Ubuntu machine on which I've the latest version of Node.js installed. I have installed Yeoman and now trying to use the angular-fullstack generator. 
When I install generator using  npm install -g generator-angular-fullstack, I get this warning:
npm WARN peerDependencies The peer dependency yo@>=1.2.0 included from generator-angular-fullstack will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency yo@>=1.0.0 included from generator-ng-component will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

When I run yo angular-fullstack [app-name], I get this error:
You don't seem to have a generator with the name angular-fullstack installed.

Any help solving this is appreciated. Thanks!

**Comment by Awk34** [comment]
It should still let you install it. Try installing it again.

**Comment by suhyunjeon** [comment]
Maybe you installed another app-name in your app-directory.

Check it out again like what @Awk34 said.

**Comment by avisiedo** [comment]
I have the same message when I try to install "generator-angular-fullstack" with npm.

OS: 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64 (Yosemite OSX 10.10.3).
npm version: 2.10.1
node version: v0.12.4

At this moment still install, but in a future npm release, it no longer install that dependencies.

Maybe they are to update dependences file, or it has changed how to set dependencies with new npm releases. I don't know.

It appears to be two problems: one problem in "generator-angular-fullstack" package, and the other problem into "generator-ng-component" package.

Kind regards!

**Comment by Awk34** [comment]
#995
