### ISSUE TITLE
How to run grunt as daemon?

### ISSUE THREAD

**Issue by suhyunjeon** [DaftMonk/generator-angular-fullstack#988]
I want to run 'grunt serve' as daemon.

I tried to grunt-forever like this. 
https://www.npmjs.com/package/grunt-forever

in Gruntfile.js
```
    forever: {
      server1: {
        options: {
          index: '<%= yeoman.client %>/app/app.js',
          logDir: 'logs'
        }
      }
    },
```

And I run command like this
```
$ grunt forever:server1:start
```

Result
```
user@ubuntu-user:~/dev/trunk/myproject$ grunt forever:server1:start
Running "forever:server1:start" (forever) task
Attempting to start client/app/app.js as daemon.
Adding to config: errFile, undefined
Adding to config: outFile, undefined
Adding to config: logFile, undefined
Logs can be found at /home/user/dev/trunk/myproject/logs.

Done, without errors.


Execution Time (2015-06-09 05:07:58 UTC)
loading tasks          275ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 93%
forever:server1:start   18ms  ▇▇▇▇▇▇▇▇▇ 6%
Total 295ms

```

It did not works. I also tried to command like this. If I touch ctrl+c, it is close. 
```
$ grunt serve &
```

Do you have any idea how to runt grunt as daemon?

**Comment by Awk34** [comment]
Why do you want to run a development environment application as a daemon?

I would suggest either using `grunt build` to get a single `server.js` to run, or maybe use the `screen` command.

**Comment by suhyunjeon** [comment]
Thank you for reply.

If I try to ```grunt build```, I didn't get a single ```server.js````. There is no server.js in my project directory.

It is my Gruntfile.js
```
  grunt.registerTask('build', [
    'clean:dist',
    'concurrent:dist',
    'injector',
    'wiredep',
    'useminPrepare',
    'autoprefixer',
    'ngtemplates',
    'concat',
    'ngAnnotate',
    'copy:dist',
    'cdnify',
    'cssmin',
    'uglify',
    'rev',
    'usemin'
  ]);
```

**Comment by Awk34** [comment]
Err not `server.js`, `app.js`. When you run `grunt build` it will make a `dist` subdirectory. You can find the file in the `server` folder.

**Comment by suhyunjeon** [comment]
When I runt ```grunt build``` or ```grunt deploy``` it makes a dist subdirectory like what you said.
```
user@ubuntu-user:~/dev/trunk/myproject/dist$ ls
package.json  public  server
```
I can find ```/dist/server/app.js```. 

So I tried to ```forever start app.js``` (If I use forever plugin (https://github.com/nodejitsu/forever/))
```
user@ubuntu-user:~/dev/trunk/myproject$ forever start ./dist/server/app.js 
info:    Forever processing file: ./dist/server/app.js
```

It cannot connect to localhost:9000.

Understand me. I am a newbie to grunt, nodejs and so on .
Thank you

**Comment by Awk34** [comment]
Try port 8080

**Comment by suhyunjeon** [comment]
http://localhost:8080/ also cannot connect.

**Comment by Awk34** [comment]
Does it ever say "Express server listening on XXXX, in XXXX mode"?

**Comment by suhyunjeon** [comment]
When I run ```forever start app.js```, it shows message like this.
```
user@ubuntu-user:~/dev/trunk/myproject$ forever start ./dist/server/app.js 
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: ./dist/server/app.js
```

That's it. Nothing says.

http://localhost:8080/ or http://localhost:9000/ cannot connect.

**Comment by suhyunjeon** [comment]
Tried to again ```$ forever start ./dist/server/app.js -p 8080```
And I found forever logs.
```
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
info: [app.js]  [reconnectionTimer : ] try cnt : 0
/api/solr/index.js in server
info:  [app.js] Mongoose default connection open
~                                                        
```

I thought, it is not enough logs. I will check the Error and after try to again. 
Wait a minute.

**Comment by YoungsoonLee** [comment]
Thank you Awk34
I support to suhyunjeon with mother language. :)

안녕하세요 한국분 맞으시죠?^^ 
음 일단 제 경우 grunt file은 수정 없이 node_env가 development 이거나 test 경우는 프로젝트 루트 폴더에서   forever start ./server/app.js 로 하면 잘 됩니다.  만일 빌드된 dist 폴더를 구동 하고 싶으실 경우 node_env를 production으로 셋팅을 먼저 하고 forever start ./server/app.js 8080 하시면 잘 됩니다.

그럼 행운을 빌겠습니다 ^^

**Comment by suhyunjeon** [comment]
YoungsooLee님 답변 감사드려요! 

원래 development 모드 프로젝트 root 에서 ```forever start ./dist/server/app.js'를 실행했는데도 안됐어요.
그래서 forever 실행 시 생성되는 로그파일을 확인하여 에러 부분을 잡다가, 
아래 처럼 초기화를 하고 npm을 재설치 했어요. 
````
rm -rm node_modules/
npm cache clean
npm config set python python2.7
npm install
````

그 후에 답변주신대로 node_env=production으로 설정, 프로젝트 root 에서 ```forever start ./dist/server/app.js'를 실행하니 누가 뭐라할것도 없이 실행이 깔끔하게 잘 되네요!! 

고맙습니다 ^^ 

Thank you Awk34. It works.

**Comment by Awk34** [comment]
Haha well I have no idea what that means, but glad to hear it works!

**Comment by gaboAcosta** [comment]
Wow, you guys just effefctively answered the question to anyone... that speaks your language that is.

I'm trying to figure this out as well and now I can't :(

**Comment by samsfisher** [comment]
Tried to decipher the korean in the above posts. 

Clean the npm modules

rm -rm node_modules/
npm cache clean
npm config set python python2.7
npm install

Set your node_env variable inside the dist
node_env = production

forever start ./dist/server/app.js  will now work.

**Comment by Awk34** [comment]
@samsfisher running forever with `start` is probably the best way to run a node app as a daemon. Also, closing this issue.

**Comment by gaboAcosta** [comment]
I dont want to re open this, I just wanted to leave here my workflow for anyone needing this.

I do a grunt build, then cd into the dist/server folder, and with forever I run forever start app.js

On Apache using the proxy mod I register a Vhost with the following configs:

```
<VirtualHost *:80>
  ServerName yourdomain.com
  ServerAlias www.yourdomain.com

  ## Vhost docroot
  DocumentRoot "/var/www/project"

  <Directory "/var/www/project">
    AllowOverride All
    Require all granted
  </Directory>

  ## Load additional static includes


  ## Logging
  ErrorLog "/var/log/apache2/yourdomain_error.log"
  ServerSignature Off
  CustomLog "/var/log/apache2/yourdomain_error.log" combined

  #Without this the sockets dont work

  RewriteEngine On
  RewriteCond %{REQUEST_URI}  ^/socket.io            [NC]
  RewriteCond %{QUERY_STRING} transport=websocket    [NC]
  RewriteRule /(.*)           ws://localhost:8080/$1 [P,L]

  <Proxy *>
	  Order deny,allow
	  Allow from all
  </Proxy>
	 
	<Location />
	    ProxyPass http://localhost:8080/
	    ProxyPassReverse http://localhost:8080/
	</Location>
</VirtualHost>
```
