### ISSUE TITLE
socket.io not being served on a fresh setup in production

### ISSUE THREAD

**Issue by pthieuklick** [DaftMonk/generator-angular-fullstack#990]
Steps to reproduce:

1. run `yo angular-fullstack APP_NAME`
2. go into server/config/express.js and comment out the `if ('production' === env) {` block, take out the conditional for development so that the code within the development block will always run
3. run `NODE_ENV=production PORT=9000 node server/app.js`
    It seems to be working on a `grunt build:dist` then running above command on `dist/server/app.js` though.
4. go to webapp on browser and open up console and you'll see 'Failed to load resource: the server responded with a status of 400 (Bad Request)'
5. io will also not be defined and will prevent all javascript from working.

You can go into server/app.js and change the serveClient option to always be 'true'. This will fix it for local machine but I've tried to deploy on AWS with this and it still didn't work.

I had a working app, did an `npm install` and `grunt build` and then `NODE_ENV=production PORT=9000 node server/app.js` and it broke so maybe a package issue?

**Comment by pthieuklick** [comment]
Nevermind.

google-code-prettify package does not play well with angular-fullstack.

**Comment by monkeymars** [comment]
how you resolve this issue @pthieuklick ?
